//! Parameterized creators: free functions that build a [`Semigroup`] (or its
//! generator list) from explicit numeric arguments.
//!
//! The randomized counterparts live in [`super::random_creators`].

use super::{Semigroup, compute};

/// Fixed list of primes the "P" / `random_primes_subset` creator samples
/// from. Mirrors the JavaScript `PRIMES_LIST` constant in `jsmodules/app.js`.
pub const PRIMES_LIST: &[usize] = &[
    2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97,
];

/// Generator list for `T(m, f)` — `[m, f+1, f+2, …, f+m]`.
#[must_use]
pub fn tmf_generators(m: usize, f: usize) -> Vec<usize> {
    let mut gens = Vec::with_capacity(m + 1);
    gens.push(m);
    for i in 0..m {
        gens.push(f + 1 + i);
    }
    gens
}

/// `T(m, f)` — the semigroup `⟨m, f+1, f+2, …, f+m⟩`.
///
/// Standard construction with multiplicity `m` and Frobenius number `f`
/// (when `f ≥ m`). The Apéry set is `(0, f+1, f+2, …, f+m−1)` in residue
/// order; for `f = 2m` this matches the original H(m, k=2) form.
///
/// # Panics
/// Panics when `m == 0`, since [`compute`] requires a non-zero multiplicity.
#[must_use]
pub fn tmf(m: usize, f: usize) -> Semigroup {
    compute(&tmf_generators(m, f))
}

/// Generator list for `A(m, d, n)` — `[m, m+d, m+2d, …, m+nd]`.
#[must_use]
pub fn arith_generators(m: usize, d: usize, n: usize) -> Vec<usize> {
    (0..=n).map(|i| m + i * d).collect()
}

/// `A(m, d, n)` — the arithmetic-sequence semigroup `⟨m, m+d, m+2d, …, m+nd⟩`.
///
/// # Panics
/// Panics when `m == 0`. Callers should ensure `gcd(m, d) = 1` if a
/// proper numerical semigroup is desired (otherwise `compute` divides
/// out the common factor and reports the rescaled multiplicity).
#[must_use]
pub fn arith(m: usize, d: usize, n: usize) -> Semigroup {
    compute(&arith_generators(m, d, n))
}

/// "Rolf primes" generator list: `p_n` together with every prime `p` with
/// `p_n < p ≤ 5·p_n`, where `p_1 = 2`.
///
/// Returns just the generator list (not a [`Semigroup`]); call [`compute`]
/// on the result to obtain the semigroup. `n` is clamped to `≥ 1`.
#[must_use]
pub fn rolf_primes(n: usize) -> Vec<usize> {
    let idx = n.max(1);
    #[allow(clippy::cast_possible_truncation)]
    let upper = primal::estimate_nth_prime(idx as u64).1 as usize;
    let sieve = primal::Sieve::new(upper * 5);
    let pn = sieve.primes_from(0).nth(idx - 1).unwrap_or(2);
    sieve.primes_from(pn).take_while(|&p| p <= 5 * pn).collect()
}

/// `Rolf(n)` — the semigroup generated by [`rolf_primes`].
#[must_use]
pub fn rolf(n: usize) -> Semigroup {
    compute(&rolf_primes(n))
}
