//! Manipulators: methods on [`Semigroup`] that return another [`Semigroup`].
//!
//! Every method here has the shape `(&self, …) -> Semigroup`. They live in a
//! second `impl Semigroup` block to keep `semigroup.rs` focused on the data
//! type and its inspectors.

use super::Semigroup;
use super::compute;
use super::symmetric_partner::symmetric_partner;

impl Semigroup {
    /// Toggle generator `n`: if `n` is a gap, add it as a new generator;
    /// if `n` is a minimal generator, remove it and recompute the generator set.
    /// Returns `self` unchanged if the operation would produce an empty generator set.
    #[must_use]
    pub fn toggle(&self, n: usize) -> Self {
        if self.is_gap(n) {
            let mut newgen = self.gen_set.clone();
            newgen.push(n);
            compute(&newgen)
        } else {
            let is_newgen = |x: usize| {
                (x > n && self.element(x)) || (x < n && self.element(x) && !self.element(n - x))
            };
            let newgen: Vec<usize> = (1..=(self.f + self.m)).filter(|&x| is_newgen(x)).collect();
            if newgen.is_empty() {
                return self.clone();
            }
            compute(&newgen)
        }
    }

    /// Fast descent: collapses every [`Self::descent_flip`] step needed to drop
    /// `f` by exactly `m` into a single closure computation.
    ///
    /// Returns `self` when `f < 2m`. Otherwise extends the generator set
    /// with `x − m` for every Apéry element `x > f`, then closes. The
    /// `x = f + m` case contributes `f` itself; cases with `x ∈ (f, f+m)`
    /// contribute the gap below `x` in the same residue class. The result
    /// satisfies `result.f == self.f − self.m` and `result.mu == self.mu`.
    #[must_use]
    pub fn fast_descent(&self) -> Self {
        if self.f < 2 * self.m {
            return self.clone();
        }
        let mut newgen = self.gen_set.clone();
        // x > f ≥ 2m here, so x − m ≥ m + 1.
        newgen.extend(
            self.apery_set
                .iter()
                .filter(|&&x| x > self.f)
                .map(|&x| x - self.m),
        );
        compute(&newgen)
    }

    /// Returns S/2 = {n ≥ 0 : 2n ∈ S}, the half of `self`.
    #[must_use]
    pub fn compute_s_over_2(&self) -> Self {
        let new_generators: Vec<usize> = (1..usize::midpoint(self.f, self.m) + 2 * self.m)
            .filter(|&x| self.element(2 * x))
            .collect();
        compute(&new_generators)
    }

    /// Returns the semigroup obtained by adding every pseudo-Frobenius number
    /// other than `f` itself as a generator.
    #[must_use]
    pub fn compute_add_all_pf(&self) -> Self {
        let mut current_gen_set = self.gen_set.clone();
        current_gen_set.extend(self.pf_set.iter().copied().filter(|&x| x != self.f));
        compute(&current_gen_set)
    }

    /// Returns the semigroup obtained by adding every reflected gap as a generator.
    #[must_use]
    pub fn compute_add_reflected_gaps(&self) -> Self {
        let mut current_gen_set = self.gen_set.clone();
        let mut current_blob = self.blob();
        current_gen_set.append(&mut current_blob);
        compute(&current_gen_set)
    }

    /// Returns the symmetric partner S̄ such that S = S̄/2 = {n | 2n ∈ S̄}.
    ///
    /// See [`crate::math::symmetric_partner`] for the full construction.
    #[must_use]
    pub fn compute_symmetric_partner(&self) -> Self {
        symmetric_partner(self)
    }

    /// Returns the canonical ideal K(S) as a numerical semigroup.
    ///
    /// The minimal generators of K(S) are `{f − p : p ∈ PF(S), p ≠ f}`.
    /// For symmetric semigroups (where PF(S) = {f}), K(S) = S, so `self` is returned.
    #[must_use]
    pub fn canonical_ideal(&self) -> Self {
        // f is always in PF(S), but f − f = 0 is not a semigroup generator.
        let gens: Vec<usize> = self
            .pf_set
            .iter()
            .filter(|&&p| p != self.f)
            .map(|&p| self.f - p)
            .collect();
        if gens.is_empty() {
            // Symmetric semigroup: K(S) = S by definition.
            return self.clone();
        }
        compute(&gens)
    }

    /// Returns the semigroup generated by `m, w₁ + m, w₂, …, w_{m-1}`,
    /// where `wᵢ = apery_set[i]`. (`m` is included to keep the multiplicity
    /// fixed; the Apéry-only notation `〈w₁+m, w₂, …〉` treats `m` as implicit.)
    ///
    /// Motivation (Kunz cone): adding `(2, 1, 1, …, 1)` to row 1 of the Kunz
    /// matrix `C` gives `U(m) · (2, 1, …, 1)ᵀ = (m, 0, …, 0)ᵀ`, so the
    /// candidate new Apéry vector is `(w₁ + m, w₂, …, w_{m-1})`. That move is
    /// feasible iff every antidiagonal entry `c_{a,b}` with `(a + b) ≡ 1 (mod
    /// m)` and `a, b ≠ 1` is ≥ 1. When the move is feasible the result has
    /// multiplicity `m` and exactly that Apéry vector; when it is blocked, the
    /// resulting semigroup equals the original (its old `w₁` is recovered as a
    /// sum of the remaining generators).
    ///
    /// For `m < 2`, returns `self` unchanged.
    #[must_use]
    pub fn compute_apery_shift_first(&self) -> Self {
        if self.m < 2 {
            return self.clone();
        }
        let mut gens = Vec::with_capacity(self.m);
        gens.push(self.m);
        gens.push(self.apery_set[1] + self.m);
        gens.extend_from_slice(&self.apery_set[2..]);
        compute(&gens)
    }

    /// Removes the atom `a` from the generator set, returning the semigroup
    /// generated by `gen(S) \ {a}`.
    ///
    /// Distinct from [`Self::toggle`]: `toggle(a)` removes `a` set-theoretically
    /// (giving `S \ {a}`), while `destroy_atom(a)` only removes `a` from the
    /// generator set, leaving any element of `S` expressible without `a`
    /// in the result. Returns `self` if `a` is not currently a minimal generator.
    #[must_use]
    pub fn destroy_atom(&self, a: usize) -> Self {
        if self.gen_set.contains(&a) {
            let new_gen_set: Vec<usize> = self
                .gen_set
                .iter()
                .copied()
                .filter(|x| x != &a)
                .collect::<Vec<_>>();
            compute(&new_gen_set)
        } else {
            self.clone()
        }
    }

    /// Ascent (total): destroy the atom `f + m`, the largest Apéry element
    /// of `S`. Returns `self` when `f + m` is not a minimal generator.
    ///
    /// When the destruction fires, the new Apéry vector keeps every
    /// `w_i` for `i ≠ μ` and lifts `w_μ` from `f + m` to `f + (ρ + 1)·m`,
    /// where `ρ = self.rho()`. Consequences (asserted in `tests/`):
    /// `g' = g + ρ`, `σ' = σ − (ρ − 1)·(m − 2) − 1`, and
    /// `r' = r − ρ·(m − 2)`.
    ///
    /// Inverse: [`Self::descent_total`] recovers `self` when applied to the
    /// result, provided `m ≥ 2` and `ρ ≥ 1` (so the multiplicity is preserved).
    #[must_use]
    pub fn ascent_total(&self) -> Self {
        let ae = self.f + self.m;
        if self.gen_set.contains(&ae) {
            self.destroy_atom(ae)
        } else {
            self.clone()
        }
    }

    /// Descent (total): a canonical left-inverse of [`Self::ascent_total`].
    /// Walks the strata `(f − (l+1)m, f − l m)` for `l = 1, 2, …` and stops
    /// at the first `l` at which the stratum is **not** entirely contained
    /// in `S`. Adds `f − (l − 1)·m` (a residue-`μ` gap of `S`) as a new
    /// generator.
    ///
    /// **Not a universal inverse of `ascent_total`.** `ascent_total` is
    /// not injective: many semigroups `S` with the same `m` and the same
    /// non-`μ` Apéry entries collapse to the same `U` after removing
    /// `f + m`. `descent_total(U)` picks the canonical pre-image rooted
    /// at the first "kink" stratum, which may differ from `S`. The
    /// round-trip `S → ascent_total → descent_total = S` holds in the
    /// hand-picked cases of
    /// `test_ascent_total_descent_total_round_trip_fpm_branch`, but fails
    /// for e.g. `⟨12, 14, 19, 77⟩` (whose canonical pre-image of
    /// `⟨12, 14, 19⟩` is `⟨12, 14, 19, 65⟩`).
    ///
    /// Returns `self` when `f < m` (`S = ℕ`) or when every stratum below
    /// `(f − m, f)` is fully in `S` (only possible in tiny edge cases like
    /// `μ = 1`).
    #[must_use]
    pub fn descent_total(&self) -> Self {
        if self.f < self.m {
            return self.clone();
        }
        // Stratum-l predicate: returns true iff (f − (l+1)m, f − l m) ⊆ S.
        // For l in 1..=level we have l·m ≤ level·m < f, so the upper bound
        // `f − l·m` is always strictly positive; the lower bound can underflow
        // when (l+1)·m > f, in which case we clamp to 0 (the interval still
        // makes sense as (0, f − l·m)).
        let stratum_in_s = |l: usize| -> bool {
            let upper = self.f - l * self.m;
            let lower = (l + 1)
                .checked_mul(self.m)
                .and_then(|p| self.f.checked_sub(p))
                .unwrap_or(0);
            ((lower + 1)..upper).all(|y| self.element(y))
        };
        for l in 1..=self.level {
            if !stratum_in_s(l) {
                return self.toggle(self.f - (l - 1) * self.m);
            }
        }
        self.clone()
    }

    /// Descent (flip): a controlled step down the gaps ladder that always
    /// changes the genus by exactly `−1`.
    ///
    /// Walks the strata `(f − (l+1)m, f − l m)` for `l = 0, 1, …, level − 1`
    /// and, at the first stratum that contains an Apéry element of `S`,
    /// picks the largest such Apéry `w` and adds `w − m` as a new
    /// generator. The added value is always a gap (it is the predecessor
    /// of `w` in the same residue class), so the resulting semigroup
    /// satisfies `g' = g − 1`, `σ' = σ + 1`, `r' = r − 2`.
    ///
    /// **Never adds `f`**: the `l = 0` stratum filter is `w ∈ (f, f + m)`
    /// strictly, which excludes `w = f + m` (the only Apéry that would
    /// contribute `f`). When the only Apéry above `f` is `f + m` and no
    /// in-stratum match is found at any `l`, the function returns `self`.
    ///
    /// Returns `self` when `f < m` (`S = ℕ`).
    ///
    /// Duality: [`Self::ascent_flip`] is its structural reverse — see that
    /// function's doc comment for the conditions under which
    /// `ascent_flip ∘ descent_flip = id`.
    #[must_use]
    pub fn descent_flip(&self) -> Self {
        if self.f < self.m {
            return self.clone();
        }
        let mut newgen = self.gen_set.clone();
        let amu = self.f + self.m;
        for l in 0..self.level {
            if let Some(largest) = self
                .apery_set
                .iter()
                .filter(|&&x| x + l * self.m > self.f && x + l * self.m < amu)
                .max()
            {
                newgen.push(*largest - self.m);
                return compute(&newgen);
            }
        }
        self.clone()
    }

    /// Ascent (flip): structural reverse of [`Self::descent_flip`].
    ///
    /// The interval `(μ, f)` decomposes into `self.level` **strata** of
    /// width `m`: stratum `l` is `(f − (l+1)m, f − l m)`, for
    /// `l = 0, 1, …, level − 1`. Stratum 0 is `V(S) = (f − m, f)`.
    ///
    /// For each stratum (shallow to deep) and each `k = 1, …, level`,
    /// look for the largest atom `a` such that `k·a` is an Apéry element
    /// of `S` landing in that stratum (and `> m`). Pick that atom `w` and
    /// toggle it. The result satisfies `g' = g + 1`, `σ' = σ − 1`,
    /// `r' = r + 2`.
    ///
    /// **Never removes `f + m`**: the filter `v + l·m < f` excludes
    /// `v = f + m` at every `l`, so the largest Apéry element is left
    /// alone. Use [`Self::ascent_total`] for that case.
    ///
    /// Returns `self` when no `(l, k)` produces a match.
    #[must_use]
    pub fn ascent_flip(&self) -> Self {
        // Apéry membership is O(1) via residue indexing:
        // v ∈ apery_set  ⇔  apery_set[v mod m] == v.
        let is_apery = |v: usize| self.apery_set[v % self.m] == v;
        for l in 0..self.level {
            for k in 1..=self.level {
                let removable = |a: usize| -> bool {
                    let v = k * a;
                    v > self.m && v + l * self.m < self.f && v + (l + 1) * self.m > self.f
                };
                if let Some(w) = self
                    .gen_set
                    .iter()
                    .copied()
                    .filter(|&a| removable(a) && is_apery(k * a))
                    .max()
                {
                    return self.toggle(w);
                }
            }
        }
        self.clone()
    }
}
