//! Manipulators: methods on [`Semigroup`] that return another [`Semigroup`].
//!
//! Every method here has the shape `(&self, …) -> Semigroup`. They live in a
//! second `impl Semigroup` block to keep `semigroup.rs` focused on the data
//! type and its inspectors.

use super::Semigroup;
use super::compute;
use super::symmetric_partner::symmetric_partner;

impl Semigroup {
    /// Toggle generator `n`: if `n` is a gap, add it as a new generator;
    /// if `n` is a minimal generator, remove it and recompute the generator set.
    /// Returns `self` unchanged if the operation would produce an empty generator set.
    #[must_use]
    pub fn toggle(&self, n: usize) -> Self {
        if self.is_gap(n) {
            let mut newgen = self.gen_set.clone();
            newgen.push(n);
            compute(&newgen)
        } else {
            let is_newgen = |x: usize| {
                (x > n && self.element(x)) || (x < n && self.element(x) && !self.element(n - x))
            };
            let newgen: Vec<usize> = (1..=(self.f + self.m)).filter(|&x| is_newgen(x)).collect();
            if newgen.is_empty() {
                return self.clone();
            }
            compute(&newgen)
        }
    }

    /// Fast descent: collapses every [`Self::descent_flip`] step needed to drop
    /// `f` by exactly `m` into a single closure computation.
    ///
    /// Returns `self` when `f < 2m`. Otherwise extends the generator set
    /// with `x − m` for every Apéry element `x > f`, then closes. The
    /// `x = f + m` case contributes `f` itself; cases with `x ∈ (f, f+m)`
    /// contribute the gap below `x` in the same residue class. The result
    /// satisfies `result.f == self.f − self.m` and `result.mu == self.mu`.
    #[must_use]
    pub fn fast_descent(&self) -> Self {
        if self.f < 2 * self.m {
            return self.clone();
        }
        let mut newgen = self.gen_set.clone();
        // x > f ≥ 2m here, so x − m ≥ m + 1.
        newgen.extend(
            self.apery_set
                .iter()
                .filter(|&&x| x > self.f)
                .map(|&x| x - self.m),
        );
        compute(&newgen)
    }

    /// Returns S/2 = {n ≥ 0 : 2n ∈ S}, the half of `self`.
    #[must_use]
    pub fn compute_s_over_2(&self) -> Self {
        let new_generators: Vec<usize> = (1..usize::midpoint(self.f, self.m) + 2 * self.m)
            .filter(|&x| self.element(2 * x))
            .collect();
        compute(&new_generators)
    }

    /// Returns the semigroup obtained by adding every pseudo-Frobenius number
    /// other than `f` itself as a generator.
    #[must_use]
    pub fn compute_add_all_pf(&self) -> Self {
        let mut current_gen_set = self.gen_set.clone();
        current_gen_set.extend(self.pf_set.iter().copied().filter(|&x| x != self.f));
        compute(&current_gen_set)
    }

    /// Returns the semigroup obtained by adding every reflected gap as a generator.
    #[must_use]
    pub fn compute_add_reflected_gaps(&self) -> Self {
        let mut current_gen_set = self.gen_set.clone();
        let mut current_blob = self.blob();
        current_gen_set.append(&mut current_blob);
        compute(&current_gen_set)
    }

    /// Returns the symmetric partner S̄ such that S = S̄/2 = {n | 2n ∈ S̄}.
    ///
    /// See [`crate::math::symmetric_partner`] for the full construction.
    #[must_use]
    pub fn compute_symmetric_partner(&self) -> Self {
        symmetric_partner(self)
    }

    /// Returns the canonical ideal K(S) as a numerical semigroup.
    ///
    /// The minimal generators of K(S) are `{f − p : p ∈ PF(S), p ≠ f}`.
    /// For symmetric semigroups (where PF(S) = {f}), K(S) = S, so `self` is returned.
    #[must_use]
    pub fn canonical_ideal(&self) -> Self {
        // f is always in PF(S), but f − f = 0 is not a semigroup generator.
        let gens: Vec<usize> = self
            .pf_set
            .iter()
            .filter(|&&p| p != self.f)
            .map(|&p| self.f - p)
            .collect();
        if gens.is_empty() {
            // Symmetric semigroup: K(S) = S by definition.
            return self.clone();
        }
        compute(&gens)
    }

    /// Returns the semigroup generated by `m, w₁ + m, w₂, …, w_{m-1}`,
    /// where `wᵢ = apery_set[i]`. (`m` is included to keep the multiplicity
    /// fixed; the Apéry-only notation `〈w₁+m, w₂, …〉` treats `m` as implicit.)
    ///
    /// Motivation (Kunz cone): adding `(2, 1, 1, …, 1)` to row 1 of the Kunz
    /// matrix `C` gives `U(m) · (2, 1, …, 1)ᵀ = (m, 0, …, 0)ᵀ`, so the
    /// candidate new Apéry vector is `(w₁ + m, w₂, …, w_{m-1})`. That move is
    /// feasible iff every antidiagonal entry `c_{a,b}` with `(a + b) ≡ 1 (mod
    /// m)` and `a, b ≠ 1` is ≥ 1. When the move is feasible the result has
    /// multiplicity `m` and exactly that Apéry vector; when it is blocked, the
    /// resulting semigroup equals the original (its old `w₁` is recovered as a
    /// sum of the remaining generators).
    ///
    /// For `m < 2`, returns `self` unchanged.
    #[must_use]
    pub fn compute_apery_shift_first(&self) -> Self {
        if self.m < 2 {
            return self.clone();
        }
        let mut gens = Vec::with_capacity(self.m);
        gens.push(self.m);
        gens.push(self.apery_set[1] + self.m);
        gens.extend_from_slice(&self.apery_set[2..]);
        compute(&gens)
    }

    /// Removes the atom `a` from the generator set, returning the semigroup
    /// generated by `gen(S) \ {a}`.
    ///
    /// Distinct from [`Self::toggle`]: `toggle(a)` removes `a` set-theoretically
    /// (giving `S \ {a}`), while `destroy_atom(a)` only removes `a` from the
    /// generator set, leaving any element of `S` expressible without `a`
    /// in the result. Returns `self` if `a` is not currently a minimal generator.
    #[must_use]
    pub fn destroy_atom(&self, a: usize) -> Self {
        if self.gen_set.contains(&a) {
            let new_gen_set: Vec<usize> = self
                .gen_set
                .iter()
                .copied()
                .filter(|x| x != &a)
                .collect::<Vec<_>>();
            compute(&new_gen_set)
        } else {
            self.clone()
        }
    }

    /// Ascent (total): destroy the atom `f + m`, the largest Apéry element
    /// of `S`. Returns `self` when `f + m` is not a minimal generator.
    ///
    /// When the destruction fires, the new Apéry vector keeps every
    /// `w_i` for `i ≠ μ` and lifts `w_μ` from `f + m` to `f + (ρ + 1)·m`,
    /// where `ρ = self.rho`. Consequences (asserted in `tests/`):
    /// `g' = g + ρ`, `σ' = σ − (ρ − 1)·(m − 2) − 1`, and
    /// `r' = r − ρ·(m − 2)`.
    ///
    /// Inverse: [`Self::descent_total`] recovers `self` when applied to the
    /// result, provided `m ≥ 2` and `ρ ≥ 1` (so the multiplicity is preserved).
    #[must_use]
    pub fn ascent_total(&self) -> Self {
        let ae = self.f + self.m;
        if self.gen_set.contains(&ae) {
            self.destroy_atom(ae)
        } else {
            self.toggle(self.f + self.m)
        }
    }

    /// Descent (total), per the writeup.
    ///
    /// Let `V = {z ∈ ℕ : z ≢ 0 (mod m) and z ≢ μ (mod m)}`. Define
    /// `L = max(V ∩ G(S))`, the largest gap of `S` in `V`. Let
    /// `l = ⌊L/m⌋` and `L_↓ = μ + l·m`. Then `descent_total(S) = S ∪ {L_↓}`.
    ///
    /// `L_↓` is always a residue-μ gap of `S` (by `w_μ = f+m`, every
    /// residue-μ element ≤ f is a gap; the construction guarantees
    /// `L_↓ ≤ f`).
    ///
    /// **Multiplicity may change**: when `l = 0` (i.e. when `L < m`),
    /// `L_↓ = μ < m`, so the result has multiplicity `μ` rather than `m`.
    /// The writeup flags this as the only structural caveat.
    ///
    /// Returns `self` when `m < 3` (the writeup assumes `m > 2`).
    #[must_use]
    pub fn descent_total(&self) -> Self {
        if self.m < 3 {
            return self.clone();
        }
        // L = max(V ∩ G(S)) = max over residues r ∈ V of (w_r − m).
        let Some(big_l) = (1..self.m)
            .filter(|&r| r != self.mu)
            .map(|r| self.apery_set[r] - self.m)
            .max()
        else {
            // For m > 2, V has m − 2 ≥ 1 residues, so this is unreachable;
            // defensively return self.
            return self.clone();
        };
        let l = big_l / self.m;
        let target = self.mu + l * self.m;
        self.toggle(target)
    }

    /// Descent (flip): walks the strata `(f − (l+1)m, f − l m)` for
    /// `l = 0, 1, …, level − 1` and, at the first stratum that contains
    /// an Apéry element of `S`, picks the largest such Apéry `w` and
    /// adds `w − m` as a new generator. The added value is always a gap
    /// (the predecessor of `w` in the same residue class).
    ///
    /// **Never adds `f`**: the `l = 0` stratum filter is `w ∈ (f, f + m)`
    /// strictly, which excludes `w = f + m`. When the only Apéry above
    /// `f` is `f + m` and no in-stratum match is found at any `l`, the
    /// function returns `self`.
    ///
    /// Returns `self` when `f < m` (`S = ℕ`) or when `m < 3` (for `m = 2`
    /// the flip move is structurally vacuous; use [`Self::descent_total`]
    /// instead).
    ///
    /// Invertibility is **not** enforced here. `ascent_flip` is the
    /// structural reverse but their composition is the identity only
    /// under conditions we do not check at call time; see
    /// [`Self::ascent_flip`].
    #[must_use]
    pub fn descent_flip(&self) -> Self {
        if self.m < 3 || self.f < self.m {
            return self.clone();
        }
        let mut newgen = self.gen_set.clone();
        let amu = self.f + self.m;
        for l in 0..self.level {
            if let Some(largest) = self
                .apery_set
                .iter()
                .filter(|&&x| x + l * self.m > self.f && x + l * self.m < amu)
                .max()
            {
                newgen.push(*largest - self.m);
                return compute(&newgen);
            }
        }
        self.clone()
    }

    /// Ascent (flip), per the writeup.
    ///
    /// Let `V = {z ∈ ℕ : z ≢ 0 (mod m) and z ≢ μ (mod m)}` and
    /// `X = (ℕ_{>0} · Atom(S)) ∩ V ∩ Ap(S)` — the Apéry elements in `V`
    /// that are positive multiples of some atom. Pick `w = max(X)`, then
    /// `a_↑ = max{a ∈ Atom(S) : a ∣ w}`. Return `S \ {a_↑}`, i.e. the
    /// maximal subsemigroup of `S` not containing `a_↑` ([`Self::toggle`]).
    ///
    /// For `m > 2`, `X` is non-empty: every atom in `Atom(S) \ {m, f+m}`
    /// is itself in `X` (atoms are Apéry, in `V` by `w_μ = f+m`), and
    /// that set is non-empty (else `Atom(S) = {m, f+m}` would force
    /// embedding dimension 2 and hence `m = 2` via the 2-generator
    /// Frobenius identity).
    ///
    /// Returns `self` when `m < 3`.
    #[must_use]
    pub fn ascent_flip(&self) -> Self {
        if self.m < 3 {
            return self.clone();
        }
        // X = {w_r : r ∈ V} ∩ {multiples of some atom}.
        let Some(w) = (1..self.m)
            .filter(|&r| r != self.mu)
            .map(|r| self.apery_set[r])
            .filter(|&w| self.gen_set.iter().any(|&a| w.is_multiple_of(a)))
            .max()
        else {
            return self.clone();
        };
        // a_↑ = largest atom dividing w (non-empty by construction of X).
        let Some(a_up) = self
            .gen_set
            .iter()
            .copied()
            .filter(|&a| w.is_multiple_of(a))
            .max()
        else {
            return self.clone();
        };
        self.toggle(a_up)
    }
}
