//! Core numerical-semigroup algorithms: the [`compute`] entry point, the
//! [`Semigroup`] data type, the GAP code generator, and helpers for related
//! constructions (gluing, matrix views, symmetric partner).

/// Parameterized creators: T(m,f), A(m,d,n), Rolf primes.
pub mod creators;
/// Self-gluing of a numerical semigroup: `m·S + x·S` with `gcd(m, x) = 1`.
pub mod glue;
/// Manipulators: `(&Semigroup, …) -> Semigroup` methods.
pub mod manipulators;
/// Dense `i64` matrices over the integers, with the U(m) and Kunz matrices.
pub mod matrix;
/// Randomized creators: `() -> Semigroup` constructions backed by `rand`.
pub mod random_creators;
/// The [`Semigroup`] struct and its derived properties.
pub mod semigroup;
/// The [`compute`] entry point: sliding-window construction of a `Semigroup`.
pub mod semigroup_compute;
/// Symmetric partner construction (Rosales–García-Sánchez 2008).
pub mod symmetric_partner;

pub use semigroup::Semigroup;
pub use semigroup_compute::compute;

/// Greatest common divisor of two numbers (Euclidean algorithm).
#[must_use]
pub const fn gcd(mut a: usize, mut b: usize) -> usize {
    while b != 0 {
        (a, b) = (b, a % b);
    }
    a
}

/// Greatest common divisor of a non-empty slice of numbers.
#[must_use]
pub fn gcd_vec(numbers: &[usize]) -> usize {
    let mut d = numbers[0];
    for m in &numbers[1..] {
        d = gcd(d, *m);
    }
    d
}

/// Binomial coefficient C(a, b) = a! / (b! · (a − b)!).
///
/// Returns `Some(0)` when `b > a` and `Some(1)` when `b = 0` or `b = a`.
/// Returns `None` if the result would overflow `usize` (relevant under
/// `wasm32`, where `usize` is 32 bits — e.g. C(34, 17) already overflows).
///
/// Computes `min(b, a−b)` factors and divides as it goes; the partial
/// product is exactly divisible by `(i+1)!` at each step, so the
/// intermediate value never exceeds the final result.
#[must_use]
pub const fn binom(a: usize, b: usize) -> Option<usize> {
    if b > a {
        return Some(0);
    }
    let k = if b < a - b { b } else { a - b };
    let mut result: usize = 1;
    let mut i: usize = 0;
    while i < k {
        // result · (a − i) is exactly divisible by (i + 1) at this step,
        // because it equals C(a, i+1) · (i+1)! / 1 — checked-arithmetic
        // throughout to surface overflow.
        let Some(prod) = result.checked_mul(a - i) else {
            return None;
        };
        result = prod / (i + 1);
        i += 1;
    }
    Some(result)
}

// ── GAP code generation ──────────────────────────────────────────────────────

/// Header prepended to every generated GAP verification script.
pub const GAP_HEADER: &str = "# Generated by f3m — paste into GAP or run with 'gap <file>'\n\
    # Requires: LoadPackage(\"NumericalSgps\");\n\n\
    LoadPackage(\"NumericalSgps\");;\n\n";
/// Footer appended to every generated GAP verification script.
pub const GAP_FOOTER: &str = "Print(\"All assertions passed.\\n\");\n";

/// Emit a GAP script (`NumericalSgps` package) that reconstructs each semigroup
/// and asserts all properties computed by this library, so the results can be
/// verified interactively in GAP.
#[must_use]
pub fn to_gap(semigroups: &[Semigroup]) -> String {
    let mut out = GAP_HEADER.to_string();
    for (i, sg) in semigroups.iter().enumerate() {
        out.push_str(&gap_block(sg, i + 1));
    }
    out.push_str(GAP_FOOTER);
    out
}

/// Emit the GAP assertions for a single semigroup, using `ng{idx}` as the variable name.
#[must_use]
pub fn gap_block(sg: &Semigroup, idx: usize) -> String {
    use std::fmt::Write as _;
    let gens = sg.gen_set.iter().map(usize::to_string).collect::<Vec<_>>();
    let apery = sg
        .apery_set
        .iter()
        .map(usize::to_string)
        .collect::<Vec<_>>();
    let pf_strs = sg.pf_set.iter().map(usize::to_string).collect::<Vec<_>>();
    let sym = if sg.is_symmetric { "true" } else { "false" };
    let mut out = String::new();
    writeln!(out, "# ── Semigroup {idx}: <{}> ──", gens.join(", ")).unwrap();
    writeln!(out, "ng{idx} := NumericalSemigroup({});", gens.join(",")).unwrap();
    writeln!(out, "Assert(0, Multiplicity(ng{idx}) = {});", sg.m).unwrap();
    writeln!(out, "Assert(0, FrobeniusNumber(ng{idx}) = {});", sg.f).unwrap();
    writeln!(out, "Assert(0, EmbeddingDimension(ng{idx}) = {});", sg.e).unwrap();
    writeln!(
        out,
        "Assert(0, GenusOfNumericalSemigroup(ng{idx}) = {});",
        sg.g
    )
    .unwrap();
    writeln!(
        out,
        "Assert(0, 1 + FrobeniusNumber(ng{idx}) - GenusOfNumericalSemigroup(ng{idx}) = {});",
        sg.sigma
    )
    .unwrap();
    writeln!(out, "Assert(0, IsSymmetric(ng{idx}) = {sym});").unwrap();
    writeln!(
        out,
        "Assert(0, AperyList(ng{idx}, {}) = [{}]);",
        sg.m,
        apery.join(",")
    )
    .unwrap();
    writeln!(
        out,
        "Assert(0, Set(PseudoFrobeniusOfNumericalSemigroup(ng{idx})) = Set([{}]));",
        pf_strs.join(",")
    )
    .unwrap();
    writeln!(
        out,
        "Assert(0, TypeOfNumericalSemigroup(ng{idx}) = {});",
        sg.t
    )
    .unwrap();
    if sg.m >= 2 {
        gap_block_matrix(sg, idx, &mut out);
    }
    out.push('\n');
    out
}

/// Appends the matrix-algebra and canonical-ideal GAP assertions for `sg` (requires `m ≥ 2`).
///
/// Emitted blocks, all keyed by `{idx}`:
/// - `ap`, `U`, `c_red_col1` — Apéry list, U(m) matrix, first column of `C_red`.
/// - `r` — reflected-gap count with assertion against `sg.r`.
/// - `d_vec` — anti-diagonal Kunz sums; asserts `wᵢ + dᵢ = f + m + r`.
/// - `zd` — zero-diagonal vector; asserts `zd · c₁ = f + m + r = 2g + m − 1`.
/// - `ks_gens` / `ks` — canonical ideal K(S); asserts its Frobenius and genus.
fn gap_block_matrix(sg: &Semigroup, idx: usize, out: &mut String) {
    use std::fmt::Write as _;
    let m = sg.m;
    let f = sg.f;
    let n = m - 1;
    // Apéry list, U(m) matrix, and first column of C_red.
    // U(m) row i: (i−1) copies of (i−m), then (n−i+1) copies of i.
    // c_red_col1[i] = (w_i + w_1 − w_{(i+1) mod m}) / m.
    writeln!(out, "ap{idx} := AperyList(ng{idx}, {m});;").unwrap();
    writeln!(
        out,
        "U{idx} := List([1..{n}], i -> Concatenation(\
         ListWithIdenticalEntries(i-1, i-{m}), \
         ListWithIdenticalEntries({n}-i+1, i)));;",
    )
    .unwrap();
    writeln!(
        out,
        "c_red_col1_{idx} := List([1..{n}], \
         i -> (ap{idx}[i+1] + ap{idx}[2] - ap{idx}[((i+1) mod {m}) + 1]) / {m});;",
    )
    .unwrap();
    writeln!(
        out,
        "Assert(0, U{idx} * c_red_col1_{idx} = ap{idx}{{[2..{m}]}});",
    )
    .unwrap();
    // Reflected gaps: r = #{g : g and f−g are both gaps}.
    writeln!(
        out,
        "r{idx} := Size(Filtered(Gaps(ng{idx}), \
         g -> g < {f} and not BelongsToNumericalSemigroup({f} - g, ng{idx})));;"
    )
    .unwrap();
    writeln!(out, "Assert(0, r{idx} = {});", sg.r).unwrap();
    // Anti-diagonal Kunz sums: d_i = Σ_{j=0}^{m−1} c(j, (i−j) mod m).
    // GAP: `mod` binds tighter than `+`, so `(i-j) mod m+1` = `((i-j) mod m) + 1`.
    writeln!(
        out,
        "d_vec{idx} := List([1..{n}], i -> \
         Sum([0..{m}-1], j -> \
         (ap{idx}[j+1] + ap{idx}[(i-j) mod {m}+1] - ap{idx}[i+1]) / {m}));;"
    )
    .unwrap();
    writeln!(
        out,
        "Assert(0, ForAll([1..{n}], i -> ap{idx}[i+1] + d_vec{idx}[i] = {f} + {m} + r{idx}));;"
    )
    .unwrap();
    // zd(m)·c₁ = f + m + r = 2g + m − 1.
    writeln!(out, "zd{idx} := List([0..{n}-1], b -> 2*b - {m} + 3);;").unwrap();
    writeln!(
        out,
        "Assert(0, zd{idx} * c_red_col1_{idx} = {f} + {m} + r{idx});"
    )
    .unwrap();
    writeln!(
        out,
        "Assert(0, zd{idx} * c_red_col1_{idx} = 2*GenusOfNumericalSemigroup(ng{idx}) + {m} - 1);"
    )
    .unwrap();
    // Canonical ideal K(S): generated by {f − p : p ∈ PF(S), p ≠ f}.
    // For symmetric S, PF(S) = {f} and K(S) = S (no non-f pseudo-Frobenius numbers).
    // When the generators have gcd > 1 they do not form a valid numerical semigroup,
    // so we only create ks{idx} when Gcd(ks_gens) = 1.
    let ks_gens: Vec<usize> = sg
        .pf_set
        .iter()
        .filter(|&&p| p != f)
        .map(|&p| f - p)
        .collect();
    writeln!(
        out,
        "ks_gens{idx} := List(\
         Filtered(Set(PseudoFrobeniusOfNumericalSemigroup(ng{idx})), p -> p <> {f}), \
         p -> {f} - p);;"
    )
    .unwrap();
    if sg.is_symmetric {
        writeln!(out, "Assert(0, IsSymmetric(ng{idx}));").unwrap();
        writeln!(out, "Assert(0, ks_gens{idx} = []);").unwrap();
    } else if !ks_gens.is_empty() && gcd_vec(&ks_gens) == 1 {
        let ks = sg.canonical_ideal();
        // GAP uses -1 for the Frobenius number of ℕ = ⟨1⟩; our usize uses 0.
        #[allow(clippy::cast_possible_wrap)]
        let ks_f_gap: i64 = if ks.f == 0 { -1 } else { ks.f as i64 };
        writeln!(out, "ks{idx} := NumericalSemigroup(ks_gens{idx});;").unwrap();
        writeln!(out, "Assert(0, FrobeniusNumber(ks{idx}) = {ks_f_gap});").unwrap();
        writeln!(
            out,
            "Assert(0, GenusOfNumericalSemigroup(ks{idx}) = {});",
            ks.g
        )
        .unwrap();
    }
    // (If gcd(ks_gens) > 1 the generators are defined in GAP but no semigroup is constructed.)
}
