//! The [`compute`] entry point: turn a slice of positive integers into a
//! fully-populated [`Semigroup`].
//!
//! Sliding-window algorithm inspired by Wilf's "circle of lights": walk a
//! window of width `2·max(input)` along ℕ, tracking per-residue
//! first-hit values to recover the Apéry set in a single pass. Membership
//! tests against the running set are O(1) via the per-residue minima.

use super::Semigroup;
use super::gcd_vec;

/// Compute the numerical semigroup generated by `input`.
///
/// The input is first normalised: divide every entry by `gcd(input)`,
/// then sort. The algorithm runs in `O(f · e)` where `f` is the
/// Frobenius number and `e` is the embedding dimension.
///
/// # Panics
/// Panics if `input` is empty or all-zero (no valid multiplicity).
#[must_use]
#[allow(clippy::cast_possible_wrap, clippy::too_many_lines)]
pub fn compute(input: &[usize]) -> Semigroup {
    let d = gcd_vec(input);
    let mut inputnumbers: Vec<usize> = input.iter().map(|x| x / d).collect();
    inputnumbers.sort_unstable();

    let maximal_input: usize = *inputnumbers.last().unwrap();
    let width = 2 * maximal_input;
    let m: usize = *inputnumbers.first().unwrap();

    let mut aperyset: Vec<usize> = vec![0; m];
    let mut sigma = 1usize; // 0 is already an element in this set
    let mut window = vec![-1isize; width]; // here we store the results
    let mut windowindex = m; // this is the running index
    let mut runlength = 0usize; // number of consecutive hits
    let mut hit: bool = false; // true if the number windowindex is in S
    let mut max_apery: usize = m;
    let mut sum_apery: usize = 0;
    let mut minimal_generators: usize = 1;
    let mut max_atom = m;
    let mut genset: Vec<usize> = Vec::new();
    window[0] = 0;
    let mut i: usize = m; // startindex
    while runlength < m {
        let residue = i % m;
        if 0 == residue {
            // case: a multiple of m
            sigma += 1;
            runlength += 1;
            hit = true;
            window[windowindex] = i as isize;
        } else if aperyset[residue] > 0 && i > aperyset[residue] {
            // case: we already have found an element in this residue class
            sigma += 1;
            runlength += 1;
            hit = true;
            window[windowindex] = i as isize;
        } else {
            // ok, we must ckeck this number by going back to windowindex-generator for all generators
            for k in &inputnumbers[1..] {
                if windowindex >= *k && window[windowindex - k] >= 0 {
                    // case window[windowindex - k] is already an element of S
                    sigma += 1;
                    runlength += 1;
                    hit = true;
                    window[windowindex] = i as isize;
                    aperyset[residue] = i;
                    sum_apery += i;
                    if i > max_apery {
                        max_apery = i;
                    }
                    if 0 == window[windowindex - *k] {
                        minimal_generators += 1;
                        genset.push(i);
                        if max_atom < i {
                            max_atom = i;
                        }
                    }
                    break;
                }
            }
        }
        if !hit {
            runlength = 0;
        }
        hit = false;
        i += 1;
        //
        // copy the right half of the window to the left and continue
        //
        if windowindex == width - 1 {
            let (dst, src) = window.split_at_mut(maximal_input);
            dst[0..maximal_input].clone_from_slice(&src[..maximal_input]);
            windowindex = maximal_input;
        } else {
            windowindex += 1;
        }
    }
    genset.push(m);
    assert_eq!(genset.len(), minimal_generators);
    genset.sort_unstable();
    assert_eq!(aperyset.len(), m);

    let element = |n: usize| -> bool { n >= aperyset[n % m] };

    let reflected_gap = |n: usize| -> bool { !element(n) && !element(max_apery - m - n) };

    let pseudo_frobenius =
        |n: usize| -> bool { !element(n) && genset.iter().all(|a| element(*a + n)) };

    let reflected_gap_count = (1..max_apery - m).filter(|x| reflected_gap(*x)).count();

    let ra = aperyset[1..]
        .iter()
        .filter(|x| reflected_gap(**x - m))
        .count();

    let pf_set: Vec<usize> = aperyset[1..]
        .iter()
        .filter(|x| pseudo_frobenius(**x - m))
        .map(|x| *x - m)
        .collect();

    let type_count: usize = pf_set.len();

    let is_fundamental_gap =
        |n: usize| -> bool { !element(n) && (2..=max_apery / n).all(|x| element(x * n)) };

    let fg = (1..max_apery - m)
        .filter(|x| is_fundamental_gap(*x))
        .count();

    let deep = aperyset[1..].iter().all(|&w| w > 2 * m);

    // es: minimal generators g with g + 2m < max_apery, i.e. g < f − m.
    let small_minimal_generators = genset.iter().filter(|&&x| x + 2 * m < max_apery).count();

    // rl: gaps L with f − m < L < f. For any such L, f − L ∈ (0, m), which is
    // always a gap, so reflectedness is automatic. The special cases avoid
    // underflow when max_apery < 2m (only reachable for f = m − 1).
    let large_reflected_gaps: usize = match m {
        1 => 0,
        _ if max_apery < 2 * m => m - 2,
        _ => ((max_apery + 1 - 2 * m)..(max_apery - m))
            .filter(|&x| !element(x))
            .count(),
    };

    Semigroup {
        e: minimal_generators,
        f: max_apery - m,
        m,
        t: type_count,
        r: reflected_gap_count,
        rl: large_reflected_gaps,
        es: small_minimal_generators,
        ae: max_atom,
        ra,
        fg,
        sigma: sigma - m,
        g: (sum_apery - ((m - 1) * m) / 2) / m,
        max_gen: *genset.iter().max().unwrap(),
        gen_set: genset,
        apery_set: aperyset,
        apery_sum: sum_apery,
        pf_set,
        mu: max_apery % m,
        level: (max_apery - m) / m,
        is_symmetric: type_count == 1,
        is_almost_symmetric: max_apery + type_count == m + 2 * (sum_apery - ((m - 1) * m) / 2) / m,
        deep,
    }
}
