//! Core numerical-semigroup algorithms: the [`compute`] entry point, the
//! [`Semigroup`] data type, the GAP code generator, and helpers for related
//! constructions (gluing, matrix views, symmetric partner).

/// Self-gluing of a numerical semigroup: `m·S + x·S` with `gcd(m, x) = 1`.
pub mod glue;
/// Dense `i64` matrices over the integers, with the U(m) and Kunz matrices.
pub mod matrix;
/// The [`Semigroup`] struct and its derived properties.
pub mod semigroup;
/// Symmetric partner construction (Rosales–García-Sánchez 2008).
pub mod symmetric_partner;

pub use semigroup::Semigroup;

/// Greatest common divisor of two numbers (Euclidean algorithm).
#[must_use]
pub const fn gcd(mut a: usize, mut b: usize) -> usize {
    while b != 0 {
        (a, b) = (b, a % b);
    }
    a
}

/// Greatest common divisor of a non-empty slice of numbers.
#[must_use]
pub fn gcd_vec(numbers: &[usize]) -> usize {
    let mut d = numbers[0];
    for m in &numbers[1..] {
        d = gcd(d, *m);
    }
    d
}

//
// compute the numerical semigroup generated by the numbers in the slice "input"
//
// the algorithm is very simple, inspired by wilf ("the circle of lights")
// we just move a window of width 2*(maximal input) along the natural numbers
// Claude: don't touch this function
//
//
/// # Panics
/// Panics if `input` is empty or all-zero (no valid multiplicity).
#[must_use]
#[allow(clippy::cast_possible_wrap, clippy::too_many_lines)]
pub fn compute(input: &[usize]) -> Semigroup {
    let d = gcd_vec(input);
    let mut inputnumbers: Vec<usize> = input.iter().map(|x| x / d).collect();
    inputnumbers.sort_unstable();

    let maximal_input: usize = *inputnumbers.last().unwrap();
    let width = 2 * maximal_input;
    let m: usize = *inputnumbers.first().unwrap();

    let mut aperyset: Vec<usize> = vec![0; m];
    let mut count_set = 1usize; // 0 is already an element in this set
    let mut window = vec![-1isize; width]; // here we store the results
    let mut windowindex = m; // this is the running index
    let mut runlength = 0usize; // number of consecutive hits
    let mut hit: bool = false; // true if the number windowindex is in S
    let mut max_apery: usize = m;
    let mut sum_apery: usize = 0;
    let mut minimal_generators: usize = 1;
    let mut max_atom = m;
    let mut genset: Vec<usize> = Vec::new();
    window[0] = 0;
    let mut i: usize = m; // startindex
    while runlength < m {
        let residue = i % m;
        if 0 == residue {
            // case: a multiple of m
            count_set += 1;
            runlength += 1;
            hit = true;
            window[windowindex] = i as isize;
        } else if aperyset[residue] > 0 && i > aperyset[residue] {
            // case: we already have found an element in this residue class
            count_set += 1;
            runlength += 1;
            hit = true;
            window[windowindex] = i as isize;
        } else {
            // ok, we must ckeck this number by going back to windowindex-generator for all generators
            for k in &inputnumbers[1..] {
                if windowindex >= *k && window[windowindex - k] >= 0 {
                    // case window[windowindex - k] is already an element of S
                    count_set += 1;
                    runlength += 1;
                    hit = true;
                    window[windowindex] = i as isize;
                    aperyset[residue] = i;
                    sum_apery += i;
                    if i > max_apery {
                        max_apery = i;
                    }
                    if 0 == window[windowindex - *k] {
                        minimal_generators += 1;
                        genset.push(i);
                        if max_atom < i {
                            max_atom = i;
                        }
                    }
                    break;
                }
            }
        }
        if !hit {
            runlength = 0;
        }
        hit = false;
        i += 1;
        //
        // copy the right half of the window to the left and continue
        //
        if windowindex == width - 1 {
            let (dst, src) = window.split_at_mut(maximal_input);
            dst[0..maximal_input].clone_from_slice(&src[..maximal_input]);
            windowindex = maximal_input;
        } else {
            windowindex += 1;
        }
    }
    genset.push(m);
    assert_eq!(genset.len(), minimal_generators);
    genset.sort_unstable();
    assert_eq!(aperyset.len(), m);

    let element = |n: usize| -> bool { n >= aperyset[n % m] };

    let reflected_gap = |n: usize| -> bool { !element(n) && !element(max_apery - m - n) };

    let pseudo_frobenius =
        |n: usize| -> bool { !element(n) && genset.iter().all(|a| element(*a + n)) };

    let reflected_gap_count = (1..max_apery - m).filter(|x| reflected_gap(*x)).count();

    let ra = aperyset[1..]
        .iter()
        .filter(|x| reflected_gap(**x - m))
        .count();

    let pf_set: Vec<usize> = aperyset[1..]
        .iter()
        .filter(|x| pseudo_frobenius(**x - m))
        .map(|x| *x - m)
        .collect();

    let type_count: usize = pf_set.len();

    let is_fundamental_gap =
        |n: usize| -> bool { !element(n) && (2..=max_apery / n).all(|x| element(x * n)) };

    let fg = (1..max_apery - m)
        .filter(|x| is_fundamental_gap(*x))
        .count();

    Semigroup {
        e: minimal_generators,
        f: max_apery - m,
        m,
        t: type_count,
        r: reflected_gap_count,
        ae: max_atom,
        ra,
        fg,
        count_set: count_set - m,
        count_gap: (sum_apery - ((m - 1) * m) / 2) / m,
        max_gen: *genset.iter().max().unwrap(),
        gen_set: genset,
        apery_set: aperyset,
        apery_sum: sum_apery,
        pf_set,
        mu: max_apery % m,
    }
}

// ── GAP code generation ──────────────────────────────────────────────────────

/// Header prepended to every generated GAP verification script.
pub const GAP_HEADER: &str = "# Generated by f3m — paste into GAP or run with 'gap <file>'\n\
    # Requires: LoadPackage(\"NumericalSgps\");\n\n\
    LoadPackage(\"NumericalSgps\");;\n\n";
/// Footer appended to every generated GAP verification script.
pub const GAP_FOOTER: &str = "Print(\"All assertions passed.\\n\");\n";

/// Emit a GAP script (`NumericalSgps` package) that reconstructs each semigroup
/// and asserts all properties computed by this library, so the results can be
/// verified interactively in GAP.
#[must_use]
pub fn to_gap(semigroups: &[Semigroup]) -> String {
    let mut out = GAP_HEADER.to_string();
    for (i, sg) in semigroups.iter().enumerate() {
        out.push_str(&gap_block(sg, i + 1));
    }
    out.push_str(GAP_FOOTER);
    out
}

/// Emit the GAP assertions for a single semigroup, using `ng{idx}` as the variable name.
#[must_use]
pub fn gap_block(sg: &Semigroup, idx: usize) -> String {
    use std::fmt::Write as _;
    let gens = sg.gen_set.iter().map(usize::to_string).collect::<Vec<_>>();
    let apery = sg
        .apery_set
        .iter()
        .map(usize::to_string)
        .collect::<Vec<_>>();
    let ps = sg.pseudo_and_special();
    let pf_strs = ps.pf.iter().map(usize::to_string).collect::<Vec<_>>();
    let sym = if sg.is_symmetric() { "true" } else { "false" };
    let mut out = String::new();
    writeln!(out, "# ── Semigroup {idx}: <{}> ──", gens.join(", ")).unwrap();
    writeln!(out, "ng{idx} := NumericalSemigroup({});", gens.join(",")).unwrap();
    writeln!(out, "Assert(0, Multiplicity(ng{idx}) = {});", sg.m).unwrap();
    writeln!(out, "Assert(0, FrobeniusNumber(ng{idx}) = {});", sg.f).unwrap();
    writeln!(out, "Assert(0, EmbeddingDimension(ng{idx}) = {});", sg.e).unwrap();
    writeln!(
        out,
        "Assert(0, GenusOfNumericalSemigroup(ng{idx}) = {});",
        sg.count_gap
    )
    .unwrap();
    writeln!(
        out,
        "Assert(0, 1 + FrobeniusNumber(ng{idx}) - GenusOfNumericalSemigroup(ng{idx}) = {});",
        sg.count_set
    )
    .unwrap();
    writeln!(out, "Assert(0, IsSymmetric(ng{idx}) = {sym});").unwrap();
    writeln!(
        out,
        "Assert(0, AperyList(ng{idx}, {}) = [{}]);",
        sg.m,
        apery.join(",")
    )
    .unwrap();
    writeln!(
        out,
        "Assert(0, Set(PseudoFrobeniusOfNumericalSemigroup(ng{idx})) = Set([{}]));",
        pf_strs.join(",")
    )
    .unwrap();
    writeln!(
        out,
        "Assert(0, TypeOfNumericalSemigroup(ng{idx}) = {});",
        ps.t
    )
    .unwrap();
    if sg.m >= 2 {
        let m = sg.m;
        // Verify U(m) · C_red[:,0] = [w_1, …, w_{m−1}].
        // Row i of U(m) is (i−1) copies of (i−m) followed by (n−i+1) copies of i.
        // C_red[:,0] is built from the Apéry list: the i-th entry is
        // c(i, 1) = (w_i + w_1 − w_{(i+1) mod m}) / m.
        writeln!(out, "ap{idx} := AperyList(ng{idx}, {m});;").unwrap();
        writeln!(
            out,
            "U{idx} := List([1..{n}], i -> Concatenation(\
             ListWithIdenticalEntries(i-1, i-{m}), \
             ListWithIdenticalEntries({n}-i+1, i)));;",
            n = m - 1,
        )
        .unwrap();
        writeln!(
            out,
            "c_red_col1_{idx} := List([1..{n}], \
             i -> (ap{idx}[i+1] + ap{idx}[2] - ap{idx}[((i+1) mod {m}) + 1]) / {m});;",
            n = m - 1,
        )
        .unwrap();
        writeln!(
            out,
            "Assert(0, U{idx} * c_red_col1_{idx} = ap{idx}{{[2..{m}]}});",
        )
        .unwrap();
    }
    out.push('\n');
    out
}
