#![warn(clippy::pedantic)]

pub mod semigroup;
pub use semigroup::Semigroup;

/// Greatest common divisor of two numbers (Euclidean algorithm).
#[must_use]
pub fn gcd(mut a: usize, mut b: usize) -> usize {
    while b != 0 {
        (a, b) = (b, a % b);
    }
    a
}

/// Greatest common divisor of a non-empty slice of numbers.
#[must_use]
pub fn gcd_vec(numbers: &[usize]) -> usize {
    let mut d = numbers[0];
    for m in &numbers[1..] {
        d = gcd(d, *m);
    }
    d
}

//
// compute the numerical semigroup generated by the numbers in the slice "input"
//
// the algorithm is very simple, inspired by wilf ("the circle of lights")
// we just move a window of width 2*(maximal input) along the natural numbers
// Claude: don't touch this function
//
//
/// # Panics
/// Panics if `input` is empty or all-zero (no valid multiplicity).
#[must_use]
#[allow(clippy::cast_possible_wrap)] // window stores usize values as isize sentinels
pub fn compute(input: &[usize]) -> Semigroup {
    let d = gcd_vec(input);
    let mut inputnumbers: Vec<usize> = input.iter().map(|x| x / d).collect();
    inputnumbers.sort_unstable();

    let maximal_input: usize = *inputnumbers.last().unwrap();
    let width = 2 * maximal_input;
    let m: usize = *inputnumbers.first().unwrap();

    let mut aperyset: Vec<usize> = vec![0; m];
    let mut count_set = 1usize; // 0 is already an element in this set
    let mut window = vec![-1isize; width]; // here we store the results
    let mut windowindex = m; // this is the running index
    let mut runlength = 0usize; // number of consecutive hits
    let mut hit: bool = false; // true if the number windowindex is in S
    let mut max_apery: usize = m;
    let mut sum_apery: usize = 0;
    let mut minimal_generators: usize = 1;
    let mut max_atom = m;
    let mut genset: Vec<usize> = Vec::new();
    window[0] = 0;
    let mut i: usize = m; // startindex
    while runlength < m {
        let residue = i % m;
        if 0 == residue {
            // case: a multiple of m
            count_set += 1;
            runlength += 1;
            hit = true;
            window[windowindex] = i as isize;
        } else if aperyset[residue] > 0 && i > aperyset[residue] {
            // case: we already have found an element in this residue class
            count_set += 1;
            runlength += 1;
            hit = true;
            window[windowindex] = i as isize;
        } else {
            // ok, we must ckeck this number by going back to windowindex-generator for all generators
            for k in &inputnumbers[1..] {
                if windowindex >= *k && window[windowindex - k] >= 0 {
                    // case window[windowindex - k] is already an element of S
                    count_set += 1;
                    runlength += 1;
                    hit = true;
                    window[windowindex] = i as isize;
                    aperyset[residue] = i;
                    sum_apery += i;
                    if i > max_apery {
                        max_apery = i;
                    }
                    if 0 == window[windowindex - *k] {
                        minimal_generators += 1;
                        genset.push(i);
                        if max_atom < i {
                            max_atom = i;
                        }
                    }
                    break;
                }
            }
        }
        if !hit {
            runlength = 0;
        }
        hit = false;
        i += 1;
        //
        // copy the right half of the window to the left and continue
        //
        if windowindex == width - 1 {
            let (dst, src) = window.split_at_mut(maximal_input);
            dst[0..maximal_input].clone_from_slice(&src[..maximal_input]);
            windowindex = maximal_input;
        } else {
            windowindex += 1;
        }
    }
    genset.push(m);
    assert_eq!(genset.len(), minimal_generators);
    genset.sort_unstable();
    assert_eq!(aperyset.len(), m);

    Semigroup {
        e: minimal_generators,
        f: max_apery - m,
        m,
        count_set: count_set - m,
        count_gap: (sum_apery - ((m - 1) * m) / 2) / m,
        max_gen: *genset.iter().max().unwrap(),
        gen_set: genset,
        apery_set: aperyset,
    }
}

// ── GAP code generation ──────────────────────────────────────────────────────

pub const GAP_HEADER: &str = "# Generated by f3m — paste into GAP or run with 'gap <file>'\n\
    # Requires: LoadPackage(\"NumericalSgps\");\n\n\
    LoadPackage(\"NumericalSgps\");;\n\n";
pub const GAP_FOOTER: &str = "Print(\"All assertions passed.\\n\");\n";

/// Emit a GAP script (`NumericalSgps` package) that reconstructs each semigroup
/// and asserts all properties computed by this library, so the results can be
/// verified interactively in GAP.
#[must_use]
pub fn to_gap(semigroups: &[Semigroup]) -> String {
    let mut out = GAP_HEADER.to_string();
    for (i, sg) in semigroups.iter().enumerate() {
        out.push_str(&gap_block(sg, i + 1));
    }
    out.push_str(GAP_FOOTER);
    out
}

/// Emit the GAP assertions for a single semigroup, using `ng{idx}` as the variable name.
#[must_use]
pub fn gap_block(sg: &Semigroup, idx: usize) -> String {
    use std::fmt::Write as _;
    let gens  = sg.gen_set  .iter().map(usize::to_string).collect::<Vec<_>>();
    let apery = sg.apery_set.iter().map(usize::to_string).collect::<Vec<_>>();
    let ((pf, t), _) = sg.pseudo_and_special();
    let pf_strs = pf.iter().map(usize::to_string).collect::<Vec<_>>();
    let sym = if sg.is_symmetric() { "true" } else { "false" };
    let mut out = String::new();
    writeln!(out, "# ── Semigroup {idx}: <{}> ──", gens.join(", ")).unwrap();
    writeln!(out, "ng{idx} := NumericalSemigroup({});", gens.join(",")).unwrap();
    writeln!(out, "Assert(0, Multiplicity(ng{idx}) = {});", sg.m).unwrap();
    writeln!(out, "Assert(0, FrobeniusNumber(ng{idx}) = {});", sg.f).unwrap();
    writeln!(out, "Assert(0, EmbeddingDimension(ng{idx}) = {});", sg.e).unwrap();
    writeln!(out, "Assert(0, GenusOfNumericalSemigroup(ng{idx}) = {});", sg.count_gap).unwrap();
    writeln!(out, "Assert(0, 1 + FrobeniusNumber(ng{idx}) - GenusOfNumericalSemigroup(ng{idx}) = {});", sg.count_set).unwrap();
    writeln!(out, "Assert(0, IsSymmetric(ng{idx}) = {sym});").unwrap();
    writeln!(out, "Assert(0, AperyList(ng{idx}, {}) = [{}]);", sg.m, apery.join(",")).unwrap();
    writeln!(out, "Assert(0, Set(PseudoFrobeniusOfNumericalSemigroup(ng{idx})) = Set([{}]));", pf_strs.join(",")).unwrap();
    writeln!(out, "Assert(0, TypeOfNumericalSemigroup(ng{idx}) = {t});").unwrap();
    out.push('\n');
    out
}
