//! Integration tests: every property asserted by gap/test.g and gap/newtests.g.
//! Cases mirror the GAP-verified properties: e, f, m, g, c, sym, apery, pf, t.

#![allow(clippy::too_many_lines, clippy::cognitive_complexity)]

use semigroup_math::math::{
    binom, compute,
    creators::{arith_generators, rolf_primes, tmf_generators},
    gcd,
    matrix::{c_red, d_matrix, u_matrix, zd_vector},
    random_creators::{
        random_generators, random_matching_generators, random_primes_subset,
        random_with_multiplier_generators,
    },
};

#[test]
fn test_ord_containment() {
    // <6,9,20> ⊂ <6,9,20,43> (adding the Frobenius number as a generator)
    let s1 = compute(&[6, 9, 20]);
    let s2 = compute(&[6, 9, 20, 43]);
    assert!(s1 < s2);
    assert!(s2 > s1);

    // Equal semigroups
    let s3 = compute(&[6, 9, 20]);
    assert_eq!(s1.partial_cmp(&s3), Some(std::cmp::Ordering::Equal));

    // <3,7> and <2,7> are incomparable: 2 ∉ <3,7> and 3 ∉ <2,7>
    let a = compute(&[3, 7]);
    let b = compute(&[2, 7]);
    assert_eq!(a.partial_cmp(&b), None);
}

#[test]
fn test_gcd() {
    assert_eq!(gcd(12, 8), 4);
    assert_eq!(gcd(7, 3), 1);
    assert_eq!(gcd(0, 5), 5);
    assert_eq!(gcd(9, 0), 9);
}

#[test]
fn test_binom_basics() {
    // Edge cases: b > a, b = 0, b = a.
    assert_eq!(binom(3, 5), Some(0));
    assert_eq!(binom(0, 0), Some(1));
    assert_eq!(binom(7, 0), Some(1));
    assert_eq!(binom(7, 7), Some(1));

    // Known values.
    assert_eq!(binom(5, 2), Some(10));
    assert_eq!(binom(10, 3), Some(120));
    assert_eq!(binom(20, 10), Some(184_756));

    // Symmetry: C(a, b) = C(a, a − b).
    for a in 0..=20 {
        for b in 0..=a {
            assert_eq!(binom(a, b), binom(a, a - b), "symmetry for ({a}, {b})");
        }
    }

    // Pascal's identity: C(n, k) = C(n−1, k−1) + C(n−1, k) for 1 ≤ k ≤ n−1.
    for n in 2..=20 {
        for k in 1..n {
            let lhs = binom(n, k).expect("no overflow at n ≤ 20");
            let a = binom(n - 1, k - 1).expect("no overflow");
            let b = binom(n - 1, k).expect("no overflow");
            assert_eq!(lhs, a + b, "Pascal at ({n}, {k})");
        }
    }
}

#[test]
fn test_binom_overflow() {
    // On 64-bit hosts: C(62, 31) ≈ 4.65·10^17 still fits in u64 = usize;
    // C(70, 35) ≈ 1.12·10^20 overflows u64. We pick a value safely above
    // u64::MAX so the test is meaningful on both 32- and 64-bit usize.
    assert!(
        binom(200, 100).is_none(),
        "C(200,100) ≈ 9·10^58 must overflow",
    );
    // And a value that fits even on 32-bit usize (C(20,10) = 184_756).
    assert_eq!(binom(20, 10), Some(184_756));
}

/// Brute-force enumeration of every level-1 numerical semigroup with given
/// multiplicity `m` (i.e. m < f < 2m). For each μ ∈ {1, …, m−1} and each
/// subset of {1, …, μ−1} (telling us which `m+r` are in S), build the
/// candidate Apéry set, run `compute`, and yield the result. Every candidate
/// gives a valid numerical semigroup (the Kunz constraints are automatic at
/// level 1, since w_r + w_s ≥ 2m + r + s dominates every right-hand side).
fn level_1_semigroups_for_m(m: usize) -> Vec<(usize, semigroup_math::math::Semigroup)> {
    let mut out = Vec::new();
    for mu in 1..m {
        // Free choices: r ∈ {1, …, μ−1}. For r > μ, w_r = m+r is forced.
        let free = mu - 1;
        for mask in 0..(1u32 << free) {
            let mut gens = vec![m];
            for r in 1..m {
                let w = if r == mu {
                    2 * m + mu
                } else if r > mu || (mask >> (r - 1)) & 1 == 1 {
                    // r > mu: forced m+r; r < mu and bit set: m+r ∈ S.
                    m + r
                } else {
                    2 * m + r
                };
                gens.push(w);
            }
            out.push((mu, compute(&gens)));
        }
    }
    out
}

#[test]
fn test_level_0_uniqueness() {
    // For every multiplicity m ≥ 2 there is exactly one level-0 numerical
    // semigroup: the ordinary semigroup S = {0} ∪ [m, ∞), generated by
    // {m, m+1, …, 2m−1}. Its invariants are f = g = μ = m − 1.
    for m in 2..=12 {
        let gens: Vec<usize> = (m..2 * m).collect();
        let s = compute(&gens);
        assert_eq!(s.m, m, "m={m}");
        assert_eq!(s.level, 0, "level should be 0 for m={m}");
        assert_eq!(s.f, m - 1, "f should be m−1 for m={m}");
        assert_eq!(s.mu, m - 1, "μ should be m−1 for m={m}");
        assert_eq!(s.count_gap, m - 1, "g should be m−1 for m={m}");
        assert_eq!(s.gen_set, gens, "min-gens should be {{m,…,2m−1}} for m={m}");
    }
}

/// Bit-encoded enumeration helper: subset of `{1, …, μ−1}` from a mask where
/// bit `r−1` set means `r` is included.
fn mask_to_subset(mask: u32, mu: usize) -> Vec<usize> {
    (1..mu).filter(|&r| (mask >> (r - 1)) & 1 == 1).collect()
}

/// `M` is sum-avoiding for parameter `μ`: no `a, b ∈ M` (allowing `a = b`)
/// satisfy `a + b = μ`. Equivalently, `M ∩ (μ − M) = ∅`, with the additional
/// requirement that `μ/2 ∉ M` when `μ` is even.
fn is_sum_avoiding(m_set: &[usize], mu: usize) -> bool {
    for &a in m_set {
        for &b in m_set {
            if a + b == mu {
                return false;
            }
        }
    }
    true
}

/// Builds the candidate level-2 "missing" semigroup whose Apéry set is
/// `(0, …, w_r = m+r if r ∈ M, 2m+r otherwise; w_μ = 3m+μ; m+r forced for r > μ)`.
/// Returns the result of `compute` on those Apéry elements as generators
/// (plus `m`). The resulting semigroup is level 2 with the intended `(m, μ)`
/// **iff** `M` is sum-avoiding for `μ`; otherwise `2m+μ` becomes reachable
/// and the result collapses back to level 1.
fn build_level_2_missing(m: usize, mu: usize, m_set: &[usize]) -> semigroup_math::math::Semigroup {
    let mut gens = vec![m];
    for r in 1..m {
        let w = if r == mu {
            3 * m + mu
        } else if r > mu || m_set.contains(&r) {
            m + r
        } else {
            2 * m + r
        };
        gens.push(w);
    }
    compute(&gens)
}

/// Same as [`build_level_2_missing`] but with `w_μ = 2m+μ`, producing the
/// level-1 semigroup at the same `M`. Always valid (level 1 has no Kunz
/// filtering).
fn build_level_1(m: usize, mu: usize, m_set: &[usize]) -> semigroup_math::math::Semigroup {
    let mut gens = vec![m];
    for r in 1..m {
        let w = if r == mu {
            2 * m + mu
        } else if r > mu || m_set.contains(&r) {
            m + r
        } else {
            2 * m + r
        };
        gens.push(w);
    }
    compute(&gens)
}

#[test]
fn test_level_2_missing_stratification() {
    // For every (m, μ) with m ≤ 8, verify:
    //   • Per-stratum count by k = |M|:
    //       level-1 stratum has C(μ−1, k) subsets,
    //       level-2 missing stratum has C(⌊(μ−1)/2⌋, k) · 2^k subsets,
    //   • The lift M ↦ M takes a level-1 with sum-avoiding M to a level-2
    //     "missing" with the same M, raising genus by exactly 1.
    //   • Non-sum-avoiding M's "lift" to a level-1 (collapse), not a
    //     level-2.
    for m in 2..=8 {
        for mu in 1..m {
            let mut l1_by_k: Vec<usize> = vec![0; mu];
            let mut l2_missing_by_k: Vec<usize> = vec![0; mu];
            for mask in 0..(1u32 << (mu - 1)) {
                let m_set = mask_to_subset(mask, mu);
                let k = m_set.len();
                l1_by_k[k] += 1;

                let s1 = build_level_1(m, mu, &m_set);
                assert_eq!(s1.m, m, "(m={m}, μ={mu}, M={m_set:?})");
                assert_eq!(s1.mu, mu, "(m={m}, μ={mu}, M={m_set:?})");
                assert_eq!(s1.level, 1, "(m={m}, μ={mu}, M={m_set:?})");
                assert_eq!(s1.count_gap, m + mu - 1 - k, "level-1 genus formula");

                let s2 = build_level_2_missing(m, mu, &m_set);
                if is_sum_avoiding(&m_set, mu) {
                    l2_missing_by_k[k] += 1;
                    assert_eq!(s2.m, m, "(m={m}, μ={mu}, M={m_set:?})");
                    assert_eq!(s2.mu, mu, "(m={m}, μ={mu}, M={m_set:?})");
                    assert_eq!(s2.level, 2, "(m={m}, μ={mu}, M={m_set:?})");
                    assert_eq!(s2.count_gap, m + mu - k, "missing genus formula");
                    assert_eq!(
                        s2.count_gap,
                        s1.count_gap + 1,
                        "genus shift l=1 → l=2 missing must be +1",
                    );
                } else {
                    // Bad pair in M: 2m+μ reduces, w_μ collapses to 2m+μ,
                    // and the result lands back in level 1 (not level 2).
                    assert_ne!(
                        s2.level, 2,
                        "non-sum-avoiding M must not lift to level 2: m={m}, μ={mu}, M={m_set:?}",
                    );
                }
            }

            // Closed forms.
            let half = (mu - 1) / 2;
            for k in 0..mu {
                assert_eq!(
                    l1_by_k[k],
                    binom(mu - 1, k).expect("small"),
                    "level-1 stratum (m={m}, μ={mu}, k={k})",
                );
                let predicted_missing = if k <= half {
                    binom(half, k).expect("small") * (1usize << k)
                } else {
                    0
                };
                assert_eq!(
                    l2_missing_by_k[k], predicted_missing,
                    "level-2 missing stratum (m={m}, μ={mu}, k={k})",
                );
            }

            // Sum totals: level-1 = 2^(μ−1), level-2 missing = 3^⌊(μ−1)/2⌋.
            assert_eq!(l1_by_k.iter().sum::<usize>(), 1usize << (mu - 1));
            assert_eq!(
                l2_missing_by_k.iter().sum::<usize>(),
                3usize.pow(half as u32)
            );
        }
    }
}

#[test]
fn test_level_1_count_formula() {
    // N(g, l=1, m, μ) = C(μ−1, m + μ − 1 − g) for g ∈ {m, …, m+μ−1};
    // zero outside that range. Verified by brute force.
    for m in 2..=8 {
        let mut actual: std::collections::HashMap<(usize, usize), usize> =
            std::collections::HashMap::new();
        for (mu, s) in level_1_semigroups_for_m(m) {
            assert_eq!(s.m, m, "m mismatch (m={m}, μ={mu})");
            assert_eq!(s.level, 1, "level mismatch (m={m}, μ={mu})");
            assert_eq!(s.mu, mu, "μ mismatch (m={m})");
            *actual.entry((s.count_gap, mu)).or_insert(0) += 1;
        }
        // Compare against the closed form for every (g, μ) we observed.
        for ((g, mu), &n) in &actual {
            let k = m + mu - 1 - g;
            let predicted = if k < *mu {
                binom(mu - 1, k).expect("small inputs cannot overflow")
            } else {
                0
            };
            assert_eq!(
                n, predicted,
                "N(g={g}, l=1, m={m}, μ={mu}): predicted {predicted}, actual {n}",
            );
        }
        // And verify the sum: N(g, l=1, m) = Σ_μ N(g, l=1, m, μ).
        let mut by_g: std::collections::HashMap<usize, usize> = std::collections::HashMap::new();
        for ((g, _), n) in &actual {
            *by_g.entry(*g).or_insert(0) += n;
        }
        for (&g, &actual_total) in &by_g {
            let predicted_total: usize = (1..m)
                .map(|mu| {
                    if g >= m && g < m + mu {
                        binom(mu - 1, m + mu - 1 - g).expect("small")
                    } else {
                        0
                    }
                })
                .sum();
            assert_eq!(
                actual_total, predicted_total,
                "N(g={g}, l=1, m={m}): predicted {predicted_total}, actual {actual_total}",
            );
        }
    }
}

/// Compute the semigroup from `gens` and assert every GAP-verified property.
///
/// Parameters match the GAP assertions in gap/test.g:
/// `e` = embedding dimension, `f` = Frobenius number, `m` = multiplicity,
/// `g` = genus, `c` = count_set (= 1+f−g), `sym` = IsSymmetric,
/// `apery` = AperyList w.r.t. m (indexed 0..m), `pf` = PseudoFrobenius set,
/// `t` = type.
#[allow(clippy::too_many_arguments)]
fn check(
    gens: &[usize],
    e: usize,
    f: usize,
    m: usize,
    g: usize,
    c: usize,
    sym: bool,
    apery: &[usize],
    pf: &[usize],
    t: usize,
) {
    let s = compute(gens);
    assert_eq!(s.f + s.m, s.apery_set[s.mu], "max apery");
    for i in 0..s.m {
        assert_eq!(s.diag(i) + s.apery_set[i], s.f + s.m + s.r, "diag {i}");
    }
    assert_eq!(s.diag(s.mu), s.r);

    assert_eq!(s.e, e, "e     for {gens:?}");
    assert_eq!(s.f, f, "f     for {gens:?}");
    assert_eq!(s.m, m, "m     for {gens:?}");
    assert_eq!(s.count_gap, g, "genus for {gens:?}");
    assert_eq!(s.count_set, c, "c     for {gens:?}");
    assert_eq!(s.is_symmetric, sym, "sym   for {gens:?}");
    assert_eq!(s.apery_set.as_slice(), apery, "apery for {gens:?}");
    let mut actual_pf = s.pf_set.clone();
    actual_pf.sort_unstable();
    let mut expected_pf = pf.to_vec();
    expected_pf.sort_unstable();
    assert_eq!(actual_pf, expected_pf, "pf    for {gens:?}");
    assert_eq!(s.t, t, "type  for {gens:?}");
    assert_eq!(f + m, *apery.iter().max().unwrap(), "f ist max apery -m");
    assert_eq!(s.count_set + s.r, s.count_gap, "g ist sigma + r");
    assert_eq!(s.f + s.r + 2, 2 * s.count_gap + 1, "f+r+2=2g+1");
    assert_eq!(
        s.ae,
        *s.gen_set.iter().max().unwrap(),
        "maximum for {gens:?}"
    );
    assert_eq!(t, s.t, "t for {gens:?}");
    assert_eq!(t, s.pf_set.len(), "type is length pf_set");
    let mut semi_pf = s.pf_set.clone();
    semi_pf.sort_unstable();
    assert_eq!(
        pf.to_vec(),
        semi_pf,
        "pseudo-frobenius for {gens:?} and {m}"
    );
    let aps: usize = s.apery_set.iter().sum();
    assert_eq!(aps, s.apery_sum);
    // todo 82
    assert!(s.rl <= s.t);
    assert!(s.t <= s.r + 1);
    assert!(s.es <= s.e);
    // up-down
    // if s.es < s.e {
    //     let up = s.ascent();
    //     let down = up.descent();
    //     assert_eq!(s, down);
    // }


    // Selmer identity: one·U(m)·c₁ = m·g + m·(m−1)/2
    let dim = m - 1;
    let u_mat = u_matrix(m);
    let cr = c_red(&s);
    let one_u: Vec<i64> = (0..dim)
        .map(|j| (0..dim).map(|a| u_mat[(a, j)]).sum())
        .collect();
    #[allow(clippy::cast_possible_wrap)]
    let c1: Vec<i64> = (0..dim).map(|i| cr[(i, 0)] as i64).collect();
    let scalar: i64 = one_u.iter().zip(c1.iter()).map(|(&u, &c)| u * c).sum();
    #[allow(clippy::cast_possible_wrap)]
    let apery_sum_selmer = (m * g + m * (m - 1) / 2) as i64;
    assert_eq!(scalar, apery_sum_selmer, "Selmer identity for {gens:?}");

    // zd(m)·c₁ = f + m + r = 2g + m − 1
    let zd = zd_vector(m);
    #[allow(clippy::cast_possible_wrap)]
    let zd_dot: i64 = (0..dim).map(|b| zd[(0, b)] * c1[b]).sum();
    #[allow(clippy::cast_possible_wrap)]
    let f_plus_m_plus_r = (f + m + s.r) as i64;
    #[allow(clippy::cast_possible_wrap)]
    let two_g_plus_m_minus_1 = (2 * g + m - 1) as i64;
    assert_eq!(zd_dot, f_plus_m_plus_r, "zd·c₁ = f+m+r for {gens:?}");
    assert_eq!(zd_dot, two_g_plus_m_minus_1, "zd·c₁ = 2g+m−1 for {gens:?}");

    // wᵢ + dᵢ = f + m + r for all i ∈ {1, …, m−1}
    let d_mat = d_matrix(m);
    for i in 1..=dim {
        #[allow(clippy::cast_possible_wrap)]
        let di: i64 = (0..dim).map(|b| d_mat[(i - 1, b)] * c1[b]).sum();
        #[allow(clippy::cast_possible_wrap)]
        let wi = s.apery_set[i] as i64;
        assert_eq!(
            wi + di,
            f_plus_m_plus_r,
            "w_{i} + d_{i} = f+m+r for {gens:?}"
        );
    }

    // level: level·m < f < (level+1)·m. f mod m = μ ≥ 1 (m ∈ S, f ∉ S),
    // so f never equals k·m and the strict inequality always holds.
    assert!(
        s.level * m < f && f < (s.level + 1) * m,
        "level invariant for {gens:?}: level={} m={} f={}",
        s.level,
        m,
        f,
    );

    // deep ⇔ every Kunz quotient q_i = (w_i − i)/m ≥ 2 (i ∈ 1..m).
    let all_q_ge_2 = (1..m).all(|i| (s.apery_set[i] - i) / m >= 2);
    assert_eq!(s.deep, all_q_ge_2, "deep ↔ q_i ≥ 2 for {gens:?}",);

    // Symmetric ⇒ r = 0 and genus = sporadics. (Every gap x has f − x ∈ S,
    // so no gap x has f − x as a gap.)
    if s.is_symmetric {
        assert_eq!(s.r, 0, "symmetric ⇒ r=0 for {gens:?}");
        assert_eq!(
            s.count_gap, s.count_set,
            "symmetric ⇒ g = #sporadics for {gens:?}",
        );
    }

    // For t > 1, let L = max(PF(S) \ {f}). Then:
    //   • if f is odd, 2L ∈ S;
    //   • if f is even, 2L ∈ S or 2L = f (the boundary case where L = f/2).
    if s.t > 1 {
        let l = s
            .pf_set
            .iter()
            .copied()
            .filter(|&p| p != s.f)
            .max()
            .expect("t > 1 guarantees a pseudo-Frobenius element distinct from f");
        let two_l = 2 * l;
        if s.f.is_multiple_of(2) {
            assert!(
                s.element(two_l) || two_l == s.f,
                "2L ∈ S ∪ {{f}} where L = max(PF\\{{f}}) for {gens:?}: L={l}, 2L={two_l}, f={}",
                s.f,
            );
        } else {
            assert!(
                s.element(two_l),
                "2L ∈ S where L = max(PF\\{{f}}) for {gens:?} (f odd): L={l}, 2L={two_l}",
            );
        }
    }

    // Almost-symmetric ⇒ ra = r, PF \ {f} = reflected gaps, and f + t = 2g.
    // The symmetric case is included (t = 1, both sides empty).
    if s.is_almost_symmetric {
        assert_eq!(s.ra, s.r, "almost-symmetric ⇒ ra=r for {gens:?}");
        assert_eq!(
            s.f + s.t,
            2 * s.count_gap,
            "almost-symmetric ⇒ f+t=2g for {gens:?}",
        );
        let mut pf_minus_f: Vec<usize> = s.pf_set.iter().copied().filter(|&p| p != s.f).collect();
        pf_minus_f.sort_unstable();
        assert_eq!(
            pf_minus_f,
            s.blob(),
            "almost-symmetric ⇒ PF\\{{f}} = reflected gaps for {gens:?}",
        );
    }
}

// ── Examples from gap/test.g (first block, ng1–ng10) ─────────────────────

#[test]
fn test_6_9_20() {
    check(
        &[6, 9, 20],
        3,
        43,
        6,
        22,
        22,
        true,
        &[0, 49, 20, 9, 40, 29],
        &[43],
        1,
    );
}

#[test]
fn test_12_14_19_77() {
    check(
        &[12, 14, 19, 77],
        4,
        65,
        12,
        38,
        28,
        false,
        &[0, 61, 14, 75, 28, 77, 42, 19, 56, 33, 70, 47],
        &[58, 63, 65],
        3,
    );
}

#[test]
fn test_20_44_54_73_77_89_90() {
    check(
        &[20, 44, 54, 73, 77, 89, 90],
        7,
        159,
        20,
        103,
        57,
        false,
        &[
            0, 121, 142, 143, 44, 165, 146, 127, 88, 89, 90, 131, 132, 73, 54, 175, 176, 77, 98,
            179,
        ],
        &[107, 122, 123, 126, 145, 155, 156, 159],
        8,
    );
}

#[test]
fn test_13_17_27() {
    check(
        &[13, 17, 27],
        3,
        89,
        13,
        48,
        42,
        false,
        &[0, 27, 54, 68, 17, 44, 71, 85, 34, 61, 88, 102, 51],
        &[75, 89],
        2,
    );
}

#[test]
fn test_20_28_30_46_47() {
    check(
        &[20, 28, 30, 46, 47],
        5,
        129,
        20,
        71,
        59,
        false,
        &[
            0, 121, 102, 103, 84, 105, 46, 47, 28, 149, 30, 131, 92, 93, 74, 75, 56, 77, 58, 139,
        ],
        &[85, 111, 119, 129],
        4,
    );
}

#[test]
fn test_18_40_49_51_78_93() {
    check(
        &[18, 40, 49, 51, 78, 93],
        6,
        164,
        18,
        93,
        72,
        false,
        &[
            0, 91, 182, 93, 40, 131, 78, 133, 80, 153, 100, 173, 102, 49, 140, 51, 142, 89,
        ],
        &[60, 122, 135, 155, 164],
        5,
    );
}

#[test]
fn test_46_47_54_62_66_69_70_85() {
    check(
        &[46, 47, 54, 62, 66, 69, 70, 85],
        8,
        219,
        46,
        128,
        92,
        false,
        &[
            0, 47, 94, 141, 188, 189, 190, 237, 54, 101, 148, 195, 242, 151, 198, 245, 62, 109,
            156, 203, 66, 113, 160, 69, 70, 117, 164, 211, 120, 167, 214, 123, 124, 171, 218, 265,
            128, 175, 222, 85, 132, 179, 226, 135, 136, 183,
        ],
        &[143, 168, 176, 180, 191, 196, 199, 219],
        8,
    );
}

#[test]
fn test_11_15_17_38() {
    check(
        &[11, 15, 17, 38],
        4,
        57,
        11,
        30,
        28,
        false,
        &[0, 34, 68, 47, 15, 38, 17, 51, 30, 53, 32],
        &[36, 57],
        2,
    );
}

#[test]
fn test_19_24_27_32() {
    check(
        &[19, 24, 27, 32],
        4,
        125,
        19,
        67,
        59,
        false,
        &[
            0, 96, 59, 136, 80, 24, 120, 64, 27, 104, 48, 144, 88, 32, 128, 72, 54, 112, 56,
        ],
        &[35, 40, 109, 117, 125],
        5,
    );
}

#[test]
fn test_16_26_36_75_81_82() {
    check(
        &[16, 26, 36, 75, 81, 82],
        6,
        167,
        16,
        86,
        82,
        false,
        &[
            0, 81, 82, 147, 36, 101, 118, 183, 72, 137, 26, 75, 108, 157, 62, 111,
        ],
        &[65, 102, 121, 167],
        4,
    );
}

// ── Examples from gap/test.g (second block) ───────────────────────────────

#[test]
fn test_12_30_32_38_40_41_symmetric() {
    check(
        &[12, 30, 32, 38, 40, 41],
        6,
        99,
        12,
        50,
        50,
        true,
        &[0, 73, 38, 111, 40, 41, 30, 79, 32, 81, 70, 71],
        &[99],
        1,
    );
}

#[test]
fn test_12_30_32_38_40_41_99() {
    check(
        &[12, 30, 32, 38, 40, 41, 99],
        7,
        87,
        12,
        49,
        39,
        false,
        &[0, 73, 38, 99, 40, 41, 30, 79, 32, 81, 70, 71],
        &[58, 59, 61, 67, 69, 87],
        6,
    );
}

#[test]
fn test_12_42_44_50_52_53_82_83_85_91_93() {
    check(
        &[12, 42, 44, 50, 52, 53, 82, 83, 85, 91, 93],
        11,
        123,
        12,
        62,
        62,
        true,
        &[0, 85, 50, 135, 52, 53, 42, 91, 44, 93, 82, 83],
        &[123],
        1,
    );
}

#[test]
fn test_12_102_104_110_112_113_142_143_145_151_153() {
    check(
        &[12, 102, 104, 110, 112, 113, 142, 143, 145, 151, 153],
        11,
        243,
        12,
        122,
        122,
        true,
        &[0, 145, 110, 255, 112, 113, 102, 151, 104, 153, 142, 143],
        &[243],
        1,
    );
}

#[test]
fn test_12_102_104_110_112_113_142_143_145_151_153_243() {
    check(
        &[12, 102, 104, 110, 112, 113, 142, 143, 145, 151, 153, 243],
        12,
        231,
        12,
        121,
        111,
        false,
        &[0, 145, 110, 243, 112, 113, 102, 151, 104, 153, 142, 143],
        &[90, 92, 98, 100, 101, 130, 131, 133, 139, 141, 231],
        11,
    );
}

// ── Examples from gap/newtests.g ────────────────────────────────────────
#[test]
fn test_6_9_20_v2() {
    check(
        &[6, 9, 20],
        3,
        43,
        6,
        22,
        22,
        true,
        &[0, 49, 20, 9, 40, 29],
        &[43],
        1,
    );
}

#[test]
fn test_13_17_27_v2() {
    check(
        &[13, 17, 27],
        3,
        89,
        13,
        48,
        42,
        false,
        &[0, 27, 54, 68, 17, 44, 71, 85, 34, 61, 88, 102, 51],
        &[75, 89],
        2,
    );
}

#[test]
fn test_6_13_17_27() {
    check(
        &[6, 13, 17, 27],
        4,
        28,
        6,
        17,
        12,
        false,
        &[0, 13, 26, 27, 34, 17],
        &[20, 21, 28],
        3,
    );
}

#[test]
fn test_13_17_19_23_29_31_37_41() {
    check(
        &[13, 17, 19, 23, 29, 31, 37, 41],
        8,
        35,
        13,
        25,
        11,
        false,
        &[0, 40, 41, 29, 17, 31, 19, 46, 34, 48, 23, 37, 38],
        &[21, 24, 25, 27, 28, 33, 35],
        7,
    );
}

#[test]
fn test_46_53_55_57_60_76_91_100() {
    check(
        &[46, 53, 55, 57, 60, 76, 91, 100],
        8,
        187,
        46,
        122,
        66,
        false,
        &[
            0, 231, 186, 233, 188, 189, 144, 53, 100, 55, 148, 57, 196, 151, 60, 153, 108, 155,
            110, 157, 112, 113, 114, 115, 208, 117, 210, 165, 120, 167, 76, 169, 170, 171, 172,
            173, 174, 129, 176, 131, 224, 133, 180, 227, 136, 91,
        ],
        &[98, 119, 140, 142, 143, 150, 162, 164, 178, 181, 185, 187],
        12,
    );
}

#[test]
fn test_16_34_49_51_52_53_54_55_56_57_58_59_60_61_62_63() {
    check(
        &[
            16, 34, 49, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
        ],
        16,
        47,
        16,
        44,
        4,
        false,
        &[
            0, 49, 34, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
        ],
        &[18, 33, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47],
        15,
    );
}

#[test]
fn test_7_16_34_52_54() {
    check(
        &[7, 16, 34, 52, 54],
        5,
        47,
        7,
        31,
        17,
        false,
        &[0, 50, 16, 52, 32, 54, 34],
        &[25, 43, 45, 47],
        4,
    );
}

#[test]
fn test_6_7_16() {
    check(
        &[6, 7, 16],
        3,
        17,
        6,
        11,
        7,
        false,
        &[0, 7, 14, 21, 16, 23],
        &[15, 17],
        2,
    );
}

#[test]
fn test_24_51_58_70_71_77_79_80() {
    check(
        &[24, 51, 58, 70, 71, 77, 79, 80],
        8,
        163,
        24,
        100,
        64,
        false,
        &[
            0, 121, 122, 51, 148, 77, 102, 79, 80, 129, 58, 131, 156, 109, 158, 135, 160, 137, 138,
            187, 116, 141, 70, 71,
        ],
        &[97, 98, 107, 111, 113, 114, 117, 124, 132, 134, 136, 163],
        12,
    );
}

#[test]
fn test_10_21_22_23() {
    check(
        &[10, 21, 22, 23],
        4,
        59,
        10,
        36,
        24,
        false,
        &[0, 21, 22, 23, 44, 45, 46, 67, 68, 69],
        &[57, 58, 59],
        3,
    );
}

#[test]
fn test_26_28_30_44_64_69() {
    check(
        &[26, 28, 30, 44, 64, 69],
        6,
        145,
        26,
        84,
        62,
        false,
        &[
            0, 157, 28, 133, 30, 161, 58, 163, 60, 113, 88, 141, 64, 143, 92, 171, 94, 69, 44, 97,
            72, 99, 74, 127, 102, 129,
        ],
        &[131, 135, 137, 145],
        4,
    );
}

#[test]
fn test_14_25_29_55_60_76() {
    check(
        &[14, 25, 29, 55, 60, 76],
        6,
        91,
        14,
        53,
        39,
        false,
        &[0, 29, 58, 87, 60, 75, 76, 105, 50, 79, 80, 25, 54, 55],
        &[46, 61, 65, 73, 91],
        5,
    );
}

#[test]
fn test_28_39_62_71_80_81_89() {
    check(
        &[28, 39, 62, 71, 80, 81, 89],
        7,
        154,
        28,
        110,
        45,
        false,
        &[
            0, 169, 142, 143, 172, 89, 62, 119, 120, 149, 178, 39, 124, 181, 182, 71, 128, 101,
            158, 159, 160, 133, 78, 163, 80, 81, 110, 167,
        ],
        &[121, 130, 131, 132, 135, 139, 141, 144, 150, 153, 154],
        11,
    );
}

#[test]
fn test_13_59_70_79_84_100() {
    check(
        &[13, 59, 70, 79, 84, 100],
        6,
        186,
        13,
        107,
        80,
        false,
        &[0, 79, 158, 159, 199, 70, 84, 59, 138, 100, 140, 154, 129],
        &[125, 141, 145, 146, 186],
        5,
    );
}

#[test]
fn test_16_28_29_30_41_43() {
    check(
        &[16, 28, 29, 30, 41, 43],
        6,
        95,
        16,
        53,
        43,
        false,
        &[
            0, 97, 82, 99, 84, 69, 70, 71, 56, 41, 58, 43, 28, 29, 30, 111,
        ],
        &[68, 81, 83, 95],
        4,
    );
}

#[test]
fn test_10_23_45_71() {
    check(
        &[10, 23, 45, 71],
        4,
        107,
        10,
        58,
        50,
        false,
        &[0, 71, 92, 23, 94, 45, 46, 117, 68, 69],
        &[58, 82, 107],
        3,
    );
}

#[test]
fn test_13_16_41() {
    check(
        &[13, 16, 41],
        3,
        101,
        13,
        57,
        45,
        false,
        &[0, 105, 41, 16, 82, 57, 32, 98, 73, 48, 114, 89, 64],
        &[92, 101],
        2,
    );
}

#[test]
fn test_16_25_30_38_65_69() {
    check(
        &[16, 25, 30, 38, 65, 69],
        6,
        83,
        16,
        53,
        31,
        false,
        &[
            0, 65, 50, 99, 68, 69, 38, 55, 88, 25, 90, 75, 60, 93, 30, 63,
        ],
        &[59, 72, 74, 77, 83],
        5,
    );
}

#[test]
fn test_26_49_53_61_66_81_85_94() {
    check(
        &[26, 49, 53, 61, 66, 81, 85, 94],
        8,
        178,
        26,
        101,
        78,
        false,
        &[
            0, 53, 106, 81, 134, 187, 110, 85, 138, 61, 114, 115, 142, 143, 66, 119, 94, 147, 122,
            175, 98, 151, 204, 49, 102, 155,
        ],
        &[89, 116, 121, 149, 161, 178],
        6,
    );
}

#[test]
fn test_22_37_55_64_72_75() {
    check(
        &[22, 37, 55, 64, 72, 75],
        6,
        179,
        22,
        99,
        81,
        false,
        &[
            0, 111, 112, 201, 92, 181, 72, 139, 74, 75, 164, 55, 144, 101, 146, 37, 148, 127, 128,
            129, 64, 109,
        ],
        &[79, 90, 106, 117, 126, 159, 179],
        7,
    );
}

#[test]
fn test_15_18_23_70() {
    check(
        &[15, 18, 23, 70],
        4,
        80,
        15,
        48,
        33,
        false,
        &[0, 46, 77, 18, 64, 95, 36, 82, 23, 54, 70, 41, 72, 88, 59],
        &[67, 73, 80],
        3,
    );
}

#[test]
fn test_14_23_43_48() {
    check(
        &[14, 23, 43, 48],
        4,
        101,
        14,
        63,
        39,
        false,
        &[0, 43, 86, 115, 46, 89, 48, 91, 92, 23, 66, 109, 96, 69],
        &[75, 77, 82, 95, 101],
        5,
    );
}

#[test]
fn test_15_18_40_47_67() {
    check(
        &[15, 18, 40, 47, 67],
        5,
        104,
        15,
        55,
        50,
        false,
        &[0, 76, 47, 18, 94, 65, 36, 67, 83, 54, 40, 101, 72, 58, 119],
        &[52, 79, 104],
        3,
    );
}

#[test]
fn test_22_40_71_83_92_94_98() {
    check(
        &[22, 40, 71, 83, 92, 94, 98],
        7,
        223,
        22,
        122,
        102,
        false,
        &[
            0, 111, 134, 245, 92, 71, 94, 205, 184, 163, 98, 165, 166, 123, 80, 169, 192, 83, 40,
            151, 174, 175,
        ],
        &[141, 144, 147, 153, 162, 170, 223],
        7,
    );
}

#[test]
fn test_13_36_51_55_69_79_84() {
    check(
        &[13, 36, 51, 55, 69, 79, 84],
        7,
        125,
        13,
        72,
        54,
        false,
        &[0, 79, 106, 55, 69, 135, 84, 72, 138, 87, 36, 102, 51],
        &[59, 66, 93, 122, 125],
        5,
    );
}

#[test]
fn test_13_17_23_27() {
    check(
        &[13, 17, 23, 27],
        4,
        58,
        13,
        36,
        23,
        false,
        &[0, 27, 54, 68, 17, 44, 71, 46, 34, 61, 23, 50, 51],
        &[33, 37, 48, 55, 58],
        5,
    );
}

#[test]
fn test_16_41_45_83_97() {
    check(
        &[16, 41, 45, 83, 97],
        5,
        152,
        16,
        97,
        56,
        false,
        &[
            0, 97, 82, 83, 164, 165, 86, 135, 168, 41, 90, 123, 124, 45, 142, 127,
        ],
        &[119, 126, 148, 149, 152],
        5,
    );
}

#[test]
fn test_31_58_68_91_92_97() {
    check(
        &[31, 58, 68, 91, 92, 97],
        6,
        292,
        31,
        166,
        127,
        false,
        &[
            0, 218, 126, 189, 97, 160, 68, 286, 194, 257, 165, 228, 136, 323, 262, 232, 233, 265,
            204, 174, 299, 207, 208, 116, 241, 149, 150, 58, 183, 91, 92,
        ],
        &[202, 226, 231, 255, 268, 292],
        6,
    );
}

#[test]
fn test_41_42_54_58_78_93_97() {
    check(
        &[41, 42, 54, 58, 78, 93, 97],
        7,
        187,
        41,
        121,
        67,
        false,
        &[
            0, 42, 84, 126, 168, 210, 170, 171, 213, 132, 174, 93, 135, 54, 96, 97, 139, 58, 100,
            142, 184, 226, 186, 228, 147, 189, 108, 150, 151, 193, 112, 154, 155, 156, 116, 158,
            200, 78, 120, 162, 204,
        ],
        &[113, 148, 152, 159, 163, 169, 172, 185, 187],
        9,
    );
}

#[test]
fn test_26_38_40_48_57_61_63() {
    check(
        &[26, 38, 40, 48, 57, 61, 63],
        7,
        119,
        26,
        79,
        41,
        false,
        &[
            0, 105, 80, 133, 134, 57, 136, 111, 86, 61, 88, 63, 38, 143, 40, 145, 120, 95, 96, 97,
            124, 99, 48, 101, 76, 103,
        ],
        &[73, 75, 85, 94, 98, 107, 108, 110, 117, 119],
        10,
    );
}

#[test]
fn test_24_37_38_39_56_59() {
    check(
        &[24, 37, 38, 39, 56, 59],
        6,
        129,
        24,
        77,
        53,
        false,
        &[
            0, 97, 74, 75, 76, 77, 78, 151, 56, 153, 130, 59, 132, 37, 38, 39, 112, 113, 114, 115,
            116, 93, 94, 95,
        ],
        &[106, 108, 127, 129],
        4,
    );
}

#[test]
fn test_12_13_17() {
    check(
        &[12, 13, 17],
        3,
        57,
        12,
        30,
        28,
        false,
        &[0, 13, 26, 39, 52, 17, 30, 43, 56, 69, 34, 47],
        &[35, 57],
        2,
    );
}

#[test]
fn test_20_21_22_45_47_49_73() {
    check(
        &[20, 21, 22, 45, 47, 49, 73],
        7,
        99,
        20,
        57,
        43,
        false,
        &[
            0, 21, 22, 43, 44, 45, 66, 47, 68, 49, 70, 71, 92, 73, 94, 95, 96, 117, 98, 119,
        ],
        &[46, 72, 74, 97, 99],
        5,
    );
}

#[test]
fn test_23_45_47_55_75_76() {
    check(
        &[23, 45, 47, 55, 75, 76],
        6,
        142,
        23,
        99,
        44,
        false,
        &[
            0, 47, 94, 141, 165, 120, 75, 76, 100, 55, 102, 149, 150, 151, 152, 130, 131, 155, 110,
            157, 135, 90, 45,
        ],
        &[107, 108, 112, 118, 126, 127, 128, 129, 132, 134, 142],
        11,
    );
}

#[test]
fn test_23_24_26_28() {
    check(
        &[23, 24, 26, 28],
        4,
        137,
        23,
        69,
        69,
        true,
        &[
            0, 24, 48, 26, 50, 28, 52, 76, 54, 78, 56, 80, 104, 82, 106, 84, 108, 132, 110, 134,
            112, 136, 160,
        ],
        &[137],
        1,
    );
}

#[test]
fn test_21_32_52_57_91_98() {
    check(
        &[21, 32, 52, 57, 91, 98],
        6,
        145,
        21,
        95,
        51,
        false,
        &[
            0, 64, 128, 150, 109, 89, 153, 91, 155, 114, 52, 32, 96, 160, 98, 57, 121, 143, 123,
            166, 104,
        ],
        &[83, 122, 129, 132, 134, 139, 145],
        7,
    );
}

#[test]
fn test_26_38_45_56_58_60() {
    check(
        &[26, 38, 45, 56, 58, 60],
        6,
        171,
        26,
        94,
        78,
        false,
        &[
            0, 105, 132, 159, 56, 83, 58, 163, 60, 139, 114, 141, 38, 143, 118, 197, 94, 121, 96,
            45, 98, 177, 152, 101, 76, 103,
        ],
        &[117, 137, 151, 171],
        4,
    );
}

#[test]
fn test_14_22_29_40_52() {
    check(
        &[14, 22, 29, 40, 52],
        5,
        89,
        14,
        50,
        40,
        false,
        &[0, 29, 44, 73, 74, 103, 62, 91, 22, 51, 52, 81, 40, 69],
        &[59, 77, 89],
        3,
    );
}

#[test]
fn test_22_27_41_58_62_65() {
    check(
        &[22, 27, 41, 58, 62, 65],
        6,
        118,
        22,
        76,
        43,
        false,
        &[
            0, 89, 68, 135, 92, 27, 116, 95, 140, 119, 54, 99, 122, 123, 58, 81, 82, 127, 62, 41,
            108, 65,
        ],
        &[94, 97, 100, 101, 105, 113, 118],
        7,
    );
}

#[test]
fn test_20_32_53_54_58_77_82() {
    check(
        &[20, 32, 53, 54, 58, 77, 82],
        7,
        123,
        20,
        79,
        45,
        false,
        &[
            0, 141, 82, 143, 64, 85, 86, 107, 108, 109, 90, 111, 32, 53, 54, 135, 96, 77, 58, 139,
        ],
        &[76, 88, 115, 119, 121, 123],
        6,
    );
}

#[test]
fn test_16_23_40_65_73() {
    check(
        &[16, 23, 40, 65, 73],
        5,
        139,
        16,
        76,
        64,
        false,
        &[
            0, 65, 130, 115, 132, 69, 86, 23, 40, 73, 138, 155, 92, 109, 46, 63,
        ],
        &[114, 122, 139],
        3,
    );
}

#[test]
fn test_21_28_38_73_74_86_89() {
    check(
        &[21, 28, 38, 73, 74, 86, 89],
        7,
        141,
        21,
        84,
        58,
        false,
        &[
            0, 127, 86, 66, 130, 89, 111, 28, 155, 114, 73, 74, 117, 76, 56, 162, 142, 38, 102,
            124, 104,
        ],
        &[90, 109, 121, 134, 141],
        5,
    );
}

#[test]
fn test_12_17_21_47() {
    check(
        &[12, 17, 21, 47],
        4,
        73,
        12,
        38,
        36,
        false,
        &[0, 85, 38, 51, 64, 17, 42, 55, 68, 21, 34, 47],
        &[30, 43, 73],
        3,
    );
}

#[test]
fn test_40_42_45_68_70_72_77_88() {
    check(
        &[40, 42, 45, 68, 70, 72, 77, 88],
        8,
        179,
        40,
        109,
        71,
        false,
        &[
            0, 161, 42, 203, 84, 45, 126, 87, 88, 129, 90, 171, 132, 133, 174, 135, 136, 177, 138,
            219, 140, 181, 142, 183, 144, 145, 186, 147, 68, 149, 70, 191, 72, 113, 114, 115, 156,
            77, 158, 119,
        ],
        &[100, 105, 116, 131, 141, 143, 146, 151, 163, 179],
        10,
    );
}

#[test]
fn test_11_21_36() {
    check(
        &[11, 21, 36],
        3,
        103,
        11,
        55,
        49,
        false,
        &[0, 78, 57, 36, 114, 93, 72, 84, 63, 42, 21],
        &[73, 103],
        2,
    );
}

#[test]
fn test_6_13_27_34() {
    check(
        &[6, 13, 27, 34],
        4,
        41,
        6,
        22,
        20,
        false,
        &[0, 13, 26, 27, 34, 47],
        &[20, 21, 41],
        3,
    );
}

#[test]
fn test_15_24_27_29() {
    check(
        &[15, 24, 27, 29],
        4,
        94,
        15,
        52,
        43,
        false,
        &[0, 106, 77, 48, 109, 80, 51, 82, 53, 24, 85, 56, 27, 58, 29],
        &[91, 94],
        2,
    );
}

#[test]
fn test_11_57_67_96() {
    check(
        &[11, 57, 67, 96],
        4,
        227,
        11,
        119,
        109,
        false,
        &[0, 67, 57, 124, 114, 181, 171, 238, 96, 163, 153],
        &[142, 152, 227],
        3,
    );
}

#[test]
fn test_18_21_35_37_66_85() {
    check(
        &[18, 21, 35, 37, 66, 85],
        6,
        104,
        18,
        58,
        47,
        false,
        &[
            0, 37, 56, 21, 58, 77, 42, 79, 98, 63, 100, 101, 66, 85, 122, 87, 70, 35,
        ],
        &[52, 80, 82, 104],
        4,
    );
}

#[test]
fn test_13_16_22_62() {
    check(
        &[13, 16, 22, 62],
        4,
        85,
        13,
        44,
        42,
        false,
        &[0, 66, 54, 16, 82, 44, 32, 98, 60, 22, 62, 76, 38],
        &[49, 85],
        2,
    );
}

#[test]
fn test_52_56_60_71_85_93_95_157_158_159_161_162_163_165_167_169_171_173_174_177_181_182_184_185_192_195_196_200_204_206()
 {
    check(
        &[
            52, 56, 60, 71, 85, 93, 95, 157, 158, 159, 161, 162, 163, 165, 167, 169, 171, 173, 174,
            177, 181, 182, 184, 185, 192, 195, 196, 200, 204, 206,
        ],
        30,
        154,
        52,
        131,
        24,
        false,
        &[
            0, 157, 158, 159, 56, 161, 162, 163, 60, 165, 166, 167, 116, 169, 170, 171, 120, 173,
            174, 71, 176, 177, 178, 127, 180, 181, 182, 131, 184, 185, 186, 187, 188, 85, 190, 191,
            192, 141, 142, 195, 196, 93, 198, 95, 200, 149, 202, 151, 204, 153, 206, 155,
        ],
        &[
            89, 97, 99, 101, 103, 105, 106, 107, 109, 110, 111, 113, 114, 115, 117, 118, 119, 121,
            122, 124, 125, 126, 128, 129, 130, 132, 133, 134, 135, 136, 138, 139, 140, 143, 144,
            146, 148, 150, 152, 154,
        ],
        40,
    );
}

#[test]
fn test_12_14_18_29_37_39_45() {
    check(
        &[12, 14, 18, 29, 37, 39, 45],
        7,
        35,
        12,
        26,
        10,
        false,
        &[0, 37, 14, 39, 28, 29, 18, 43, 32, 45, 46, 47],
        &[25, 27, 31, 33, 34, 35],
        6,
    );
}

#[test]
fn test_10_29_31_32_33_34_35_36_37_38() {
    check(
        &[10, 29, 31, 32, 33, 34, 35, 36, 37, 38],
        10,
        28,
        10,
        26,
        3,
        false,
        &[0, 31, 32, 33, 34, 35, 36, 37, 38, 29],
        &[19, 21, 22, 23, 24, 25, 26, 27, 28],
        9,
    );
}

#[test]
fn test_26_38_51_56_79_80_81_83_84_85_86_87_88_91_92_93_95_96_97_98_99_100_101() {
    check(
        &[
            26, 38, 51, 56, 79, 80, 81, 83, 84, 85, 86, 87, 88, 91, 92, 93, 95, 96, 97, 98, 99,
            100, 101,
        ],
        23,
        75,
        26,
        69,
        7,
        false,
        &[
            0, 79, 80, 81, 56, 83, 84, 85, 86, 87, 88, 89, 38, 91, 92, 93, 94, 95, 96, 97, 98, 99,
            100, 101, 76, 51,
        ],
        &[
            50, 53, 54, 55, 57, 58, 59, 60, 61, 62, 63, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75,
        ],
        22,
    );
}

#[test]
fn test_17_32_52_53_54_55_56_57_58_59_60_61_62_63_65_67() {
    check(
        &[
            17, 32, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 65, 67,
        ],
        16,
        50,
        17,
        46,
        5,
        false,
        &[
            0, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 32, 67,
        ],
        &[35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 50],
        15,
    );
}

#[test]
fn test_17_38_43_47_52_53_54_56_57_58_59_61_62_63_65_66_67() {
    check(
        &[
            17, 38, 43, 47, 52, 53, 54, 56, 57, 58, 59, 61, 62, 63, 65, 66, 67,
        ],
        17,
        50,
        17,
        45,
        6,
        false,
        &[
            0, 52, 53, 54, 38, 56, 57, 58, 59, 43, 61, 62, 63, 47, 65, 66, 67,
        ],
        &[
            21, 26, 30, 35, 36, 37, 39, 40, 41, 42, 44, 45, 46, 48, 49, 50,
        ],
        16,
    );
}

#[test]
fn test_20_21_24_28_67_71_74_75_78_79() {
    check(
        &[20, 21, 24, 28, 67, 71, 74, 75, 78, 79],
        10,
        59,
        20,
        46,
        14,
        false,
        &[
            0, 21, 42, 63, 24, 45, 66, 67, 28, 49, 70, 71, 52, 73, 74, 75, 56, 77, 78, 79,
        ],
        &[43, 46, 47, 50, 51, 53, 54, 55, 57, 58, 59],
        11,
    );
}

#[test]
fn test_10_13_21_22_24_25_27_28_29() {
    check(
        &[10, 13, 21, 22, 24, 25, 27, 28, 29],
        9,
        19,
        10,
        17,
        3,
        false,
        &[0, 21, 22, 13, 24, 25, 26, 27, 28, 29],
        &[11, 12, 14, 15, 16, 17, 18, 19],
        8,
    );
}

#[test]
fn test_28_32_47_48_57_58_59_61_62_63_65_66_67_68_69_70_71_72_73_74_77_78_81_82_83() {
    check(
        &[
            28, 32, 47, 48, 57, 58, 59, 61, 62, 63, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 77, 78,
            81, 82, 83,
        ],
        25,
        55,
        28,
        51,
        5,
        false,
        &[
            0, 57, 58, 59, 32, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 47, 48, 77,
            78, 79, 80, 81, 82, 83,
        ],
        &[
            29, 30, 31, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 49, 50, 51, 52, 53,
            54, 55,
        ],
        24,
    );
}

#[test]
fn test_27_41_47_55_56_57_58_59_60_61_62_63_64_65_66_67_69_70_71_72_73_75_76_77_78_79_80() {
    check(
        &[
            27, 41, 47, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 69, 70, 71, 72, 73, 75,
            76, 77, 78, 79, 80,
        ],
        27,
        53,
        27,
        50,
        4,
        false,
        &[
            0, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 41, 69, 70, 71, 72, 73, 47, 75,
            76, 77, 78, 79, 80,
        ],
        &[
            14, 20, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 42, 43, 44, 45, 46, 48, 49,
            50, 51, 52, 53,
        ],
        26,
    );
}

#[test]
fn test_12_22_25_26_27_28_29_30_31_32_33_35() {
    check(
        &[12, 22, 25, 26, 27, 28, 29, 30, 31, 32, 33, 35],
        12,
        23,
        12,
        21,
        3,
        false,
        &[0, 25, 26, 27, 28, 29, 30, 31, 32, 33, 22, 35],
        &[10, 13, 14, 15, 16, 17, 18, 19, 20, 21, 23],
        11,
    );
}

#[test]
fn test_10_21_22_23_24_25_26_27_28_29() {
    check(
        &[10, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        10,
        19,
        10,
        18,
        2,
        false,
        &[0, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        &[11, 12, 13, 14, 15, 16, 17, 18, 19],
        9,
    );
}

#[test]
fn test_19_30_39_40_41_42_43_44_45_46_47_48_50_51_52_53_54_55_56() {
    check(
        &[
            19, 30, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 50, 51, 52, 53, 54, 55, 56,
        ],
        19,
        37,
        19,
        35,
        3,
        false,
        &[
            0, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 30, 50, 51, 52, 53, 54, 55, 56,
        ],
        &[
            11, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 31, 32, 33, 34, 35, 36, 37,
        ],
        18,
    );
}

#[test]
fn test_11_12_32() {
    check(
        &[11, 12, 32],
        3,
        85,
        11,
        43,
        43,
        true,
        &[0, 12, 24, 36, 48, 60, 72, 84, 96, 64, 32],
        &[85],
        1,
    );
}

#[test]
fn test_10_14_69() {
    check(
        &[10, 14, 69],
        3,
        115,
        10,
        58,
        58,
        true,
        &[0, 111, 42, 83, 14, 125, 56, 97, 28, 69],
        &[115],
        1,
    );
}

#[test]
fn test_14_32_44_48_52_95() {
    check(
        &[14, 32, 44, 48, 52, 95],
        6,
        177,
        14,
        89,
        89,
        true,
        &[0, 127, 44, 143, 32, 159, 48, 147, 64, 191, 52, 95, 96, 139],
        &[177],
        1,
    );
}

#[test]
fn test_13_18_81() {
    check(
        &[13, 18, 81],
        3,
        167,
        13,
        84,
        84,
        true,
        &[0, 144, 54, 81, 108, 18, 162, 72, 99, 126, 36, 180, 90],
        &[167],
        1,
    );
}

#[test]
fn test_12_18_37_87() {
    check(
        &[12, 18, 37, 87],
        4,
        167,
        12,
        84,
        84,
        true,
        &[0, 37, 74, 87, 124, 161, 18, 55, 92, 105, 142, 179],
        &[167],
        1,
    );
}

#[test]
fn test_14_15_21() {
    check(
        &[14, 15, 21],
        3,
        97,
        14,
        49,
        49,
        true,
        &[0, 15, 30, 45, 60, 75, 90, 21, 36, 51, 66, 81, 96, 111],
        &[97],
        1,
    );
}

#[test]
fn test_5_13() {
    check(
        &[5, 13],
        2,
        47,
        5,
        24,
        24,
        true,
        &[0, 26, 52, 13, 39],
        &[47],
        1,
    );
}

#[test]
fn test_13_17_71_89() {
    check(
        &[13, 17, 71, 89],
        4,
        126,
        13,
        69,
        58,
        false,
        &[0, 105, 106, 68, 17, 122, 71, 85, 34, 139, 88, 89, 51],
        &[72, 93, 126],
        3,
    );
}

#[test]
fn test_5_7() {
    check(
        &[5, 7],
        2,
        23,
        5,
        12,
        12,
        true,
        &[0, 21, 7, 28, 14],
        &[23],
        1,
    );
}

#[test]
fn test_7_11_13() {
    check(
        &[7, 11, 13],
        3,
        30,
        7,
        16,
        15,
        false,
        &[0, 22, 37, 24, 11, 26, 13],
        &[15, 30],
        2,
    );
}

#[test]
fn test_41_47_61_83() {
    check(
        &[41, 47, 61, 83],
        4,
        363,
        41,
        198,
        166,
        false,
        &[
            0, 83, 166, 249, 291, 169, 47, 130, 213, 296, 338, 216, 94, 177, 260, 343, 385, 263,
            141, 183, 61, 144, 227, 310, 188, 230, 108, 191, 274, 357, 235, 277, 155, 238, 321,
            404, 282, 324, 202, 244, 122,
        ],
        &[344, 363],
        2,
    );
}

#[test]
fn test_41_88_135_182_229_276_323_370_417_464_511_558_605_652_699_746_793_840_887_934_981_1028_1075_1122_1169_1216_1263_1310_1357_1404_1451_1498_1545_1592_1639_1686_1733_1780_1827_1874_1921()
 {
    check(
        &[
            41, 88, 135, 182, 229, 276, 323, 370, 417, 464, 511, 558, 605, 652, 699, 746, 793, 840,
            887, 934, 981, 1028, 1075, 1122, 1169, 1216, 1263, 1310, 1357, 1404, 1451, 1498, 1545,
            1592, 1639, 1686, 1733, 1780, 1827, 1874, 1921,
        ],
        41,
        1880,
        41,
        960,
        921,
        false,
        &[
            0, 370, 699, 1028, 1357, 1686, 88, 417, 746, 1075, 1404, 1733, 135, 464, 793, 1122,
            1451, 1780, 182, 511, 840, 1169, 1498, 1827, 229, 558, 887, 1216, 1545, 1874, 276, 605,
            934, 1263, 1592, 1921, 323, 652, 981, 1310, 1639,
        ],
        &[
            47, 94, 141, 188, 235, 282, 329, 376, 423, 470, 517, 564, 611, 658, 705, 752, 799, 846,
            893, 940, 987, 1034, 1081, 1128, 1175, 1222, 1269, 1316, 1363, 1410, 1457, 1504, 1551,
            1598, 1645, 1692, 1739, 1786, 1833, 1880,
        ],
        40,
    );
}

#[test]
fn test_179_181_191_193_197_199_211_223_227_229_233_239_241_251_257_263_269_271_277_281_283_293_307_311_313_317_331_337_347_349_353_359_367_373_379_383_389_397_401_409_419_421_431_433_439_443_449_457_461_463_467_479_487_491_499_503_509_521_523_547()
 {
    check(
        &[
            179, 181, 191, 193, 197, 199, 211, 223, 227, 229, 233, 239, 241, 251, 257, 263, 269,
            271, 277, 281, 283, 293, 307, 311, 313, 317, 331, 337, 347, 349, 353, 359, 367, 373,
            379, 383, 389, 397, 401, 409, 419, 421, 431, 433, 439, 443, 449, 457, 461, 463, 467,
            479, 487, 491, 499, 503, 509, 521, 523, 547,
        ],
        60,
        545,
        179,
        392,
        154,
        false,
        &[
            0, 359, 181, 540, 362, 542, 543, 544, 724, 367, 547, 548, 191, 550, 193, 373, 374, 554,
            197, 556, 199, 379, 380, 560, 382, 383, 384, 564, 386, 566, 388, 389, 211, 570, 392,
            572, 394, 574, 396, 397, 398, 578, 579, 401, 223, 582, 404, 584, 227, 586, 229, 409,
            410, 590, 233, 592, 414, 594, 416, 596, 239, 419, 241, 421, 422, 602, 424, 604, 426,
            606, 428, 608, 251, 431, 432, 433, 434, 614, 257, 616, 438, 439, 440, 620, 263, 443,
            444, 624, 446, 626, 269, 449, 271, 630, 452, 632, 454, 634, 277, 457, 458, 638, 281,
            461, 283, 463, 464, 644, 466, 467, 468, 648, 470, 650, 293, 652, 474, 654, 476, 656,
            478, 479, 480, 660, 482, 662, 484, 664, 307, 487, 488, 668, 311, 491, 313, 672, 494,
            674, 317, 676, 498, 499, 500, 680, 502, 503, 504, 684, 506, 686, 508, 509, 331, 690,
            512, 692, 514, 694, 337, 696, 518, 698, 520, 521, 522, 523, 524, 704, 347, 706, 349,
            708, 530, 710, 353, 712, 534, 714, 536,
        ],
        &[
            195, 205, 213, 215, 217, 225, 231, 235, 237, 243, 245, 247, 249, 253, 255, 259, 261,
            265, 267, 273, 275, 279, 285, 287, 289, 291, 295, 297, 299, 301, 303, 305, 309, 315,
            319, 321, 323, 325, 327, 329, 333, 335, 339, 341, 343, 345, 351, 355, 357, 361, 363,
            365, 368, 369, 371, 375, 377, 381, 385, 387, 391, 393, 395, 399, 400, 403, 405, 407,
            411, 413, 415, 417, 423, 425, 427, 429, 435, 437, 441, 445, 447, 451, 453, 455, 459,
            465, 469, 471, 473, 475, 477, 481, 483, 485, 489, 493, 495, 497, 501, 505, 507, 511,
            513, 515, 517, 519, 525, 527, 529, 531, 533, 535, 545,
        ],
        113,
    );
}

#[test]
fn test_5_7_11_13() {
    check(
        &[5, 7, 11, 13],
        4,
        9,
        5,
        7,
        3,
        false,
        &[0, 11, 7, 13, 14],
        &[6, 8, 9],
        3,
    );
}

#[test]
fn test_11_13_17_19_23_29_31() {
    check(
        &[11, 13, 17, 19, 23, 29, 31],
        7,
        27,
        11,
        19,
        9,
        false,
        &[0, 23, 13, 36, 26, 38, 17, 29, 19, 31, 32],
        &[15, 18, 20, 21, 25, 27],
        6,
    );
}

#[test]
fn test_13_17_19_23_29_31_37_41_v2() {
    check(
        &[13, 17, 19, 23, 29, 31, 37, 41],
        8,
        35,
        13,
        25,
        11,
        false,
        &[0, 40, 41, 29, 17, 31, 19, 46, 34, 48, 23, 37, 38],
        &[21, 24, 25, 27, 28, 33, 35],
        7,
    );
}

#[test]
fn test_17_19_23_29_31_37_41_43_47() {
    check(
        &[17, 19, 23, 29, 31, 37, 41, 43, 47],
        9,
        49,
        17,
        33,
        17,
        false,
        &[
            0, 52, 19, 37, 38, 56, 23, 41, 42, 43, 61, 62, 29, 47, 31, 66, 50,
        ],
        &[24, 33, 35, 39, 44, 45, 49],
        7,
    );
}

#[test]
fn test_19_23_29_31_37_41_43_47_53_59() {
    check(
        &[19, 23, 29, 31, 37, 41, 43, 47, 53, 59],
        10,
        63,
        19,
        40,
        24,
        false,
        &[
            0, 58, 59, 41, 23, 43, 82, 64, 46, 47, 29, 68, 31, 70, 52, 53, 54, 74, 37,
        ],
        &[27, 33, 35, 39, 45, 49, 51, 55, 63],
        9,
    );
}

#[test]
fn test_23_29_31_37_41_43_47_53_59_61_67_71_73_79() {
    check(
        &[23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79],
        14,
        65,
        23,
        48,
        18,
        false,
        &[
            0, 47, 71, 72, 73, 74, 29, 53, 31, 78, 79, 80, 58, 59, 37, 61, 62, 86, 41, 88, 43, 67,
            68,
        ],
        &[30, 35, 38, 39, 44, 45, 48, 49, 50, 51, 55, 56, 57, 63, 65],
        15,
    );
}

#[test]
fn test_29_31_37_41_43_47_53_59_61_67_71_73_79_83() {
    check(
        &[29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83],
        14,
        85,
        29,
        58,
        28,
        false,
        &[
            0, 59, 31, 61, 62, 92, 93, 94, 37, 67, 68, 98, 41, 71, 43, 73, 74, 104, 47, 106, 78,
            79, 80, 110, 53, 83, 84, 114, 86,
        ],
        &[39, 45, 49, 51, 55, 57, 63, 64, 65, 69, 75, 77, 81, 85],
        14,
    );
}

#[test]
fn test_31_37_41_43_47_53_59_61_67_71_73_79_83_89_97_101_107() {
    check(
        &[
            31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97, 101, 107,
        ],
        17,
        95,
        31,
        67,
        29,
        false,
        &[
            0, 94, 126, 96, 97, 67, 37, 100, 101, 71, 41, 73, 43, 106, 107, 108, 47, 79, 80, 112,
            82, 83, 53, 116, 86, 118, 88, 89, 59, 122, 61,
        ],
        &[
            49, 51, 55, 57, 63, 65, 66, 69, 70, 75, 76, 77, 81, 85, 87, 91, 95,
        ],
        17,
    );
}

#[test]
fn test_37_41_43_47_53_59_61_67_71_73_79_83_89_97_101_103_107_109_113() {
    check(
        &[
            37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97, 101, 103, 107, 109, 113,
        ],
        19,
        105,
        37,
        75,
        31,
        false,
        &[
            0, 112, 113, 114, 41, 79, 43, 118, 82, 83, 47, 122, 86, 124, 88, 89, 53, 128, 129, 130,
            94, 132, 59, 97, 61, 136, 100, 101, 102, 103, 67, 142, 106, 107, 71, 109, 73,
        ],
        &[
            57, 60, 63, 65, 66, 69, 70, 72, 75, 76, 77, 81, 85, 87, 91, 92, 93, 95, 99, 105,
        ],
        20,
    );
}

#[test]
fn test_41_43_47_53_59_61_67_71_73_79_83_89_97_101_103_107_109_113() {
    check(
        &[
            41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97, 101, 103, 107, 109, 113,
        ],
        18,
        121,
        41,
        85,
        37,
        false,
        &[
            0, 83, 43, 126, 86, 128, 47, 89, 90, 132, 133, 134, 53, 136, 96, 97, 139, 140, 59, 101,
            61, 103, 104, 146, 106, 107, 67, 109, 110, 152, 71, 113, 73, 156, 116, 158, 118, 160,
            79, 162, 122,
        ],
        &[
            63, 65, 69, 75, 77, 81, 85, 87, 91, 92, 93, 95, 98, 99, 105, 111, 115, 117, 119, 121,
        ],
        20,
    );
}

#[test]
fn test_43_47_53_59_61_67_71_73_79_83_89_97_101_103_107_109_113_127_131() {
    check(
        &[
            43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97, 101, 103, 107, 109, 113, 127, 131,
        ],
        19,
        135,
        43,
        92,
        44,
        false,
        &[
            0, 130, 131, 89, 47, 134, 178, 136, 94, 138, 53, 97, 141, 142, 100, 101, 59, 103, 61,
            148, 106, 107, 108, 109, 67, 154, 112, 113, 71, 158, 73, 160, 118, 162, 120, 164, 79,
            166, 124, 168, 83, 127, 128,
        ],
        &[
            57, 63, 65, 69, 75, 77, 81, 84, 85, 87, 91, 93, 95, 98, 99, 105, 111, 115, 117, 119,
            121, 123, 125, 135,
        ],
        24,
    );
}

#[test]
fn test_47_53_59_61_67_71_73_79_83_89_97_101_103_107_109_113_127_131_137_139_149_151_157_163() {
    check(
        &[
            47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97, 101, 103, 107, 109, 113, 127, 131, 137,
            139, 149, 151, 157, 163,
        ],
        24,
        145,
        47,
        104,
        42,
        false,
        &[
            0, 142, 190, 97, 192, 146, 53, 101, 149, 103, 151, 152, 59, 107, 61, 109, 157, 158,
            112, 113, 67, 162, 163, 164, 71, 166, 73, 168, 122, 170, 124, 172, 79, 127, 128, 176,
            83, 131, 132, 180, 134, 182, 89, 137, 138, 139, 140,
        ],
        &[
            65, 75, 77, 81, 85, 87, 91, 93, 95, 99, 102, 104, 105, 110, 111, 115, 116, 117, 119,
            121, 123, 125, 129, 133, 135, 143, 145,
        ],
        27,
    );
}

#[test]
fn test_53_59_61_67_71_73_79_83_89_97_101_103_107_109_113_127_131_137_139_149_151_157_163() {
    check(
        &[
            53, 59, 61, 67, 71, 73, 79, 83, 89, 97, 101, 103, 107, 109, 113, 127, 131, 137, 139,
            149, 151, 157, 163,
        ],
        23,
        169,
        53,
        114,
        56,
        false,
        &[
            0, 107, 214, 109, 163, 164, 59, 113, 61, 168, 222, 170, 118, 172, 67, 174, 122, 176,
            71, 178, 73, 127, 128, 182, 130, 131, 79, 186, 134, 188, 83, 137, 138, 139, 140, 194,
            89, 196, 144, 198, 146, 200, 148, 149, 97, 151, 152, 206, 101, 208, 103, 157, 158,
        ],
        &[
            65, 69, 75, 77, 81, 85, 87, 91, 93, 95, 99, 104, 105, 111, 115, 117, 119, 121, 123,
            125, 129, 133, 135, 141, 143, 145, 147, 153, 155, 161, 169,
        ],
        31,
    );
}

#[test]
fn test_59_61_67_71_73_79_83_89_97_101_103_107_109_113_127_131_137_139_149_151_157_163_167_173() {
    check(
        &[
            59, 61, 67, 71, 73, 79, 83, 89, 97, 101, 103, 107, 109, 113, 127, 131, 137, 139, 149,
            151, 157, 163, 167, 173,
        ],
        24,
        175,
        59,
        124,
        52,
        false,
        &[
            0, 178, 61, 180, 122, 182, 183, 184, 67, 127, 128, 188, 71, 131, 73, 192, 134, 194,
            195, 137, 79, 139, 140, 200, 83, 202, 144, 204, 146, 206, 89, 149, 150, 151, 152, 212,
            154, 214, 97, 157, 158, 218, 101, 220, 103, 163, 164, 224, 107, 167, 109, 228, 170,
            230, 113, 173, 174, 234, 176,
        ],
        &[
            81, 85, 87, 91, 93, 95, 99, 105, 111, 115, 117, 119, 121, 123, 124, 125, 129, 133, 135,
            136, 141, 143, 145, 147, 153, 155, 159, 161, 165, 169, 171, 175,
        ],
        32,
    );
}

#[test]
fn test_61_67_71_73_79_83_89_97_101_103_107_109_113_127_131_137_139_149_151_157_163_167_173_179_181_191_197()
 {
    check(
        &[
            61, 67, 71, 73, 79, 83, 89, 97, 101, 103, 107, 109, 113, 127, 131, 137, 139, 149, 151,
            157, 163, 167, 173, 179, 181, 191, 197,
        ],
        27,
        187,
        61,
        133,
        55,
        false,
        &[
            0, 184, 246, 186, 248, 127, 67, 190, 191, 131, 71, 194, 73, 196, 197, 137, 138, 139,
            79, 202, 142, 204, 83, 206, 146, 208, 209, 149, 89, 151, 152, 214, 154, 216, 156, 157,
            97, 220, 160, 222, 101, 163, 103, 226, 166, 167, 107, 230, 109, 232, 172, 173, 113,
            236, 176, 238, 178, 179, 180, 181, 182,
        ],
        &[
            85, 91, 93, 95, 99, 105, 111, 115, 117, 119, 121, 123, 125, 129, 130, 133, 135, 136,
            141, 143, 145, 147, 148, 153, 155, 159, 161, 165, 169, 171, 175, 177, 185, 187,
        ],
        34,
    );
}

#[test]
fn test_67_71_73_79_83_89_97_101_103_107_109_113_127_131_137_139_149_151_157_163_167_173_179_181_191_193_197_199()
 {
    check(
        &[
            67, 71, 73, 79, 83, 89, 97, 101, 103, 107, 109, 113, 127, 131, 137, 139, 149, 151, 157,
            163, 167, 173, 179, 181, 191, 193, 197, 199,
        ],
        28,
        203,
        67,
        141,
        63,
        false,
        &[
            0, 202, 270, 137, 71, 139, 73, 208, 142, 210, 144, 212, 79, 214, 215, 149, 83, 151,
            152, 220, 154, 222, 89, 157, 158, 226, 160, 228, 162, 163, 97, 232, 166, 167, 101, 236,
            103, 238, 172, 173, 107, 242, 109, 244, 178, 179, 113, 181, 182, 250, 184, 252, 186,
            254, 188, 256, 190, 191, 192, 193, 127, 262, 196, 197, 131, 199, 200,
        ],
        &[
            85, 87, 91, 93, 95, 99, 105, 111, 115, 117, 119, 121, 123, 125, 126, 129, 133, 135,
            141, 143, 145, 147, 148, 153, 155, 159, 161, 165, 169, 171, 175, 177, 183, 185, 187,
            189, 195, 203,
        ],
        38,
    );
}

#[test]
fn test_71_73_79_83_89_97_101_103_107_109_113_127_131_137_139_149_151_157_163_167_173_179_181_191_193_197_199_211()
 {
    check(
        &[
            71, 73, 79, 83, 89, 97, 101, 103, 107, 109, 113, 127, 131, 137, 139, 149, 151, 157,
            163, 167, 173, 179, 181, 191, 193, 197, 199, 211,
        ],
        28,
        209,
        71,
        150,
        60,
        false,
        &[
            0, 214, 73, 216, 146, 218, 219, 149, 79, 151, 152, 224, 83, 226, 156, 157, 158, 230,
            89, 232, 162, 163, 235, 236, 166, 167, 97, 240, 170, 242, 101, 173, 103, 246, 176, 248,
            107, 179, 109, 181, 182, 254, 113, 256, 186, 258, 188, 260, 190, 191, 192, 193, 194,
            266, 196, 197, 127, 199, 200, 272, 131, 274, 204, 276, 206, 278, 137, 280, 139, 211,
            212,
        ],
        &[
            87, 95, 99, 105, 111, 115, 117, 119, 121, 123, 125, 129, 133, 135, 140, 141, 143, 145,
            147, 148, 153, 155, 159, 161, 164, 165, 169, 171, 175, 177, 183, 185, 187, 189, 195,
            201, 203, 205, 207, 209,
        ],
        40,
    );
}

// ── Canonical ideal K(S) ──────────────────────────────────────────────────────

#[test]
fn test_canonical_ideal_generators() {
    // gen(K(S)) = {f − p : p ∈ PF(S), p ≠ f} for non-symmetric semigroups.
    let cases: &[(&[usize], &[usize])] = &[
        // ⟨6, 13, 17, 27⟩: f=28, PF={20,21,28}  →  K = ⟨7, 8⟩
        (&[6, 13, 17, 27], &[7, 8]),
        // ⟨12, 14, 19, 77⟩: f=65, PF={58,63,65}  →  K = ⟨2, 7⟩
        (&[12, 14, 19, 77], &[2, 7]),
    ];
    for &(gens, expected_k_gens) in cases {
        let s = compute(gens);
        let k = s.canonical_ideal();

        // Verify formula: gen(K) = {f − p : p ∈ PF, p ≠ f}, sorted.
        let mut from_formula: Vec<usize> = s
            .pf_set
            .iter()
            .filter(|&&p| p != s.f)
            .map(|&p| s.f - p)
            .collect();
        from_formula.sort_unstable();
        let mut actual = k.gen_set.clone();
        actual.sort_unstable();
        assert_eq!(
            actual, from_formula,
            "gen(K(S)) = {{f−p : p ∈ PF(S)\\{{f}}}} for {gens:?}"
        );

        // Verify against the known expected generators.
        assert_eq!(actual, expected_k_gens, "K(S) generators for {gens:?}");
    }
}

#[test]
fn test_canonical_ideal_containment() {
    // S ⊊ K(S) when the generators of K reach below m(S).
    // ⟨12, 14, 19, 77⟩: K = ⟨2, 7⟩; every element of S is ≥ 12 > f(K)=5,
    // so S ⊆ K, and 2 ∈ K \ S, giving S ⊊ K.
    let s = compute(&[12, 14, 19, 77]);
    let k = s.canonical_ideal();
    assert!(s < k, "⟨12,14,19,77⟩ ⊊ K(S)");
}

#[test]
fn test_canonical_ideal_symmetric() {
    // For symmetric semigroups, K(S) = S.
    for gens in [
        [6, 9, 20].as_slice(), // symmetric, f=43
        [5, 7].as_slice(),     // symmetric, f=23
        [2, 11].as_slice(),    // symmetric, f=9
    ] {
        let s = compute(gens);
        assert!(s.is_symmetric, "{gens:?} should be symmetric");
        let k = s.canonical_ideal();
        assert_eq!(
            s.partial_cmp(&k),
            Some(std::cmp::Ordering::Equal),
            "K(S) = S for symmetric {gens:?}"
        );
    }
}

#[test]
fn test_u_times_two_ones_is_m_zero_zero() {
    // U(m) · (2, 1, 1, …, 1)ᵀ = (m, 0, 0, …, 0)ᵀ for every m ≥ 2.
    // This is the identity that makes `compute_apery_shift_first` correspond
    // to a Kunz-cone neighbour (row 1 of C shifted by (2, 1, …, 1)).
    for m in 2..=12 {
        let n = m - 1;
        let u = u_matrix(m);
        let mut v = vec![1i64; n];
        v[0] = 2;
        let mut prod = vec![0i64; n];
        for i in 0..n {
            for (j, vj) in v.iter().enumerate().take(n) {
                prod[i] += u[(i, j)] * vj;
            }
        }
        let mut expected = vec![0i64; n];
        expected[0] = i64::try_from(m).expect("m fits in i64");
        assert_eq!(prod, expected, "U({m})·(2,1,…,1)ᵀ ≠ (m,0,…,0)ᵀ");
    }
}

#[test]
fn test_apery_shift_first_when_kunz_move_is_valid() {
    // When every antidiagonal Kunz entry c_{a,b} with (a+b) ≡ 1 (mod m) and
    // a,b ≠ 1 is ≥ 1, the move w₁ → w₁ + m is a valid Kunz-cone neighbour
    // and the result has multiplicity m and Apéry (0, w₁+m, w₂, …, w_{m-1}).
    // <3,7,11>: m=3, Ap=(0,7,11), c_22 = (11+11-7)/3 = 5 ≥ 1 → valid.
    // <4,5,6,7>: m=4, Ap=(0,5,6,7), c_23 = (6+7-5)/4 = 2 ≥ 1 → valid.
    for gens in [[3, 7, 11].as_slice(), [4, 5, 6, 7].as_slice()] {
        let s = compute(gens);
        let s2 = s.compute_apery_shift_first();
        assert_eq!(s2.m, s.m, "multiplicity preserved for {gens:?}");
        let mut want = s.apery_set.clone();
        want[1] += s.m;
        assert_eq!(
            s2.apery_set, want,
            "Apéry shift for {gens:?}: got {:?}, want {:?}",
            s2.apery_set, want,
        );
    }
}

#[test]
fn test_apery_shift_first_changes_s_iff_w1_is_minimal_generator() {
    // Equivalence: the move w₁ → w₁+m yields a different semigroup iff w₁
    // is a minimal generator. (When w₁ ∉ gen_set, w₁ = w_a + w_b for some
    // a,b ≠ 1 with (a+b)≡1 mod m, so c_{a,b} = 0, so the Kunz move forces
    // c_{a,b} = -1 — and compute() recovers the original w₁ as that sum.)
    for gens in [
        [3, 7, 11].as_slice(),   // w₁ = 7  ∈ gen_set → moves
        [4, 5, 6, 7].as_slice(), // w₁ = 5  ∈ gen_set → moves
        [6, 9, 20].as_slice(),   // w₁ = 49 ∉ gen_set → no-op
        [5, 6, 8].as_slice(),    // various
        [7, 11, 13, 17, 19].as_slice(),
        [10, 14, 21].as_slice(),
    ] {
        let s = compute(gens);
        let w1 = s.apery_set[1];
        let w1_is_gen = s.gen_set.contains(&w1);
        let s2 = s.compute_apery_shift_first();
        let changed = s.partial_cmp(&s2) != Some(std::cmp::Ordering::Equal);
        assert_eq!(
            changed, w1_is_gen,
            "for {gens:?}: w₁={w1}, w1_is_gen={w1_is_gen}, changed={changed}",
        );
    }
}

/// Brute-force count of reflected gaps `x` (gap with `f − x` also a gap)
/// grouped by residue class mod `m`. Used to cross-check `Semigroup::r_i`.
fn brute_force_ri(sg: &semigroup_math::math::Semigroup) -> Vec<usize> {
    let mut counts = vec![0usize; sg.m];
    if sg.f == 0 {
        return counts;
    }
    for x in 1..sg.f {
        if sg.is_gap(x) && sg.is_gap(sg.f - x) {
            counts[x % sg.m] += 1;
        }
    }
    counts
}

#[test]
fn test_r_i_matches_brute_force() {
    // Spans several m values and mu values, and includes <4,7,9,10> where
    // r_1 = 2 (the case the underflow fix is meant to handle: mu = 2, i = 3).
    let cases: &[&[usize]] = &[
        &[3, 5, 7],
        &[3, 7, 11],
        &[3, 10, 11],
        &[4, 5, 6, 7],
        &[4, 7, 9, 10],
        &[5, 6, 7, 8, 9],
        &[5, 7, 9],
        &[6, 9, 20],
    ];
    for gens in cases {
        let sg = compute(gens);
        let expected = brute_force_ri(&sg);
        for (i, &want) in expected.iter().enumerate().take(sg.m).skip(1) {
            assert_eq!(
                sg.r_i(i),
                want,
                "r_{i} mismatch for {gens:?} (m={}, mu={})",
                sg.m,
                sg.mu,
            );
        }
        assert_eq!(sg.r_i(0), 0);
        assert_eq!(sg.r_i(sg.m), 0);
    }
}

#[test]
fn test_min_max_any_ri() {
    // min_ri excludes i = μ (where r_μ = 0 by construction), so on a fresh
    // semigroup it picks up the smallest *non-trivial* count.

    // <4, 7, 9, 10>: f=6, μ=2. r_1=2, r_2=0, r_3=1 → min over {1,3} = 1.
    let sg = compute(&[4, 7, 9, 10]);
    assert_eq!(sg.r_i(1), 2);
    assert_eq!(sg.r_i(2), 0);
    assert_eq!(sg.r_i(3), 1);
    assert_eq!(sg.min_ri(), 1);
    assert_eq!(sg.max_ri(), 2);
    assert!(sg.any_ri_eq_2());

    // <3, 5, 7>: f=4, μ=1. r_1=0, r_2=1 → min over {2} = 1.
    let sg = compute(&[3, 5, 7]);
    assert_eq!(sg.min_ri(), 1);
    assert_eq!(sg.max_ri(), 1);
    assert!(!sg.any_ri_eq_2());

    // <3, 10, 11>: f=8, μ=2. r_1=3, r_2=0 → min over {1} = 3.
    let sg = compute(&[3, 10, 11]);
    assert_eq!(sg.min_ri(), 3);
    assert_eq!(sg.max_ri(), 3);
    assert!(!sg.any_ri_eq_2());

    // m = 2: 1..m \ {μ} is empty (μ = 1 since f is odd) → min_ri = 0,
    // any_ri_eq_2 = false. <2, 5>: f=3, μ=1.
    let sg = compute(&[2, 5]);
    assert_eq!(sg.mu, 1);
    assert_eq!(sg.min_ri(), 0);
    assert_eq!(sg.max_ri(), 0);
    assert!(!sg.any_ri_eq_2());
}

#[test]
fn test_is_deep() {
    // Helper: checks that `deep` matches whether all {m+1,...,2m-1} are gaps.
    let check_deep = |sg: &semigroup_math::math::Semigroup| {
        let all_gaps = (1..sg.m).all(|i| sg.is_gap(sg.m + i));
        assert_eq!(
            sg.deep, all_gaps,
            "deep disagrees with direct gap check for gens={:?} m={} f={}",
            sg.gen_set, sg.m, sg.f
        );
    };

    // <3, 7, 11>: m=3, f=8. {4, 5} are gaps (apery=[0,7,11]). deep=true.
    let sg = compute(&[3, 7, 11]);
    assert!(sg.deep);
    assert!(sg.is_gap(4) && sg.is_gap(5));
    check_deep(&sg);

    // <3, 4>: m=3, 4 ∈ S (generator). {4,5}: 4 in S → not deep.
    let sg = compute(&[3, 4]);
    assert!(!sg.deep);
    assert!(!sg.is_gap(4));
    check_deep(&sg);

    // <3, 5>: m=3, 5 ∈ S (generator). {4,5}: 5 in S → not deep.
    let sg = compute(&[3, 5]);
    assert!(!sg.deep);
    assert!(!sg.is_gap(5));
    check_deep(&sg);

    // <5, 11, 12, 13, 14>: m=5. {6,7,8,9} are all gaps (apery=[0,11,12,13,14]). deep=true.
    let sg = compute(&[5, 11, 12, 13, 14]);
    assert!(sg.deep);
    for i in 1..sg.m {
        assert!(sg.is_gap(sg.m + i), "expected gap at {}", sg.m + i);
    }
    check_deep(&sg);

    // <2, 3>: m=2. {3} is in S → not deep.
    let sg = compute(&[2, 3]);
    assert!(!sg.deep);
    assert!(!sg.is_gap(3));
    check_deep(&sg);

    // <2, 5>: m=2. {3} — 3 mod 2 = 1, apery[1]=5 > 3, so 3 is a gap. deep=true.
    let sg = compute(&[2, 5]);
    assert!(sg.deep);
    assert!(sg.is_gap(3));
    check_deep(&sg);
}

#[test]
fn test_is_descent() {
    // Checks the implication: is_descent() && max_gen == f+m  =>  deep.
    let check = |sg: &semigroup_math::math::Semigroup| {
        if sg.is_descent() && sg.max_gen == sg.f + sg.m {
            assert!(
                sg.deep,
                "is_descent && max_gen==f+m should imply deep for gens={:?}",
                sg.gen_set,
            );
        }
    };

    // <2,5>: apery=[0,5], f=3, f+m=5=max_gen. is_descent=true, deep=true.
    let sg = compute(&[2, 5]);
    assert!(sg.is_descent());
    assert_eq!(sg.max_gen, sg.f + sg.m);
    assert!(sg.deep);
    check(&sg);

    // <3,7,11>: apery=[0,7,11], f=8, f+m=11=max_gen. is_descent=true, deep=true.
    let sg = compute(&[3, 7, 11]);
    assert!(sg.is_descent());
    assert_eq!(sg.max_gen, sg.f + sg.m);
    assert!(sg.deep);
    check(&sg);

    // <3,4>: apery=[0,4,8], f=5, f+m=8. is_descent=true (4<f, 8=f+m),
    // but max_gen=4≠8=f+m and deep=false (4∈S). Implication not triggered.
    let sg = compute(&[3, 4]);
    assert!(sg.is_descent());
    assert_ne!(sg.max_gen, sg.f + sg.m);
    assert!(!sg.deep);
    check(&sg);

    // <3,4,5>: apery=[0,4,5], f=2. w_1=4>f=2 and 4≠f+m=5. is_descent=false.
    let sg = compute(&[3, 4, 5]);
    assert!(!sg.is_descent());
    check(&sg);
}

#[test]
fn test_fast_descent_drops_f_by_m_and_preserves_mu() {
    // Specification: whenever f ≥ 2m the result of fast_descent has μ unchanged
    // and Frobenius number exactly old f − m.

    // 1. Hand-checked !is_descent example: <10,11,13> has f=38, m=10, μ=8 and
    //    apéry=[0,11,22,13,24,35,26,37,48,39] — a_9 = 39 ∈ (f, f+m), so
    //    is_descent is false and naïvely adding only f would land at f=29, μ=9.
    let s = compute(&[10, 11, 13]);
    assert!(!s.is_descent());
    assert_eq!((s.f, s.m, s.mu), (38, 10, 8));
    let t = s.fast_descent();
    assert_eq!(t.f, s.f - s.m);
    assert_eq!(t.mu, s.mu);

    // 2. is_descent example for completeness: <5,7> has f=23, m=5, μ=3 and
    //    apéry=[0,21,7,28,14], so the only Apéry element ≥ f is 28 = f+m.
    let s = compute(&[5, 7]);
    assert!(s.is_descent());
    assert_eq!((s.f, s.m, s.mu), (23, 5, 3));
    let t = s.fast_descent();
    assert_eq!(t.f, s.f - s.m);
    assert_eq!(t.mu, s.mu);

    // 3. Sweep over a range of generator pairs/triples and assert the property
    //    on every semigroup with f ≥ 2m. This would catch the previous bug,
    //    which adds the Apéry elements themselves (no-ops) instead of x−m.
    let mut sweep_count = 0;
    for a in 3..=12 {
        for b in (a + 1)..=20 {
            if gcd(a, b) != 1 {
                continue;
            }
            for c in (b + 1)..=25 {
                if gcd(gcd(a, b), c) != 1 {
                    continue;
                }
                let s = compute(&[a, b, c]);
                if s.f < 2 * s.m {
                    continue;
                }
                let t = s.fast_descent();
                assert_eq!(
                    t.f,
                    s.f - s.m,
                    "fast_descent f for gens={:?}: expected {}, got {}",
                    s.gen_set,
                    s.f - s.m,
                    t.f,
                );
                assert_eq!(
                    t.mu, s.mu,
                    "fast_descent mu for gens={:?}: expected {}, got {}",
                    s.gen_set, s.mu, t.mu,
                );
                sweep_count += 1;
            }
        }
    }
    assert!(sweep_count > 0, "sweep must exercise at least one case");
}

#[test]
fn test_fast_descent_returns_self_when_f_lt_2m() {
    // S = ℕ: m=1, f=0. fast_descent must not touch the generator set.
    let s = compute(&[1]);
    assert_eq!(s.fast_descent().gen_set, s.gen_set);

    // Terminal range m < f < 2m: <3,4> has m=3, f=5, so 5 < 6 = 2m.
    let s = compute(&[3, 4]);
    assert!(s.f < 2 * s.m);
    assert_eq!(s.fast_descent().gen_set, s.gen_set);
}

#[test]
fn test_creators_tmf() {
    assert_eq!(tmf_generators(3, 6), vec![3, 7, 8, 9]);

    // T(4, 7): ⟨4, 8, 9, 10, 11⟩; 8 reduces to 4+4 so minimal gens are
    // ⟨4, 9, 10, 11⟩, Apéry [0, 9, 10, 11], f = 11 − 4 = 7.
    let s = compute(&tmf_generators(4, 7));
    assert_eq!(s.m, 4);
    assert_eq!(s.f, 7);
    assert_eq!(s.apery_set, vec![0, 9, 10, 11]);
}

#[test]
fn test_creators_arith() {
    assert_eq!(arith_generators(3, 2, 3), vec![3, 5, 7, 9]);
    // 9 = 3+3+3 is reducible so minimal gens are ⟨3, 5, 7⟩.
    let s = compute(&arith_generators(3, 2, 3));
    assert_eq!(s.gen_set, vec![3, 5, 7]);

    // Single generator m,d=1,n=0 → ⟨m⟩ which compute() rescales to ⟨1⟩ = ℕ.
    let s = compute(&arith_generators(5, 0, 0));
    assert_eq!(s.m, 1);
}

#[test]
fn test_creators_rolf_primes() {
    // p_1 = 2; primes 2 ≤ p ≤ 10.
    assert_eq!(rolf_primes(1), vec![2, 3, 5, 7]);
    // p_3 = 5; primes 5 ≤ p ≤ 25.
    assert_eq!(rolf_primes(3), vec![5, 7, 11, 13, 17, 19, 23]);
    // n=0 clamps to n=1.
    assert_eq!(rolf_primes(0), rolf_primes(1));
}

#[test]
fn test_random_creators_basic_shape() {
    let nums = random_generators();
    assert_eq!(nums.len(), 8);
    assert!(nums.iter().all(|&x| (10..=100).contains(&x)));

    // multiplier-extended list yields a valid semigroup.
    let s = compute(&random_with_multiplier_generators(2));
    assert!(s.m >= 1);

    let primes = random_primes_subset();
    assert!((4..=8).contains(&primes.len()));
    assert!(primes.windows(2).all(|w| w[0] < w[1]));
}

#[test]
fn test_random_creators_predicate_postconditions() {
    let g =
        random_matching_generators(|s| s.is_symmetric).expect("random_symmetric should succeed");
    assert!(compute(&g).is_symmetric);

    let g =
        random_matching_generators(|s| s.r == 1).expect("random_pseudo_symmetric should succeed");
    assert_eq!(compute(&g).r, 1);

    let g = random_matching_generators(|s| s.is_almost_symmetric && s.r >= 2)
        .expect("random_almost_symmetric should succeed");
    let s = compute(&g);
    assert!(s.is_almost_symmetric);
    assert!(s.r >= 2);
}

#[test]
fn test_descent_changes_r_by_exact_amount() {
    // Per-step descent changes the reflected-gap count `r` by an exact
    // amount that depends on which descent branch ran:
    //   - is_descent (add f as generator):     Δr =  m − 2
    //   - !is_descent (add x − m for largest   Δr = −2
    //     apéry x ∈ (f, f+m))
    //
    // The is_descent branch can flip parity (m odd → m−2 odd); the
    // !is_descent branch always stays even.
    //
    // The !is_descent claim assumes the multiplicity is preserved. When
    // f < 2m the added gap x − m can be smaller than m and the new
    // semigroup has a smaller multiplicity (e.g. ⟨3,5,7⟩ has f=4, x=5,
    // and adds 2; new m drops to 2 and Δr = −1). The sweep restricts to
    // f ≥ 2m where x > f ≥ 2m, so x − m > m and m is preserved.
    let mut tested = 0;
    for a in 2..=15 {
        for b in (a + 1)..=25 {
            if gcd(a, b) != 1 {
                continue;
            }
            for c in (b + 1)..=30 {
                if gcd(gcd(a, b), c) != 1 {
                    continue;
                }
                let s = compute(&[a, b, c]);
                if s.f < 2 * s.m {
                    continue;
                }

                let after = s.descent();
                let dr = isize::try_from(after.r).unwrap() - isize::try_from(s.r).unwrap();
                let expected = if s.is_descent() {
                    isize::try_from(s.m).unwrap() - 2
                } else {
                    -2
                };
                assert_eq!(
                    dr,
                    expected,
                    "descent on gens={:?} (m={}, f={}, is_descent={}): \
                     expected Δr = {}, got {} (r: {} → {})",
                    s.gen_set,
                    s.m,
                    s.f,
                    s.is_descent(),
                    expected,
                    dr,
                    s.r,
                    after.r,
                );
                tested += 1;
            }
        }
    }
    assert!(tested > 0, "sweep must exercise at least one case");
}

#[test]
fn test_fast_descent_changes_r_by_exact_amount() {
    // fast_descent (when f ≥ 2m) collapses k = #(apéry ∈ (f, f+m)) per-step
    // !is_descent removals (each Δr = −2) followed by one is_descent step
    // (Δr = m − 2). Net: Δr = (m − 2) − 2·k.
    let mut tested = 0;
    for a in 2..=15 {
        for b in (a + 1)..=25 {
            if gcd(a, b) != 1 {
                continue;
            }
            for c in (b + 1)..=30 {
                if gcd(gcd(a, b), c) != 1 {
                    continue;
                }
                let s = compute(&[a, b, c]);
                if s.f < 2 * s.m {
                    continue;
                }

                let after = s.fast_descent();
                let dr = isize::try_from(after.r).unwrap() - isize::try_from(s.r).unwrap();
                let k = s
                    .apery_set
                    .iter()
                    .filter(|&&x| s.f < x && x < s.f + s.m)
                    .count();
                let expected = isize::try_from(s.m).unwrap() - 2 - 2 * isize::try_from(k).unwrap();
                assert_eq!(
                    dr, expected,
                    "fast_descent on gens={:?} (m={}, f={}, k={}): \
                     expected Δr = {}, got {} (r: {} → {})",
                    s.gen_set, s.m, s.f, k, expected, dr, s.r, after.r,
                );
                tested += 1;
            }
        }
    }
    assert!(tested > 0, "sweep must exercise at least one case");
}

#[test]
fn test_is_descent_image_holds_for_every_descent_output() {
    // Forward direction: every descent output is recognised by the predicate.
    // Sweep over generator triples T, descend, and verify the result is
    // labeled as in the descent image. Includes the is_descent regime
    // (where the added gen lands at a_μ = f+m, not in (f−m, f)).
    let mut tested = 0;
    for a in 2..=15 {
        for b in (a + 1)..=25 {
            if gcd(a, b) != 1 {
                continue;
            }
            for c in (b + 1)..=30 {
                if gcd(gcd(a, b), c) != 1 {
                    continue;
                }
                let t = compute(&[a, b, c]);
                if t.f < t.m {
                    continue;
                }
                let s = t.descent();
                assert!(
                    s.is_descent_image(),
                    "descent output of T={:?} should be in image; \
                     S.gen_set={:?}, S.f={}, S.m={}, is_descent(T)={}",
                    t.gen_set,
                    s.gen_set,
                    s.f,
                    s.m,
                    t.is_descent(),
                );
                tested += 1;
            }
        }
    }
    assert!(tested > 0);
}

#[test]
fn test_is_descent_image_concrete_cases() {
    // ⟨5, 7, 23⟩ is image of ⟨5, 7⟩ via the is_descent branch; its min-gen
    // 23 = a_μ = f+m caches the descent step.
    let s = compute(&[5, 7, 23]);
    assert_eq!((s.m, s.f), (5, 18));
    assert_eq!(s.f + s.m, 23);
    assert!(s.is_descent_image());

    // ⟨5, 7⟩ itself: gens 5, 7, both below f−m=18; max apery 28 ≠ any min-gen.
    // So it's outside the descent image — there's no T with T.descent()=⟨5,7⟩.
    let s = compute(&[5, 7]);
    assert!(!s.is_descent_image());

    // ⟨10, 11, 13, 29⟩: image via the !is_descent branch (29 ∈ (28, 38)).
    let s = compute(&[10, 11, 13, 29]);
    assert!(s.is_descent_image());

    // ⟨10, 11, 13⟩ itself: no min-gen in (28, 38), max apery 48 ≠ any min-gen.
    let s = compute(&[10, 11, 13]);
    assert!(!s.is_descent_image());
}

#[test]
fn test_ascent_active_iff_in_descent_image() {
    // ascent activates exactly when is_descent_image() holds, and when the
    // !is_descent branch fires (largest min-gen w in (m, f)) the residue
    // class of w has apéry w + m in the result.
    let mut tested = 0;
    let mut active = 0;
    for a in 2..=15 {
        for b in (a + 1)..=25 {
            if gcd(a, b) != 1 {
                continue;
            }
            for c in (b + 1)..=30 {
                if gcd(gcd(a, b), c) != 1 {
                    continue;
                }
                let s = compute(&[a, b, c]);
                let after = s.ascent();
                let predicted = s.is_descent_image();
                let did_change = after.gen_set != s.gen_set;
                assert_eq!(
                    did_change, predicted,
                    "ascent activity should match is_descent_image; \
                     gens={:?}, is_descent_image={}, ascent.gen_set={:?}",
                    s.gen_set, predicted, after.gen_set,
                );
                if predicted {
                    active += 1;
                    let lo = s.f.saturating_sub(s.m);
                    if let Some(w) = s
                        .gen_set
                        .iter()
                        .copied()
                        .filter(|&x| lo < x && x < s.f && x > s.m)
                        .max()
                    {
                        assert_eq!(
                            after.apery_set[w % s.m],
                            w + s.m,
                            "ascent on gens={:?}: apéry of residue {} should be {} (w+m)",
                            s.gen_set,
                            w % s.m,
                            w + s.m,
                        );
                    }
                }
                tested += 1;
            }
        }
    }
    assert!(tested > 0);
    assert!(active > 0, "sweep must exercise some descent-image cases");
}

#[test]
fn test_ascent_f_plus_m_fallback_concrete() {
    // ⟨5, 7, 23⟩: window (5, 18) has no min-gen, but f+m = 23 is one.
    // Ascent toggles 23 and recovers ⟨5, 7⟩ exactly.
    let s = compute(&[5, 7, 23]);
    let parent = s.ascent();
    assert_eq!(parent.gen_set, vec![5, 7]);

    // ⟨2, 5⟩: window (2, 3) is empty; f+m = 5 is a min-gen. The extended
    // range catches the new max apéry = 7, recovering ⟨2, 7⟩.
    let s = compute(&[2, 5]);
    let parent = s.ascent();
    assert_eq!(parent.gen_set, vec![2, 7]);
}

#[test]
fn test_apery_shift_first_when_kunz_move_is_blocked() {
    // For <6,9,20>, w₂+w₅ = 20+29 = 49 = w₁, so c_25 = 0 and the move
    // would force c_25 → -1. compute() then collapses back: 9 + 40 = 49
    // regenerates the original w₁, so the result equals the input semigroup.
    let s = compute(&[6, 9, 20]);
    let s2 = s.compute_apery_shift_first();
    assert_eq!(
        s.partial_cmp(&s2),
        Some(std::cmp::Ordering::Equal),
        "blocked Kunz move should collapse to the original semigroup",
    );
}
