//! Semigroup integration tests: every property asserted by gap/test.g and
//! gap/newtests.g. Cases mirror the GAP-verified properties:
//! e, f, m, g, c, sym, apery, pf, t. Pure-math helpers (`gcd`, `binom`)
//! are exercised separately in `math_tests.rs`.

#![allow(clippy::too_many_lines, clippy::cognitive_complexity)]

use semigroup_math::math::{
    Semigroup, binom, compute,
    creators::{arith_generators, rolf_primes, tmf_generators},
    gcd,
    matrix::{c_red, d_matrix, u_matrix, zd_vector},
    random_creators::{
        random_generators, random_matching_generators, random_primes_subset,
        random_with_multiplier_generators,
    },
};

#[test]
fn test_ord_containment() {
    // <6,9,20> ⊂ <6,9,20,43> (adding the Frobenius number as a generator)
    let s1 = compute(&[6, 9, 20]);
    let s2 = compute(&[6, 9, 20, 43]);
    assert!(s1 < s2);
    assert!(s2 > s1);

    // Equal semigroups
    let s3 = compute(&[6, 9, 20]);
    assert_eq!(s1.partial_cmp(&s3), Some(std::cmp::Ordering::Equal));

    // <3,7> and <2,7> are incomparable: 2 ∉ <3,7> and 3 ∉ <2,7>
    let a = compute(&[3, 7]);
    let b = compute(&[2, 7]);
    assert_eq!(a.partial_cmp(&b), None);
}

/// Brute-force enumeration of every level-1 numerical semigroup with given
/// multiplicity `m` (i.e. m < f < 2m). For each μ ∈ {1, …, m−1} and each
/// subset of {1, …, μ−1} (telling us which `m+r` are in S), build the
/// candidate Apéry set, run `compute`, and yield the result. Every candidate
/// gives a valid numerical semigroup (the Kunz constraints are automatic at
/// level 1, since w_r + w_s ≥ 2m + r + s dominates every right-hand side).
fn level_1_semigroups_for_m(m: usize) -> Vec<(usize, semigroup_math::math::Semigroup)> {
    let mut out = Vec::new();
    for mu in 1..m {
        // Free choices: r ∈ {1, …, μ−1}. For r > μ, w_r = m+r is forced.
        let free = mu - 1;
        for mask in 0..(1u32 << free) {
            let mut gens = vec![m];
            for r in 1..m {
                let w = if r == mu {
                    2 * m + mu
                } else if r > mu || (mask >> (r - 1)) & 1 == 1 {
                    // r > mu: forced m+r; r < mu and bit set: m+r ∈ S.
                    m + r
                } else {
                    2 * m + r
                };
                gens.push(w);
            }
            out.push((mu, compute(&gens)));
        }
    }
    out
}

#[test]
fn test_level_0_uniqueness() {
    // For every multiplicity m ≥ 2 there is exactly one level-0 numerical
    // semigroup: the ordinary semigroup S = {0} ∪ [m, ∞), generated by
    // {m, m+1, …, 2m−1}. Its invariants are f = g = μ = m − 1.
    for m in 2..=12 {
        let gens: Vec<usize> = (m..2 * m).collect();
        let s = compute(&gens);
        assert_eq!(s.m, m, "m={m}");
        assert_eq!(s.level, 0, "level should be 0 for m={m}");
        assert_eq!(s.f, m - 1, "f should be m−1 for m={m}");
        assert_eq!(s.mu, m - 1, "μ should be m−1 for m={m}");
        assert_eq!(s.g, m - 1, "g should be m−1 for m={m}");
        assert_eq!(s.gen_set, gens, "min-gens should be {{m,…,2m−1}} for m={m}");
    }
}

/// Bit-encoded enumeration helper: subset of `{1, …, μ−1}` from a mask where
/// bit `r−1` set means `r` is included.
fn mask_to_subset(mask: u32, mu: usize) -> Vec<usize> {
    (1..mu).filter(|&r| (mask >> (r - 1)) & 1 == 1).collect()
}

/// `M` is sum-avoiding for parameter `μ`: no `a, b ∈ M` (allowing `a = b`)
/// satisfy `a + b = μ`. Equivalently, `M ∩ (μ − M) = ∅`, with the additional
/// requirement that `μ/2 ∉ M` when `μ` is even.
fn is_sum_avoiding(m_set: &[usize], mu: usize) -> bool {
    for &a in m_set {
        for &b in m_set {
            if a + b == mu {
                return false;
            }
        }
    }
    true
}

/// Builds the candidate level-2 "missing" semigroup whose Apéry set is
/// `(0, …, w_r = m+r if r ∈ M, 2m+r otherwise; w_μ = 3m+μ; m+r forced for r > μ)`.
/// Returns the result of `compute` on those Apéry elements as generators
/// (plus `m`). The resulting semigroup is level 2 with the intended `(m, μ)`
/// **iff** `M` is sum-avoiding for `μ`; otherwise `2m+μ` becomes reachable
/// and the result collapses back to level 1.
fn build_level_2_missing(m: usize, mu: usize, m_set: &[usize]) -> semigroup_math::math::Semigroup {
    let mut gens = vec![m];
    for r in 1..m {
        let w = if r == mu {
            3 * m + mu
        } else if r > mu || m_set.contains(&r) {
            m + r
        } else {
            2 * m + r
        };
        gens.push(w);
    }
    compute(&gens)
}

/// Same as [`build_level_2_missing`] but with `w_μ = 2m+μ`, producing the
/// level-1 semigroup at the same `M`. Always valid (level 1 has no Kunz
/// filtering).
fn build_level_1(m: usize, mu: usize, m_set: &[usize]) -> semigroup_math::math::Semigroup {
    let mut gens = vec![m];
    for r in 1..m {
        let w = if r == mu {
            2 * m + mu
        } else if r > mu || m_set.contains(&r) {
            m + r
        } else {
            2 * m + r
        };
        gens.push(w);
    }
    compute(&gens)
}

#[test]
fn test_level_2_missing_stratification() {
    // For every (m, μ) with m ≤ 8, verify:
    //   • Per-stratum count by k = |M|:
    //       level-1 stratum has C(μ−1, k) subsets,
    //       level-2 missing stratum has C(⌊(μ−1)/2⌋, k) · 2^k subsets,
    //   • The lift M ↦ M takes a level-1 with sum-avoiding M to a level-2
    //     "missing" with the same M, raising genus by exactly 1.
    //   • Non-sum-avoiding M's "lift" to a level-1 (collapse), not a
    //     level-2.
    for m in 2..=8 {
        for mu in 1..m {
            let mut l1_by_k: Vec<usize> = vec![0; mu];
            let mut l2_missing_by_k: Vec<usize> = vec![0; mu];
            for mask in 0..(1u32 << (mu - 1)) {
                let m_set = mask_to_subset(mask, mu);
                let k = m_set.len();
                l1_by_k[k] += 1;

                let s1 = build_level_1(m, mu, &m_set);
                assert_eq!(s1.m, m, "(m={m}, μ={mu}, M={m_set:?})");
                assert_eq!(s1.mu, mu, "(m={m}, μ={mu}, M={m_set:?})");
                assert_eq!(s1.level, 1, "(m={m}, μ={mu}, M={m_set:?})");
                assert_eq!(s1.g, m + mu - 1 - k, "level-1 genus formula");

                let s2 = build_level_2_missing(m, mu, &m_set);
                if is_sum_avoiding(&m_set, mu) {
                    l2_missing_by_k[k] += 1;
                    assert_eq!(s2.m, m, "(m={m}, μ={mu}, M={m_set:?})");
                    assert_eq!(s2.mu, mu, "(m={m}, μ={mu}, M={m_set:?})");
                    assert_eq!(s2.level, 2, "(m={m}, μ={mu}, M={m_set:?})");
                    assert_eq!(s2.g, m + mu - k, "missing genus formula");
                    assert_eq!(s2.g, s1.g + 1, "genus shift l=1 → l=2 missing must be +1",);
                } else {
                    // Bad pair in M: 2m+μ reduces, w_μ collapses to 2m+μ,
                    // and the result lands back in level 1 (not level 2).
                    assert_ne!(
                        s2.level, 2,
                        "non-sum-avoiding M must not lift to level 2: m={m}, μ={mu}, M={m_set:?}",
                    );
                }
            }

            // Closed forms.
            let half = (mu - 1) / 2;
            for k in 0..mu {
                assert_eq!(
                    l1_by_k[k],
                    binom(mu - 1, k).expect("small"),
                    "level-1 stratum (m={m}, μ={mu}, k={k})",
                );
                let predicted_missing = if k <= half {
                    binom(half, k).expect("small") * (1usize << k)
                } else {
                    0
                };
                assert_eq!(
                    l2_missing_by_k[k], predicted_missing,
                    "level-2 missing stratum (m={m}, μ={mu}, k={k})",
                );
            }

            // Sum totals: level-1 = 2^(μ−1), level-2 missing = 3^⌊(μ−1)/2⌋.
            assert_eq!(l1_by_k.iter().sum::<usize>(), 1usize << (mu - 1));
            assert_eq!(
                l2_missing_by_k.iter().sum::<usize>(),
                3usize.pow(half as u32)
            );
        }
    }
}

#[test]
fn test_level_1_count_formula() {
    // N(g, l=1, m, μ) = C(μ−1, m + μ − 1 − g) for g ∈ {m, …, m+μ−1};
    // zero outside that range. Verified by brute force.
    for m in 2..=8 {
        let mut actual: std::collections::HashMap<(usize, usize), usize> =
            std::collections::HashMap::new();
        for (mu, s) in level_1_semigroups_for_m(m) {
            assert_eq!(s.m, m, "m mismatch (m={m}, μ={mu})");
            assert_eq!(s.level, 1, "level mismatch (m={m}, μ={mu})");
            assert_eq!(s.mu, mu, "μ mismatch (m={m})");
            *actual.entry((s.g, mu)).or_insert(0) += 1;
        }
        // Compare against the closed form for every (g, μ) we observed.
        for ((g, mu), &n) in &actual {
            let k = m + mu - 1 - g;
            let predicted = if k < *mu {
                binom(mu - 1, k).expect("small inputs cannot overflow")
            } else {
                0
            };
            assert_eq!(
                n, predicted,
                "N(g={g}, l=1, m={m}, μ={mu}): predicted {predicted}, actual {n}",
            );
        }
        // And verify the sum: N(g, l=1, m) = Σ_μ N(g, l=1, m, μ).
        let mut by_g: std::collections::HashMap<usize, usize> = std::collections::HashMap::new();
        for ((g, _), n) in &actual {
            *by_g.entry(*g).or_insert(0) += n;
        }
        for (&g, &actual_total) in &by_g {
            let predicted_total: usize = (1..m)
                .map(|mu| {
                    if g >= m && g < m + mu {
                        binom(mu - 1, m + mu - 1 - g).expect("small")
                    } else {
                        0
                    }
                })
                .sum();
            assert_eq!(
                actual_total, predicted_total,
                "N(g={g}, l=1, m={m}): predicted {predicted_total}, actual {actual_total}",
            );
        }
    }
}

/// Compute the semigroup from `gens` and assert every GAP-verified property.
///
/// Parameters match the GAP assertions in gap/test.g:
/// `e` = embedding dimension, `f` = Frobenius number, `m` = multiplicity,
/// `g` = genus, `c` = sigma (= 1+f−g), `sym` = IsSymmetric,
/// `apery` = AperyList w.r.t. m (indexed 0..m), `pf` = PseudoFrobenius set,
/// `t` = type.
#[allow(clippy::too_many_arguments)]
fn check(
    gens: &[usize],
    e: usize,
    f: usize,
    m: usize,
    g: usize,
    c: usize,
    sym: bool,
    apery: &[usize],
    pf: &[usize],
    t: usize,
) {
    let s = compute(gens);
    assert_eq!(s.f + s.m, s.apery_set[s.mu], "max apery");
    for i in 0..s.m {
        assert_eq!(s.diag(i) + s.apery_set[i], s.f + s.m + s.r, "diag {i}");
    }
    assert_eq!(s.diag(s.mu), s.r);
    assert_eq!(s.e, e, "e     for {gens:?}");
    assert_eq!(s.f, f, "f     for {gens:?}");
    assert_eq!(s.m, m, "m     for {gens:?}");
    assert_eq!(s.g, g, "genus for {gens:?}");
    assert_eq!(s.sigma, c, "c     for {gens:?}");
    assert_eq!(s.is_symmetric, sym, "sym   for {gens:?}");
    assert_eq!(s.apery_set.as_slice(), apery, "apery for {gens:?}");
    let mut actual_pf = s.pf_set.clone();
    actual_pf.sort_unstable();
    let mut expected_pf = pf.to_vec();
    expected_pf.sort_unstable();
    assert_eq!(actual_pf, expected_pf, "pf    for {gens:?}");
    assert_eq!(s.t, t, "type  for {gens:?}");
    assert_eq!(f + m, *apery.iter().max().unwrap(), "f ist max apery -m");
    assert_eq!(s.sigma + s.r, s.g, "g ist sigma + r");
    assert_eq!(s.f + s.r + 2, 2 * s.g + 1, "f+r+2=2g+1");
    assert_eq!(
        s.ae,
        *s.gen_set.iter().max().unwrap(),
        "maximum for {gens:?}"
    );
    assert_eq!(t, s.t, "t for {gens:?}");
    assert_eq!(t, s.pf_set.len(), "type is length pf_set");
    let mut semi_pf = s.pf_set.clone();
    semi_pf.sort_unstable();
    assert_eq!(
        pf.to_vec(),
        semi_pf,
        "pseudo-frobenius for {gens:?} and {m}"
    );
    let aps: usize = s.apery_set.iter().sum();
    assert_eq!(aps, s.apery_sum);
    // todo 82 / 85
    // rl < t whenever t > 0: every gap counted by rl is pseudo-Frobenius and
    // strictly below f, while f itself is always pseudo-Frobenius and never
    // counted by rl. So PF ⊇ {rl-counted gaps} ⊔ {f}, hence rl + 1 ≤ t.
    if s.t > 0 {
        assert!(s.rl < s.t, "rl = {}, t = {} for {gens:?}", s.rl, s.t);
    } else {
        assert_eq!(s.rl, 0);
    }
    assert!(s.t <= s.r + 1);
    assert!(s.es <= s.e);
    // todo 86: descent(ascent(S)) == S iff ascent enters its "f+m branch":
    // f+m is a min-gen AND no min-gen lies in (m, f) ∩ (f-m, f). The window
    // matches Semigroup::ascent's own filter (which excludes g = m so that
    // the trivial branch is not taken).
    let no_large_mingen = !s
        .gen_set
        .iter()
        .any(|&g| g > s.m && g < s.f && g + s.m > s.f);
    let fpm_is_mingen = s.gen_set.contains(&(s.f + s.m));
    if no_large_mingen && fpm_is_mingen {
        assert_eq!(s, s.ascent().descent(), "up-down identity for {gens:?}");
    }
    test_up_downs(&s);
    // Selmer identity: one·U(m)·c₁ = m·g + m·(m−1)/2
    let dim = m - 1;
    let u_mat = u_matrix(m);
    let cr = c_red(&s);
    let one_u: Vec<i64> = (0..dim)
        .map(|j| (0..dim).map(|a| u_mat[(a, j)]).sum())
        .collect();
    #[allow(clippy::cast_possible_wrap)]
    let c1: Vec<i64> = (0..dim).map(|i| cr[(i, 0)] as i64).collect();
    let scalar: i64 = one_u.iter().zip(c1.iter()).map(|(&u, &c)| u * c).sum();
    #[allow(clippy::cast_possible_wrap)]
    let apery_sum_selmer = (m * g + m * (m - 1) / 2) as i64;
    assert_eq!(scalar, apery_sum_selmer, "Selmer identity for {gens:?}");

    // zd(m)·c₁ = f + m + r = 2g + m − 1
    let zd = zd_vector(m);
    #[allow(clippy::cast_possible_wrap)]
    let zd_dot: i64 = (0..dim).map(|b| zd[(0, b)] * c1[b]).sum();
    #[allow(clippy::cast_possible_wrap)]
    let f_plus_m_plus_r = (f + m + s.r) as i64;
    #[allow(clippy::cast_possible_wrap)]
    let two_g_plus_m_minus_1 = (2 * g + m - 1) as i64;
    assert_eq!(zd_dot, f_plus_m_plus_r, "zd·c₁ = f+m+r for {gens:?}");
    assert_eq!(zd_dot, two_g_plus_m_minus_1, "zd·c₁ = 2g+m−1 for {gens:?}");

    // wᵢ + dᵢ = f + m + r for all i ∈ {1, …, m−1}
    let d_mat = d_matrix(m);
    for i in 1..=dim {
        #[allow(clippy::cast_possible_wrap)]
        let di: i64 = (0..dim).map(|b| d_mat[(i - 1, b)] * c1[b]).sum();
        #[allow(clippy::cast_possible_wrap)]
        let wi = s.apery_set[i] as i64;
        assert_eq!(
            wi + di,
            f_plus_m_plus_r,
            "w_{i} + d_{i} = f+m+r for {gens:?}"
        );
    }

    // level: level·m < f < (level+1)·m. f mod m = μ ≥ 1 (m ∈ S, f ∉ S),
    // so f never equals k·m and the strict inequality always holds.
    assert!(
        s.level * m < f && f < (s.level + 1) * m,
        "level invariant for {gens:?}: level={} m={} f={}",
        s.level,
        m,
        f,
    );

    // deep ⇔ every Kunz quotient q_i = (w_i − i)/m ≥ 2 (i ∈ 1..m).
    let all_q_ge_2 = (1..m).all(|i| (s.apery_set[i] - i) / m >= 2);
    assert_eq!(s.deep, all_q_ge_2, "deep ↔ q_i ≥ 2 for {gens:?}",);

    // Symmetric ⇒ r = 0 and genus = sporadics. (Every gap x has f − x ∈ S,
    // so no gap x has f − x as a gap.)
    if s.is_symmetric {
        assert_eq!(s.r, 0, "symmetric ⇒ r=0 for {gens:?}");
        assert_eq!(s.g, s.sigma, "symmetric ⇒ g = #sporadics for {gens:?}",);
    }

    // For t > 1, let L = max(PF(S) \ {f}). Then:
    //   • if f is odd, 2L ∈ S;
    //   • if f is even, 2L ∈ S or 2L = f (the boundary case where L = f/2).
    if s.t > 1 {
        let l = s
            .pf_set
            .iter()
            .copied()
            .filter(|&p| p != s.f)
            .max()
            .expect("t > 1 guarantees a pseudo-Frobenius element distinct from f");
        let two_l = 2 * l;
        if s.f.is_multiple_of(2) {
            assert!(
                s.element(two_l) || two_l == s.f,
                "2L ∈ S ∪ {{f}} where L = max(PF\\{{f}}) for {gens:?}: L={l}, 2L={two_l}, f={}",
                s.f,
            );
        } else {
            assert!(
                s.element(two_l),
                "2L ∈ S where L = max(PF\\{{f}}) for {gens:?} (f odd): L={l}, 2L={two_l}",
            );
        }
    }

    // Almost-symmetric ⇒ ra = r, PF \ {f} = reflected gaps, and f + t = 2g.
    // The symmetric case is included (t = 1, both sides empty).
    if s.is_almost_symmetric {
        assert_eq!(s.ra, s.r, "almost-symmetric ⇒ ra=r for {gens:?}");
        assert_eq!(s.f + s.t, 2 * s.g, "almost-symmetric ⇒ f+t=2g for {gens:?}",);
        let mut pf_minus_f: Vec<usize> = s.pf_set.iter().copied().filter(|&p| p != s.f).collect();
        pf_minus_f.sort_unstable();
        assert_eq!(
            pf_minus_f,
            s.blob(),
            "almost-symmetric ⇒ PF\\{{f}} = reflected gaps for {gens:?}",
        );
    }
}
/// Property checks for one-step descent / ascent.
///
/// For every non-trivial residue class `i ∈ 1..m`, looks at `w = a_i`
/// (the Apéry element with residue `i`) and runs up to four assertion
/// blocks. The four "legs" mirror the visible-arrow conditions in
/// `combined_table::arrow_cell`:
///
/// 1. **Descent of an outer Apéry** (`w > f` and `f > m`).
///    `w − m` is a gap; toggling it adds exactly one element to `S`.
///    The pair `(w − m, f − (w − m))` is a reflected-gap pair when
///    `w < f + m`, hence `r` drops by 2 and `sigma` rises by 1.
///    When `w == f + m` and `V(S) = {f−m+1, …, f−1} ⊆ S`, descent
///    collapses the conductor by `m`, raising `r` by `m − 2` and
///    raising `sigma` by `m − 1` (one new element `f` plus the
///    `m − 1` elements of `V` already in `S` reaching the new conductor).
/// 2. **Ascent of a "large" minimal generator** (`w ∈ gen_set` with
///    `f − m < w < f`). Removing `w` makes `(w, f − w)` a new
///    reflected-gap pair, so `r += 2` and `sigma -= 1`; the new
///    Apéry in residue `i` becomes `w + m`.
/// 3. **Ascent of the max Apéry** (`w == f + m ∈ gen_set`). The new
///    `a_μ` jumps by `rho · m`, where `rho = rho(S)`; the size and
///    `r` changes follow from that jump.
///
/// All four legs are exercised on every fixture in `check()`.
fn test_up_downs(s: &Semigroup) {
    if s.m == 1 {
        return;
    }
    for i in 1..s.m {
        let w = s.apery_set[i];

        // Descent: w-m is a gap; adding it lifts the membership of w-m.
        if w > s.f && s.f > s.m {
            assert!(!s.element(w - s.m));
            assert!(w <= s.f + s.m);
            assert!(
                w == s.f + s.m || s.is_reflected_gap(w - s.m),
                "reflected {w} at {i}"
            );
            let down = s.toggle(w - s.m);
            assert_eq!(down.g + 1, s.g);
            //find failed testcase assert_eq!(down.rho(),s.rho()+1);
            if w == s.f + s.m && s.v_in_s() {
                assert_eq!(down.r + 2, s.r + s.m, "r change w==f+m for i={i}");
                assert_eq!(down.sigma + s.m, s.sigma + 1, "sigma");
            }
            if w < s.f + s.m {
                assert_eq!(down.r + 2, s.r, "r change w<f+m for i={i}");
                assert_eq!(down.sigma, s.sigma + 1, "sigma");
            }
        }

        // Ascent: w must already be a minimal generator.
        if s.gen_set.contains(&w) {
            let up = s.toggle(w);
            if w < s.f && w + s.m > s.f {
                assert_eq!(up.g, s.g + 1, "removing atom generates gap for {i} and {w}");
                assert!(up.apery_set.contains(&(w + s.m)));
                assert_eq!(up.apery_set[i], w + s.m);
                assert_eq!(up.r, s.r + 2, "r change w<f for i={i}");
                assert_eq!(up.sigma + 1, s.sigma);
            }
            // Skip m == 2: {1..m-1}\{μ} = ∅, so the ρ-formula is vacuous and
            // removing the lone non-multiplicity atom collapses the semigroup
            // to ℕ via gcd-normalisation (e.g. ⟨2, 5⟩ ⇒ ⟨2⟩ ⇒ ℕ). The "ascent
            // of w_μ" structural claim assumes another residue class survives.
            if w == s.f + s.m && s.m >= 3 {
                let rho = s.rho();
                assert_eq!(
                    up.g,
                    s.g + rho,
                    "removing atom generates rho gap for {i} and {w}"
                );
                assert!(up.apery_set.contains(&(w + rho * s.m)));
                assert_eq!(up.apery_set[i], w + rho * s.m);
                assert_eq!(up.r + rho * (s.m - 2), s.r, "r change w==f+m for i={i}");
                assert_eq!(
                    up.sigma,
                    rho * (s.m - 1) + s.sigma,
                    "sigma change w==f+m for i={i}"
                );
            }
        }
    }
}

// ── CSV-driven fixtures ───────────────────────────────────────────────────
//
// Every per-semigroup `check(...)` case (originally ~108 hand-written
// `#[test] fn test_<gens>()` wrappers transcribed from gap/test.g and
// gap/newtests.g) is now sourced from `tests/data/check_fixtures.csv`.
// Columns: `gens;e;f;m;g;c;sym;apery;pf;t`, with inner arrays
// space-separated. The single `#[test] fn test_csv_fixtures` below
// drives `check()` once per row; assertion messages embed `gens:?` so a
// failure still pinpoints the offending row.

fn parse_usize_list(s: &str) -> Vec<usize> {
    s.split_ascii_whitespace()
        .map(|t| {
            t.parse::<usize>()
                .unwrap_or_else(|e| panic!("non-usize token {t:?}: {e}"))
        })
        .collect()
}

#[test]
fn test_csv_fixtures() {
    let csv = include_str!("data/check_fixtures.csv");
    let mut lines = csv.lines();
    let header = lines.next().expect("CSV has a header");
    assert_eq!(header, "gens;e;f;m;g;c;sym;apery;pf;t", "CSV header drift");

    let mut count = 0usize;
    for (idx, raw) in lines.enumerate() {
        if raw.trim().is_empty() {
            continue;
        }
        let cols: Vec<&str> = raw.split(';').collect();
        assert_eq!(cols.len(), 10, "row {idx} has {} cols, want 10", cols.len());
        let gens = parse_usize_list(cols[0]);
        let e: usize = cols[1].parse().expect("e usize");
        let f: usize = cols[2].parse().expect("f usize");
        let m: usize = cols[3].parse().expect("m usize");
        let g: usize = cols[4].parse().expect("g usize");
        let c: usize = cols[5].parse().expect("c usize");
        let sym: bool = match cols[6] {
            "true" => true,
            "false" => false,
            other => panic!("row {idx} sym must be true/false, got {other:?}"),
        };
        let apery = parse_usize_list(cols[7]);
        let pf = parse_usize_list(cols[8]);
        let t: usize = cols[9].parse().expect("t usize");
        check(&gens, e, f, m, g, c, sym, &apery, &pf, t);
        count += 1;
    }
    assert!(count >= 100, "expected ≥100 fixtures, got {count}");
}

// ── Canonical ideal K(S) ──────────────────────────────────────────────────────

#[test]
fn test_canonical_ideal_generators() {
    // gen(K(S)) = {f − p : p ∈ PF(S), p ≠ f} for non-symmetric semigroups.
    let cases: &[(&[usize], &[usize])] = &[
        // ⟨6, 13, 17, 27⟩: f=28, PF={20,21,28}  →  K = ⟨7, 8⟩
        (&[6, 13, 17, 27], &[7, 8]),
        // ⟨12, 14, 19, 77⟩: f=65, PF={58,63,65}  →  K = ⟨2, 7⟩
        (&[12, 14, 19, 77], &[2, 7]),
    ];
    for &(gens, expected_k_gens) in cases {
        let s = compute(gens);
        let k = s.canonical_ideal();

        // Verify formula: gen(K) = {f − p : p ∈ PF, p ≠ f}, sorted.
        let mut from_formula: Vec<usize> = s
            .pf_set
            .iter()
            .filter(|&&p| p != s.f)
            .map(|&p| s.f - p)
            .collect();
        from_formula.sort_unstable();
        let mut actual = k.gen_set.clone();
        actual.sort_unstable();
        assert_eq!(
            actual, from_formula,
            "gen(K(S)) = {{f−p : p ∈ PF(S)\\{{f}}}} for {gens:?}"
        );

        // Verify against the known expected generators.
        assert_eq!(actual, expected_k_gens, "K(S) generators for {gens:?}");
    }
}

#[test]
fn test_canonical_ideal_containment() {
    // S ⊊ K(S) when the generators of K reach below m(S).
    // ⟨12, 14, 19, 77⟩: K = ⟨2, 7⟩; every element of S is ≥ 12 > f(K)=5,
    // so S ⊆ K, and 2 ∈ K \ S, giving S ⊊ K.
    let s = compute(&[12, 14, 19, 77]);
    let k = s.canonical_ideal();
    assert!(s < k, "⟨12,14,19,77⟩ ⊊ K(S)");
}

#[test]
fn test_canonical_ideal_symmetric() {
    // For symmetric semigroups, K(S) = S.
    for gens in [
        [6, 9, 20].as_slice(), // symmetric, f=43
        [5, 7].as_slice(),     // symmetric, f=23
        [2, 11].as_slice(),    // symmetric, f=9
    ] {
        let s = compute(gens);
        assert!(s.is_symmetric, "{gens:?} should be symmetric");
        let k = s.canonical_ideal();
        assert_eq!(
            s.partial_cmp(&k),
            Some(std::cmp::Ordering::Equal),
            "K(S) = S for symmetric {gens:?}"
        );
    }
}

#[test]
fn test_u_times_two_ones_is_m_zero_zero() {
    // U(m) · (2, 1, 1, …, 1)ᵀ = (m, 0, 0, …, 0)ᵀ for every m ≥ 2.
    // This is the identity that makes `compute_apery_shift_first` correspond
    // to a Kunz-cone neighbour (row 1 of C shifted by (2, 1, …, 1)).
    for m in 2..=12 {
        let n = m - 1;
        let u = u_matrix(m);
        let mut v = vec![1i64; n];
        v[0] = 2;
        let mut prod = vec![0i64; n];
        for i in 0..n {
            for (j, vj) in v.iter().enumerate().take(n) {
                prod[i] += u[(i, j)] * vj;
            }
        }
        let mut expected = vec![0i64; n];
        expected[0] = i64::try_from(m).expect("m fits in i64");
        assert_eq!(prod, expected, "U({m})·(2,1,…,1)ᵀ ≠ (m,0,…,0)ᵀ");
    }
}

#[test]
fn test_apery_shift_first_when_kunz_move_is_valid() {
    // When every antidiagonal Kunz entry c_{a,b} with (a+b) ≡ 1 (mod m) and
    // a,b ≠ 1 is ≥ 1, the move w₁ → w₁ + m is a valid Kunz-cone neighbour
    // and the result has multiplicity m and Apéry (0, w₁+m, w₂, …, w_{m-1}).
    // <3,7,11>: m=3, Ap=(0,7,11), c_22 = (11+11-7)/3 = 5 ≥ 1 → valid.
    // <4,5,6,7>: m=4, Ap=(0,5,6,7), c_23 = (6+7-5)/4 = 2 ≥ 1 → valid.
    for gens in [[3, 7, 11].as_slice(), [4, 5, 6, 7].as_slice()] {
        let s = compute(gens);
        let s2 = s.compute_apery_shift_first();
        assert_eq!(s2.m, s.m, "multiplicity preserved for {gens:?}");
        let mut want = s.apery_set.clone();
        want[1] += s.m;
        assert_eq!(
            s2.apery_set, want,
            "Apéry shift for {gens:?}: got {:?}, want {:?}",
            s2.apery_set, want,
        );
    }
}

#[test]
fn test_apery_shift_first_changes_s_iff_w1_is_minimal_generator() {
    // Equivalence: the move w₁ → w₁+m yields a different semigroup iff w₁
    // is a minimal generator. (When w₁ ∉ gen_set, w₁ = w_a + w_b for some
    // a,b ≠ 1 with (a+b)≡1 mod m, so c_{a,b} = 0, so the Kunz move forces
    // c_{a,b} = -1 — and compute() recovers the original w₁ as that sum.)
    for gens in [
        [3, 7, 11].as_slice(),   // w₁ = 7  ∈ gen_set → moves
        [4, 5, 6, 7].as_slice(), // w₁ = 5  ∈ gen_set → moves
        [6, 9, 20].as_slice(),   // w₁ = 49 ∉ gen_set → no-op
        [5, 6, 8].as_slice(),    // various
        [7, 11, 13, 17, 19].as_slice(),
        [10, 14, 21].as_slice(),
    ] {
        let s = compute(gens);
        let w1 = s.apery_set[1];
        let w1_is_gen = s.gen_set.contains(&w1);
        let s2 = s.compute_apery_shift_first();
        let changed = s.partial_cmp(&s2) != Some(std::cmp::Ordering::Equal);
        assert_eq!(
            changed, w1_is_gen,
            "for {gens:?}: w₁={w1}, w1_is_gen={w1_is_gen}, changed={changed}",
        );
    }
}

/// Brute-force count of reflected gaps `x` (gap with `f − x` also a gap)
/// grouped by residue class mod `m`. Used to cross-check `Semigroup::r_i`.
fn brute_force_ri(sg: &semigroup_math::math::Semigroup) -> Vec<usize> {
    let mut counts = vec![0usize; sg.m];
    if sg.f == 0 {
        return counts;
    }
    for x in 1..sg.f {
        if sg.is_gap(x) && sg.is_gap(sg.f - x) {
            counts[x % sg.m] += 1;
        }
    }
    counts
}

#[test]
fn test_r_i_matches_brute_force() {
    // Spans several m values and mu values, and includes <4,7,9,10> where
    // r_1 = 2 (the case the underflow fix is meant to handle: mu = 2, i = 3).
    let cases: &[&[usize]] = &[
        &[3, 5, 7],
        &[3, 7, 11],
        &[3, 10, 11],
        &[4, 5, 6, 7],
        &[4, 7, 9, 10],
        &[5, 6, 7, 8, 9],
        &[5, 7, 9],
        &[6, 9, 20],
    ];
    for gens in cases {
        let sg = compute(gens);
        let expected = brute_force_ri(&sg);
        for (i, &want) in expected.iter().enumerate().take(sg.m).skip(1) {
            assert_eq!(
                sg.r_i(i),
                want,
                "r_{i} mismatch for {gens:?} (m={}, mu={})",
                sg.m,
                sg.mu,
            );
        }
        assert_eq!(sg.r_i(0), 0);
        assert_eq!(sg.r_i(sg.m), 0);
    }
}

#[test]
fn test_rho() {
    // rho() excludes i = μ (where r_μ = 0 by construction), so on a fresh
    // semigroup it picks up the smallest *non-trivial* count.

    // <4, 7, 9, 10>: f=6, μ=2. r_1=2, r_2=0, r_3=1 → min over {1,3} = 1.
    let sg = compute(&[4, 7, 9, 10]);
    assert_eq!(sg.r_i(1), 2);
    assert_eq!(sg.r_i(2), 0);
    assert_eq!(sg.r_i(3), 1);
    assert_eq!(sg.rho(), 1);

    // <3, 5, 7>: f=4, μ=1. r_1=0, r_2=1 → min over {2} = 1.
    let sg = compute(&[3, 5, 7]);
    assert_eq!(sg.rho(), 1);

    // <3, 10, 11>: f=8, μ=2. r_1=3, r_2=0 → min over {1} = 3.
    let sg = compute(&[3, 10, 11]);
    assert_eq!(sg.rho(), 3);

    // m = 2: 1..m \ {μ} is empty (μ = 1 since f is odd) → rho = 0.
    // <2, 5>: f=3, μ=1.
    let sg = compute(&[2, 5]);
    assert_eq!(sg.mu, 1);
    assert_eq!(sg.rho(), 0);
}

#[test]
fn test_is_deep() {
    // Helper: checks that `deep` matches whether all {m+1,...,2m-1} are gaps.
    let check_deep = |sg: &semigroup_math::math::Semigroup| {
        let all_gaps = (1..sg.m).all(|i| sg.is_gap(sg.m + i));
        assert_eq!(
            sg.deep, all_gaps,
            "deep disagrees with direct gap check for gens={:?} m={} f={}",
            sg.gen_set, sg.m, sg.f
        );
    };

    // <3, 7, 11>: m=3, f=8. {4, 5} are gaps (apery=[0,7,11]). deep=true.
    let sg = compute(&[3, 7, 11]);
    assert!(sg.deep);
    assert!(sg.is_gap(4) && sg.is_gap(5));
    check_deep(&sg);

    // <3, 4>: m=3, 4 ∈ S (generator). {4,5}: 4 in S → not deep.
    let sg = compute(&[3, 4]);
    assert!(!sg.deep);
    assert!(!sg.is_gap(4));
    check_deep(&sg);

    // <3, 5>: m=3, 5 ∈ S (generator). {4,5}: 5 in S → not deep.
    let sg = compute(&[3, 5]);
    assert!(!sg.deep);
    assert!(!sg.is_gap(5));
    check_deep(&sg);

    // <5, 11, 12, 13, 14>: m=5. {6,7,8,9} are all gaps (apery=[0,11,12,13,14]). deep=true.
    let sg = compute(&[5, 11, 12, 13, 14]);
    assert!(sg.deep);
    for i in 1..sg.m {
        assert!(sg.is_gap(sg.m + i), "expected gap at {}", sg.m + i);
    }
    check_deep(&sg);

    // <2, 3>: m=2. {3} is in S → not deep.
    let sg = compute(&[2, 3]);
    assert!(!sg.deep);
    assert!(!sg.is_gap(3));
    check_deep(&sg);

    // <2, 5>: m=2. {3} — 3 mod 2 = 1, apery[1]=5 > 3, so 3 is a gap. deep=true.
    let sg = compute(&[2, 5]);
    assert!(sg.deep);
    assert!(sg.is_gap(3));
    check_deep(&sg);
}

#[test]
fn test_fast_descent_drops_f_by_m_and_preserves_mu() {
    // Specification: whenever f ≥ 2m the result of fast_descent has μ unchanged
    // and Frobenius number exactly old f − m.

    // 1. Hand-picked: <10,11,13> has f=38, m=10, μ=8 and apéry
    //    [0,11,22,13,24,35,26,37,48,39]. a_9 = 39 ∈ (f, f+m), so naïvely
    //    adding only f would land at f=29 with μ=9.
    let s = compute(&[10, 11, 13]);
    assert_eq!((s.f, s.m, s.mu), (38, 10, 8));
    let t = s.fast_descent();
    assert_eq!(t.f, s.f - s.m);
    assert_eq!(t.mu, s.mu);

    // 2. <5,7> has f=23, m=5, μ=3 and apéry [0,21,7,28,14]: the only Apéry
    //    element ≥ f is 28 = f+m.
    let s = compute(&[5, 7]);
    assert_eq!((s.f, s.m, s.mu), (23, 5, 3));
    let t = s.fast_descent();
    assert_eq!(t.f, s.f - s.m);
    assert_eq!(t.mu, s.mu);

    // 3. Sweep over a range of generator pairs/triples and assert the property
    //    on every semigroup with f ≥ 2m. This would catch the previous bug,
    //    which adds the Apéry elements themselves (no-ops) instead of x−m.
    let mut sweep_count = 0;
    for a in 3..=12 {
        for b in (a + 1)..=20 {
            if gcd(a, b) != 1 {
                continue;
            }
            for c in (b + 1)..=25 {
                if gcd(gcd(a, b), c) != 1 {
                    continue;
                }
                let s = compute(&[a, b, c]);
                if s.f < 2 * s.m {
                    continue;
                }
                let t = s.fast_descent();
                assert_eq!(
                    t.f,
                    s.f - s.m,
                    "fast_descent f for gens={:?}: expected {}, got {}",
                    s.gen_set,
                    s.f - s.m,
                    t.f,
                );
                assert_eq!(
                    t.mu, s.mu,
                    "fast_descent mu for gens={:?}: expected {}, got {}",
                    s.gen_set, s.mu, t.mu,
                );
                sweep_count += 1;
            }
        }
    }
    assert!(sweep_count > 0, "sweep must exercise at least one case");
}

#[test]
fn test_fast_descent_returns_self_when_f_lt_2m() {
    // S = ℕ: m=1, f=0. fast_descent must not touch the generator set.
    let s = compute(&[1]);
    assert_eq!(s.fast_descent().gen_set, s.gen_set);

    // Terminal range m < f < 2m: <3,4> has m=3, f=5, so 5 < 6 = 2m.
    let s = compute(&[3, 4]);
    assert!(s.f < 2 * s.m);
    assert_eq!(s.fast_descent().gen_set, s.gen_set);
}

#[test]
fn test_creators_tmf() {
    assert_eq!(tmf_generators(3, 6), vec![3, 7, 8, 9]);

    // T(4, 7): ⟨4, 8, 9, 10, 11⟩; 8 reduces to 4+4 so minimal gens are
    // ⟨4, 9, 10, 11⟩, Apéry [0, 9, 10, 11], f = 11 − 4 = 7.
    let s = compute(&tmf_generators(4, 7));
    assert_eq!(s.m, 4);
    assert_eq!(s.f, 7);
    assert_eq!(s.apery_set, vec![0, 9, 10, 11]);
}

#[test]
fn test_creators_arith() {
    assert_eq!(arith_generators(3, 2, 3), vec![3, 5, 7, 9]);
    // 9 = 3+3+3 is reducible so minimal gens are ⟨3, 5, 7⟩.
    let s = compute(&arith_generators(3, 2, 3));
    assert_eq!(s.gen_set, vec![3, 5, 7]);

    // Single generator m,d=1,n=0 → ⟨m⟩ which compute() rescales to ⟨1⟩ = ℕ.
    let s = compute(&arith_generators(5, 0, 0));
    assert_eq!(s.m, 1);
}

#[test]
fn test_creators_rolf_primes() {
    // p_1 = 2; primes 2 ≤ p ≤ 10.
    assert_eq!(rolf_primes(1), vec![2, 3, 5, 7]);
    // p_3 = 5; primes 5 ≤ p ≤ 25.
    assert_eq!(rolf_primes(3), vec![5, 7, 11, 13, 17, 19, 23]);
    // n=0 clamps to n=1.
    assert_eq!(rolf_primes(0), rolf_primes(1));
}

#[test]
fn test_random_creators_basic_shape() {
    let nums = random_generators();
    assert_eq!(nums.len(), 8);
    assert!(nums.iter().all(|&x| (10..=100).contains(&x)));

    // multiplier-extended list yields a valid semigroup.
    let s = compute(&random_with_multiplier_generators(2));
    assert!(s.m >= 1);

    let primes = random_primes_subset();
    assert!((4..=8).contains(&primes.len()));
    assert!(primes.windows(2).all(|w| w[0] < w[1]));
}

#[test]
fn test_random_creators_predicate_postconditions() {
    let g =
        random_matching_generators(|s| s.is_symmetric).expect("random_symmetric should succeed");
    assert!(compute(&g).is_symmetric);

    let g =
        random_matching_generators(|s| s.r == 1).expect("random_pseudo_symmetric should succeed");
    assert_eq!(compute(&g).r, 1);

    let g = random_matching_generators(|s| s.is_almost_symmetric && s.r >= 2)
        .expect("random_almost_symmetric should succeed");
    let s = compute(&g);
    assert!(s.is_almost_symmetric);
    assert!(s.r >= 2);
}

#[test]
fn test_fast_descent_changes_r_by_exact_amount() {
    // fast_descent (when f ≥ 2m) folds k = #(apéry ∈ (f, f+m)) per-step
    // "add x−m" removals (each Δr = −2) plus one "add f" step
    // (Δr = m − 2) into a single closure. Net: Δr = (m − 2) − 2·k.
    let mut tested = 0;
    for a in 2..=15 {
        for b in (a + 1)..=25 {
            if gcd(a, b) != 1 {
                continue;
            }
            for c in (b + 1)..=30 {
                if gcd(gcd(a, b), c) != 1 {
                    continue;
                }
                let s = compute(&[a, b, c]);
                if s.f < 2 * s.m {
                    continue;
                }

                let after = s.fast_descent();
                let dr = isize::try_from(after.r).unwrap() - isize::try_from(s.r).unwrap();
                let k = s
                    .apery_set
                    .iter()
                    .filter(|&&x| s.f < x && x < s.f + s.m)
                    .count();
                let expected = isize::try_from(s.m).unwrap() - 2 - 2 * isize::try_from(k).unwrap();
                assert_eq!(
                    dr, expected,
                    "fast_descent on gens={:?} (m={}, f={}, k={}): \
                     expected Δr = {}, got {} (r: {} → {})",
                    s.gen_set, s.m, s.f, k, expected, dr, s.r, after.r,
                );
                tested += 1;
            }
        }
    }
    assert!(tested > 0, "sweep must exercise at least one case");
}

#[test]
fn test_ascent_f_plus_m_branch_concrete() {
    // Removing f+m as an atom is now folded into the same loop body as
    // the "k·a in V(S)" cases (matched by `k·a == f+m`, taken when the
    // winning atom equals f+m).
    //
    // ⟨5, 7, 23⟩: V(S) = (5, 18) has no atom; f+m = 23 wins at k=1.
    // Ascent removes 23 and recovers ⟨5, 7⟩ exactly.
    let s = compute(&[5, 7, 23]);
    let parent = s.ascent();
    assert_eq!(parent.gen_set, vec![5, 7]);

    // ⟨2, 5⟩: V(S) = (2, 3) is empty; f+m = 5 wins at k=1. The extended
    // range catches the new max Apéry = 7, recovering ⟨2, 7⟩.
    let s = compute(&[2, 5]);
    let parent = s.ascent();
    assert_eq!(parent.gen_set, vec![2, 7]);
}

#[test]
fn test_ascent_k_at_least_2_concrete() {
    // The k≥2 branch: an atom whose k-th multiple is an Apéry element
    // landing in V(S) gets toggled. The canonical witness is the
    // ⟨n, n+1⟩ family for n ≥ 4: with a = n+1 and k = n−2,
    //   k·a = (n−2)(n+1) = w_{n−2} ∈ V(S).
    //
    // ⟨4, 5⟩: at k=2, atom 5 satisfies 2·5 = 10 = w₂ ∈ (7, 11).
    // Ascent toggles 5, leaving the previously-Apéry multiples
    // {2·5, 3·5} = {10, 15} as fresh atoms.
    let s = compute(&[4, 5]);
    let up = s.ascent();
    assert!(up.gen_set.contains(&10), "expected 10 = 2·5 as a new atom");
    assert!(up.gen_set.contains(&15), "expected 15 = 3·5 as a new atom");
    assert!(!up.gen_set.contains(&5), "atom 5 should be removed");
    assert_eq!(up.g, s.g + 1, "k≥2 ascent always adds exactly one gap");

    // ⟨5, 6⟩: at k=3, atom 6 satisfies 3·6 = 18 = w_3 ∈ (14, 19).
    // 2·6 = 12 and 3·6 = 18 both end up as new atoms.
    let s = compute(&[5, 6]);
    let up = s.ascent();
    assert!(up.gen_set.contains(&12));
    assert!(up.gen_set.contains(&18));
    assert!(!up.gen_set.contains(&6));
    assert_eq!(up.g, s.g + 1);
}

#[test]
fn test_apery_shift_first_when_kunz_move_is_blocked() {
    // For <6,9,20>, w₂+w₅ = 20+29 = 49 = w₁, so c_25 = 0 and the move
    // would force c_25 → -1. compute() then collapses back: 9 + 40 = 49
    // regenerates the original w₁, so the result equals the input semigroup.
    let s = compute(&[6, 9, 20]);
    let s2 = s.compute_apery_shift_first();
    assert_eq!(
        s.partial_cmp(&s2),
        Some(std::cmp::Ordering::Equal),
        "blocked Kunz move should collapse to the original semigroup",
    );
}

#[test]
fn test_up_down_identity_fpm_branch() {
    // descent(ascent(S)) == S whenever ascent enters its f+m branch:
    // f+m is a min-gen and no min-gen lies in (m, f) with g + m > f.
    // The fixed cases are picked to span a few multiplicities.
    for gens in [
        &[5_usize, 7, 23][..], // m=5, f=18, f+m=23 is the only min-gen in (m,f+m]
        &[2, 5][..],           // m=2, f=3,  f+m=5 is a min-gen, (m,f) is empty
        &[3, 7, 8][..],        // m=3, f=5,  f+m=8 is a min-gen, no g in (3,5)
        &[4, 6, 7, 9][..],     // m=4, f=5,  f+m=9 is a min-gen, no g in (4,5)
    ] {
        let s = compute(gens);
        let no_large_mingen = !s
            .gen_set
            .iter()
            .any(|&g| g > s.m && g < s.f && g + s.m > s.f);
        let fpm_is_mingen = s.gen_set.contains(&(s.f + s.m));
        assert!(
            no_large_mingen,
            "precondition mismatch for {gens:?}: large min-gen present"
        );
        assert!(
            fpm_is_mingen,
            "precondition mismatch for {gens:?}: f+m not a min-gen"
        );
        assert_eq!(s, s.ascent().descent(), "up-down identity for {gens:?}");
    }
}
