use wasm_bindgen::prelude::*;
// compute the greatest common divisor of two numbers
pub fn gcd(mut a: usize, mut b: usize) -> usize {
    while b != 0 {
        (a, b) = (b, a % b);
    }
    a
}

// compute the greatest common divisor of a vector of numbers

pub fn gcd_vec(numbers: &[usize]) -> usize {
    let mut d = numbers[0];
    for m in &numbers[1..] {
        d = gcd(d, *m);
    }
    d
}

//
// simple struct to hold the results
//
#[derive(Debug,Clone,PartialEq,Eq,Ord,PartialOrd)]
pub struct Semigroup {
    // e is the embedding dimension, f is the Frobenius number, m is the multiplicity
    // gen_set is the set of minimal generators, apery_set is the Apery set with respect to m
    // count_set is the number of elements in the semigroup <f - the sporadic elements
    // count_gap is the number of gaps
    // b is the number of reflected gaps (i.e. gaps g such that f-g is also a gap)
    // blob_set is the set of reflected gaps
    pub e:usize,
    pub f:usize,
    pub m:usize,
    pub count_set:usize,
    pub count_gap:usize,
    pub max_gen:usize,
    pub gen_set:Vec<usize>,
    pub apery_set:Vec<usize>,
}
impl Semigroup {
    // check if a number is an element of the semigroup
    pub fn element(&self, x: usize) -> bool {
        let modulus = x % self.m;
        let ap = self.apery_set[modulus];
        x >= ap
    }
    // check if a number is a gap of the semigroup
    pub fn is_gap(&self, x: usize) -> bool {
        !self.element(x)
    }

    // check if symmetric
    pub fn is_symmetric(&self) -> bool {
        let sym = &self.count_gap==&self.count_set;
        assert!(!sym || self.f+1==2*self.count_gap);
        sym
    }

    // compute the wilf quotient
    pub fn wilf(&self)->f64 {
        let c = self.f as f64 + 1.0f64;
        let spor = self.count_set as f64;
        spor /c
    }

    // check if a number is a reflected gap
    pub fn is_reflected_gap(&self, x: usize) -> bool {
        self.is_gap(x) && self.is_gap(self.f - x)
    }

    // get the blob, the number of reflected gaps
    pub fn blob(&self) -> Vec<usize> {
        (0..self.f).filter(|&x| self.is_reflected_gap(x)).collect()
    }

    // compute the kunz overshoot apery[i]+apery[j]-apery[i+j%m] / m
    // when displayed, it should be a symmetric matix
    // the i-th row sums should be the i-th aperyelement
    pub fn kunz(&self, i: usize, j:usize) -> usize {
        let first = i % self.m;
        let second = j % self.m;
        let idx = (i+j) % self.m;
        let sum = &self.apery_set[first] + &self.apery_set[second];
        assert!(sum >= self.apery_set[idx]);
        let res = sum - self.apery_set[idx];
        assert_eq!(0,res %self.m,"ai+aj-a(i+j) immer duch m teilbar!");
        res / &self.m
    }

    //
    // computes PF(S), the set of pseudo-frobenius numers
    // the reflected gaps x such that x+(element of S > 0) is always in S
    // and the type t, the number of this
    //
    pub fn pft(&self) -> (Vec<usize>,usize) {
        let mut pf:Vec<usize> = self.blob().into_iter().filter(|&g| {
            self.gen_set.iter().all(|&a| self.element(a + g))
        }).collect();
        pf.push(self.f);
        let t = pf.len();
        (pf,t)
    }
}


//
// compute the numerical semigroup generated by the numbers in the slice "input"
//
// the algorithm is very simple, inspired by wilf ("the circle of lights")
// we just move a window of width 2*(maximal input) along the natural numbers
//
//
//
pub fn compute(input: &[usize]) -> Semigroup {
    let d = gcd_vec(input);
    let mut inputnumbers: Vec<usize> = input.iter().map(|x| x / d).collect();
    inputnumbers.sort();

    let maximal_input: usize = *inputnumbers.last().unwrap();
    let width=2*maximal_input;
    let m: usize = *inputnumbers.first().unwrap();

    let mut aperyset: Vec<usize> = vec![0; m];
    let mut count_set = 1usize; // 0 is already an element in this set
    let mut window = vec![-1isize; width]; // here we store the results
    let mut windowindex = m; // this is the running index
    let mut runlength = 0usize; // number of consecutive hits
    let mut hit: bool = false; // true if the number windowindex is in S
    let mut max_apery:usize = m;
    let mut sum_apery:usize = 0;
    let mut minimal_generators:usize = 1;
    let mut max_atom = m;
    let mut genset:Vec<usize> = Vec::new();
    window[0]=0;
    let mut i: usize = m; // startindex
    while runlength < m {
        let residue = i % m;
        if 0 == residue {
            // case: a multiple of m
            count_set += 1;
            runlength += 1;
            hit = true;
            window[windowindex] = i as isize;
        } else if aperyset[residue]>0 && i > aperyset[residue] {
            // case: we already have found an element in this residue class
            count_set += 1;
            runlength += 1;
            hit = true;
            window[windowindex] = i as isize;
        }
        else {
            // ok, we must ckeck this number by going back to windowindex-generator for all generators
            for k in inputnumbers[1..].iter() {
                if windowindex >= *k && window[windowindex - k] >= 0 {
                    // case window[windowindex - k] is already an element of S
                    count_set += 1;
                    runlength += 1;
                    hit = true;
                    window[windowindex] = i as isize;
                    aperyset[residue] = i;
                    sum_apery+=i;
                    if i>max_apery { max_apery = i}
                    if 0==window[windowindex - *k] {
                        minimal_generators+=1;
                        genset.push(i);
                        if max_atom < i {max_atom=i};
                    }
                    break;
                }
            }
        }
        if !hit { runlength = 0 };
        hit = false;
        i += 1;
        //
        // copy the right half of the window to the left and continue
        //
        if windowindex == width - 1 {
            let (dst, src) = window.split_at_mut(maximal_input);
            dst[0..maximal_input].clone_from_slice(&src[..maximal_input]);
            windowindex = maximal_input;
        } else {
            windowindex += 1;
        }
    }
    genset.push(m);
    assert_eq!(genset.len(),minimal_generators);
    genset.sort();
    assert_eq!(aperyset.len(),m);

    Semigroup{
        e:minimal_generators,
        f:max_apery-m,
        m,
        count_set:count_set-m,
        count_gap:(sum_apery - ((m - 1) * m) / 2) / m,
        max_gen:*genset.iter().max().unwrap(),
        gen_set:genset,
        apery_set:aperyset,
    }
}

pub mod js_helper;

// the following is the interface to JavaScript
#[wasm_bindgen]
pub struct JsSemigroup (pub(crate) Semigroup);

#[wasm_bindgen]
impl JsSemigroup {
    #[wasm_bindgen(getter)] pub fn e(&self)         -> usize { self.0.e }
    #[wasm_bindgen(getter)] pub fn f(&self)         -> usize { self.0.f }
    #[wasm_bindgen(getter)] pub fn m(&self)         -> usize { self.0.m }
    #[wasm_bindgen(getter)] pub fn count_set(&self) -> usize { self.0.count_set }
    #[wasm_bindgen(getter)] pub fn count_gap(&self) -> usize { self.0.count_gap }
    #[wasm_bindgen(getter)] pub fn max_gen(&self)   -> usize { self.0.max_gen }

    #[wasm_bindgen(getter)]
    pub fn gen_set(&self)   -> Vec<u32> { self.0.gen_set.iter().map(|&x| x as u32).collect() }
    #[wasm_bindgen(getter)]
    pub fn apery_set(&self) -> Vec<u32> { self.0.apery_set.iter().map(|&x| x as u32).collect() }
    #[wasm_bindgen(getter)]
    pub fn blob(&self)      -> Vec<u32> { self.0.blob().iter().map(|&x| x as u32).collect() }

    pub fn is_element(&self, x: usize) -> bool { self.0.element(x) }
    pub fn kunz(&self, i: usize, j: usize) -> usize { self.0.kunz(i, j) }

    #[wasm_bindgen(getter)]
    pub fn is_symmetric(&self) -> bool { self.0.is_symmetric() }
    #[wasm_bindgen(getter)]
    pub fn wilf(&self) -> f64 { self.0.wilf() }

    #[wasm_bindgen(getter)]
    pub fn pf(&self) -> Vec<u32> { let (pf, _) = self.0.pft(); pf.iter().map(|&x| x as u32).collect() }
    #[wasm_bindgen(getter)]
    pub fn type_t(&self) -> usize { self.0.pft().1 }
}

#[wasm_bindgen]
pub fn js_compute(input: &str) -> JsSemigroup {
    let numbers: Vec<usize> = input
        .split(',')
        .filter_map(|s| s.trim().parse().ok())
        .collect();
    JsSemigroup(compute(&numbers))
}


#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_gcd() {
        assert_eq!(gcd(12, 8), 4);
        assert_eq!(gcd(7, 3), 1);
        assert_eq!(gcd(0, 5), 5);
        assert_eq!(gcd(9, 0), 9);
    }

    #[test]
    fn test_semigroup_2_3() {
        let s = compute(&[2, 3]);
        assert_eq!(s.e, 2);
        assert_eq!(s.f, 1);
        let s = compute(&[21,23,27,29,30]);
        assert_eq!(s.blob().len()+s.count_set,s.count_gap);
    }
}
