use wasm_bindgen::prelude::*;
// compute the greatest common divisor of two numbers
pub fn gcd(mut a: usize, mut b: usize) -> usize {
    while b != 0 {
        (a, b) = (b, a % b);
    }
    a
}

// compute the greatest common divisor of a vector of numbers

pub fn gcd_vec(numbers: &[usize]) -> usize {
    let mut d = numbers[0];
    for m in &numbers[1..] {
        d = gcd(d, *m);
    }
    d
}

//
// simple struct to hold the results
//
pub struct Semigroup {
    // e is the embedding dimension, f is the Frobenius number, m is the multiplicity
    // gen_set is the set of minimal generators, apery_set is the Apery set with respect to m
    // count_set is the number of elements in the semigroup <f - the sporadic elements
    // count_gap is the number of gaps
    // b is the number of reflected gaps (i.e. gaps g such that f-g is also a gap)
    // blob_set is the set of reflected gaps
    pub e:usize,
    pub f:usize,
    pub m:usize,
    pub count_set:usize,
    pub count_gap:usize,
    pub max_gen:usize,
    pub gen_set:Vec<usize>,
    pub apery_set:Vec<usize>,
}

impl Semigroup {
    // check if a number is an element of the semigroup
    pub fn element(&self, x: usize) -> bool {
        let modu = x % self.m;
        let ap = self.apery_set[modu];
        x >= ap
    }
    // check if a number is a gap of the semigroup
    pub fn is_gap(&self, x: usize) -> bool {
        !self.element(x)
    }

    // check if a number is a reflected gap
    pub fn is_reflected_gap(&self, x: usize) -> bool {
        self.is_gap(x) && self.is_gap(self.f - x)
    }

    // get the blob, the number of reflected gaps
    pub fn blob(&self) -> Vec<usize> {
        (0..self.f).filter(|&x| self.is_reflected_gap(x)).collect()
    }
}


//
// compute the numerical semigroup generated by the numbers in the slice "input"
//
// the algorithm is very simple, inspired by wilf ("the circle of lights")
// we just move a window of width 2*(maximal input) along the natural numbers
//
//
//
pub fn compute(input: &[usize]) -> Semigroup {
    let d = gcd_vec(input);
    let mut inputnumbers: Vec<usize> = input.iter().map(|x| x / d).collect();
    inputnumbers.sort();

    let maximal_input: usize = *inputnumbers.last().unwrap();
    let width=2*maximal_input;
    let m: usize = *inputnumbers.first().unwrap();

    let mut aperyset: Vec<usize> = vec![0; m];
    let mut count_set = 1usize; // 0 is already an element in this set
    let mut window = vec![-1isize; width]; // here we store the results
    let mut windowindex = m; // this is the running index
    let mut runlength = 0usize; // number of consecutive hits
    let mut hit: bool = false; // true if the number windowindex is in S
    let mut max_apery:usize = m;
    let mut sum_apery:usize = 0;
    let mut minimal_generators:usize = 1;
    let mut max_atom = m;
    let mut genset:Vec<usize> = Vec::new();
    window[0]=0;
    let mut i: usize = m; // startindex
    while runlength < m {
        let residue = i % m;
        if 0 == residue {
            // case: a multiple of m
            count_set += 1;
            runlength += 1;
            hit = true;
            window[windowindex] = i as isize;
        } else if aperyset[residue]>0 && i > aperyset[residue] {
            // case: we already have found an element in this residue class
            count_set += 1;
            runlength += 1;
            hit = true;
            window[windowindex] = i as isize;
        }
        else {
            // ok, we must ckeck this number by going back to windowindex-generator for all generators
            for k in inputnumbers[1..].iter() {
                if windowindex >= *k && window[windowindex - k] >= 0 {
                    // case window[windowindex - k] is already an element of S
                    count_set += 1;
                    runlength += 1;
                    hit = true;
                    window[windowindex] = i as isize;
                    aperyset[residue] = i;
                    sum_apery+=i;
                    if i>max_apery { max_apery = i}
                    if 0==window[windowindex - *k] {
                        minimal_generators+=1;
                        genset.push(i);
                        if max_atom < i {max_atom=i};
                    }
                    break;
                }
            }
        }
        if !hit { runlength = 0 };
        hit = false;
        i += 1;
        //
        // copy the right half of the window to the left and continue
        //
        if windowindex == width - 1 {
            let (dst, src) = window.split_at_mut(maximal_input);
            dst[0..maximal_input].clone_from_slice(&src[..maximal_input]);
            windowindex = maximal_input;
        } else {
            windowindex += 1;
        }
    }
    genset.push(m);
    assert_eq!(genset.len(),minimal_generators);
    genset.sort();
    assert_eq!(aperyset.len(),m);

    Semigroup{
        e:minimal_generators,
        f:max_apery-m,
        m,
        count_set:count_set-m,
        count_gap:(sum_apery - ((m - 1) * m) / 2) / m,
        max_gen:*genset.iter().max().unwrap(),
        gen_set:genset,
        apery_set:aperyset,
    }
}





#[wasm_bindgen]
pub fn js_semigroup(input: &str) -> String {
    let numbers: Vec<usize> = input
        .split(',')
        .filter_map(|s| s.trim().parse().ok())
        .collect();
    let s = compute(&numbers);
    format!(
        "{{\"e\":{},\"f\":{},\"m\":{},\"count_set\":{},\"count_gap\":{},\"max_gen\":{},\"gen_set\":{:?},\"apery_set\":{:?}}}",
        s.e, s.f, s.m, s.count_set, s.count_gap, s.max_gen, s.gen_set, s.apery_set
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_gcd() {
        assert_eq!(gcd(12, 8), 4);
        assert_eq!(gcd(7, 3), 1);
        assert_eq!(gcd(0, 5), 5);
        assert_eq!(gcd(9, 0), 9);
    }

    #[test]
    fn test_semigroup_2_3() {
        let s = compute(&[2, 3]);
        assert_eq!(s.e, 2);
        assert_eq!(s.f, 1);
        let s = compute(&[21,23,27,29,30]);
        assert_eq!(s.blob().len()+s.count_set,s.count_gap);
    }
}
