# Generated by f3m — paste into GAP or run with 'gap <file>'
# Requires: LoadPackage("NumericalSgps");

LoadPackage("NumericalSgps");;

# ── Semigroup 1: <6, 9, 20> ──
ng1 := NumericalSemigroup(6,9,20);
Assert(0, Multiplicity(ng1) = 6);
Assert(0, FrobeniusNumber(ng1) = 43);
Assert(0, EmbeddingDimension(ng1) = 3);
Assert(0, GenusOfNumericalSemigroup(ng1) = 22);
Assert(0, 1 + FrobeniusNumber(ng1) - GenusOfNumericalSemigroup(ng1) = 22);
Assert(0, IsSymmetric(ng1) = true);
Assert(0, AperyList(ng1, 6) = [0,49,20,9,40,29]);
Assert(0, Set(PseudoFrobeniusOfNumericalSemigroup(ng1)) = Set([43]));
Assert(0, TypeOfNumericalSemigroup(ng1) = 1);

# ── Semigroup 2: <12, 14, 19, 77> ──
ng2 := NumericalSemigroup(12,14,19,77);
Assert(0, Multiplicity(ng2) = 12);
Assert(0, FrobeniusNumber(ng2) = 65);
Assert(0, EmbeddingDimension(ng2) = 4);
Assert(0, GenusOfNumericalSemigroup(ng2) = 38);
Assert(0, 1 + FrobeniusNumber(ng2) - GenusOfNumericalSemigroup(ng2) = 28);
Assert(0, IsSymmetric(ng2) = false);
Assert(0, AperyList(ng2, 12) = [0,61,14,75,28,77,42,19,56,33,70,47]);
Assert(0, Set(PseudoFrobeniusOfNumericalSemigroup(ng2)) = Set([58,63,65]));
Assert(0, TypeOfNumericalSemigroup(ng2) = 3);

# ── Semigroup 3: <20, 44, 54, 73, 77, 89, 90> ──
ng3 := NumericalSemigroup(20,44,54,73,77,89,90);
Assert(0, Multiplicity(ng3) = 20);
Assert(0, FrobeniusNumber(ng3) = 159);
Assert(0, EmbeddingDimension(ng3) = 7);
Assert(0, GenusOfNumericalSemigroup(ng3) = 103);
Assert(0, 1 + FrobeniusNumber(ng3) - GenusOfNumericalSemigroup(ng3) = 57);
Assert(0, IsSymmetric(ng3) = false);
Assert(0, AperyList(ng3, 20) = [0,121,142,143,44,165,146,127,88,89,90,131,132,73,54,175,176,77,98,179]);
Assert(0, Set(PseudoFrobeniusOfNumericalSemigroup(ng3)) = Set([107,122,123,126,145,155,156,159]));
Assert(0, TypeOfNumericalSemigroup(ng3) = 8);

# ── Semigroup 4: <13, 17, 27> ──
ng4 := NumericalSemigroup(13,17,27);
Assert(0, Multiplicity(ng4) = 13);
Assert(0, FrobeniusNumber(ng4) = 89);
Assert(0, EmbeddingDimension(ng4) = 3);
Assert(0, GenusOfNumericalSemigroup(ng4) = 48);
Assert(0, 1 + FrobeniusNumber(ng4) - GenusOfNumericalSemigroup(ng4) = 42);
Assert(0, IsSymmetric(ng4) = false);
Assert(0, AperyList(ng4, 13) = [0,27,54,68,17,44,71,85,34,61,88,102,51]);
Assert(0, Set(PseudoFrobeniusOfNumericalSemigroup(ng4)) = Set([75,89]));
Assert(0, TypeOfNumericalSemigroup(ng4) = 2);

# ── Semigroup 5: <20, 28, 30, 46, 47> ──
ng5 := NumericalSemigroup(20,28,30,46,47);
Assert(0, Multiplicity(ng5) = 20);
Assert(0, FrobeniusNumber(ng5) = 129);
Assert(0, EmbeddingDimension(ng5) = 5);
Assert(0, GenusOfNumericalSemigroup(ng5) = 71);
Assert(0, 1 + FrobeniusNumber(ng5) - GenusOfNumericalSemigroup(ng5) = 59);
Assert(0, IsSymmetric(ng5) = false);
Assert(0, AperyList(ng5, 20) = [0,121,102,103,84,105,46,47,28,149,30,131,92,93,74,75,56,77,58,139]);
Assert(0, Set(PseudoFrobeniusOfNumericalSemigroup(ng5)) = Set([85,111,119,129]));
Assert(0, TypeOfNumericalSemigroup(ng5) = 4);

# ── Semigroup 6: <18, 40, 49, 51, 78, 93> ──
ng6 := NumericalSemigroup(18,40,49,51,78,93);
Assert(0, Multiplicity(ng6) = 18);
Assert(0, FrobeniusNumber(ng6) = 164);
Assert(0, EmbeddingDimension(ng6) = 6);
Assert(0, GenusOfNumericalSemigroup(ng6) = 93);
Assert(0, 1 + FrobeniusNumber(ng6) - GenusOfNumericalSemigroup(ng6) = 72);
Assert(0, IsSymmetric(ng6) = false);
Assert(0, AperyList(ng6, 18) = [0,91,182,93,40,131,78,133,80,153,100,173,102,49,140,51,142,89]);
Assert(0, Set(PseudoFrobeniusOfNumericalSemigroup(ng6)) = Set([60,122,135,155,164]));
Assert(0, TypeOfNumericalSemigroup(ng6) = 5);

# ── Semigroup 7: <46, 47, 54, 62, 66, 69, 70, 85> ──
ng7 := NumericalSemigroup(46,47,54,62,66,69,70,85);
Assert(0, Multiplicity(ng7) = 46);
Assert(0, FrobeniusNumber(ng7) = 219);
Assert(0, EmbeddingDimension(ng7) = 8);
Assert(0, GenusOfNumericalSemigroup(ng7) = 128);
Assert(0, 1 + FrobeniusNumber(ng7) - GenusOfNumericalSemigroup(ng7) = 92);
Assert(0, IsSymmetric(ng7) = false);
Assert(0, AperyList(ng7, 46) = [0,47,94,141,188,189,190,237,54,101,148,195,242,151,198,245,62,109,156,203,66,113,160,69,70,117,164,211,120,167,214,123,124,171,218,265,128,175,222,85,132,179,226,135,136,183]);
Assert(0, Set(PseudoFrobeniusOfNumericalSemigroup(ng7)) = Set([143,168,176,180,191,196,199,219]));
Assert(0, TypeOfNumericalSemigroup(ng7) = 8);

# ── Semigroup 8: <11, 15, 17, 38> ──
ng8 := NumericalSemigroup(11,15,17,38);
Assert(0, Multiplicity(ng8) = 11);
Assert(0, FrobeniusNumber(ng8) = 57);
Assert(0, EmbeddingDimension(ng8) = 4);
Assert(0, GenusOfNumericalSemigroup(ng8) = 30);
Assert(0, 1 + FrobeniusNumber(ng8) - GenusOfNumericalSemigroup(ng8) = 28);
Assert(0, IsSymmetric(ng8) = false);
Assert(0, AperyList(ng8, 11) = [0,34,68,47,15,38,17,51,30,53,32]);
Assert(0, Set(PseudoFrobeniusOfNumericalSemigroup(ng8)) = Set([36,57]));
Assert(0, TypeOfNumericalSemigroup(ng8) = 2);

# ── Semigroup 9: <19, 24, 27, 32> ──
ng9 := NumericalSemigroup(19,24,27,32);
Assert(0, Multiplicity(ng9) = 19);
Assert(0, FrobeniusNumber(ng9) = 125);
Assert(0, EmbeddingDimension(ng9) = 4);
Assert(0, GenusOfNumericalSemigroup(ng9) = 67);
Assert(0, 1 + FrobeniusNumber(ng9) - GenusOfNumericalSemigroup(ng9) = 59);
Assert(0, IsSymmetric(ng9) = false);
Assert(0, AperyList(ng9, 19) = [0,96,59,136,80,24,120,64,27,104,48,144,88,32,128,72,54,112,56]);
Assert(0, Set(PseudoFrobeniusOfNumericalSemigroup(ng9)) = Set([35,40,109,117,125]));
Assert(0, TypeOfNumericalSemigroup(ng9) = 5);

# ── Semigroup 10: <16, 26, 36, 75, 81, 82> ──
ng10 := NumericalSemigroup(16,26,36,75,81,82);
Assert(0, Multiplicity(ng10) = 16);
Assert(0, FrobeniusNumber(ng10) = 167);
Assert(0, EmbeddingDimension(ng10) = 6);
Assert(0, GenusOfNumericalSemigroup(ng10) = 86);
Assert(0, 1 + FrobeniusNumber(ng10) - GenusOfNumericalSemigroup(ng10) = 82);
Assert(0, IsSymmetric(ng10) = false);
Assert(0, AperyList(ng10, 16) = [0,81,82,147,36,101,118,183,72,137,26,75,108,157,62,111]);
Assert(0, Set(PseudoFrobeniusOfNumericalSemigroup(ng10)) = Set([65,102,121,167]));
Assert(0, TypeOfNumericalSemigroup(ng10) = 4);

Print("All assertions passed.\n");

# Generated by f3m — paste into GAP or run with 'gap <file>'
# Requires: LoadPackage("NumericalSgps");

LoadPackage("NumericalSgps");;

# ── Semigroup 1: <6, 9, 20> ──
ng1 := NumericalSemigroup(6,9,20);
Assert(0, Multiplicity(ng1) = 6);
Assert(0, FrobeniusNumber(ng1) = 43);
Assert(0, EmbeddingDimension(ng1) = 3);
Assert(0, GenusOfNumericalSemigroup(ng1) = 22);
Assert(0, 1 + FrobeniusNumber(ng1) - GenusOfNumericalSemigroup(ng1) = 22);
Assert(0, IsSymmetric(ng1) = true);
Assert(0, AperyList(ng1, 6) = [0,49,20,9,40,29]);
Assert(0, Set(PseudoFrobeniusOfNumericalSemigroup(ng1)) = Set([43]));
Assert(0, TypeOfNumericalSemigroup(ng1) = 1);

# ── Semigroup 2: <12, 30, 32, 38, 40, 41> ──
ng2 := NumericalSemigroup(12,30,32,38,40,41);
Assert(0, Multiplicity(ng2) = 12);
Assert(0, FrobeniusNumber(ng2) = 99);
Assert(0, EmbeddingDimension(ng2) = 6);
Assert(0, GenusOfNumericalSemigroup(ng2) = 50);
Assert(0, 1 + FrobeniusNumber(ng2) - GenusOfNumericalSemigroup(ng2) = 50);
Assert(0, IsSymmetric(ng2) = true);
Assert(0, AperyList(ng2, 12) = [0,73,38,111,40,41,30,79,32,81,70,71]);
Assert(0, Set(PseudoFrobeniusOfNumericalSemigroup(ng2)) = Set([99]));
Assert(0, TypeOfNumericalSemigroup(ng2) = 1);

# ── Semigroup 3: <12, 30, 32, 38, 40, 41, 99> ──
ng3 := NumericalSemigroup(12,30,32,38,40,41,99);
Assert(0, Multiplicity(ng3) = 12);
Assert(0, FrobeniusNumber(ng3) = 87);
Assert(0, EmbeddingDimension(ng3) = 7);
Assert(0, GenusOfNumericalSemigroup(ng3) = 49);
Assert(0, 1 + FrobeniusNumber(ng3) - GenusOfNumericalSemigroup(ng3) = 39);
Assert(0, IsSymmetric(ng3) = false);
Assert(0, AperyList(ng3, 12) = [0,73,38,99,40,41,30,79,32,81,70,71]);
Assert(0, Set(PseudoFrobeniusOfNumericalSemigroup(ng3)) = Set([58,59,61,67,69,87]));
Assert(0, TypeOfNumericalSemigroup(ng3) = 6);

# ── Semigroup 4: <12, 30, 32, 38, 40, 41> ──
ng4 := NumericalSemigroup(12,30,32,38,40,41);
Assert(0, Multiplicity(ng4) = 12);
Assert(0, FrobeniusNumber(ng4) = 99);
Assert(0, EmbeddingDimension(ng4) = 6);
Assert(0, GenusOfNumericalSemigroup(ng4) = 50);
Assert(0, 1 + FrobeniusNumber(ng4) - GenusOfNumericalSemigroup(ng4) = 50);
Assert(0, IsSymmetric(ng4) = true);
Assert(0, AperyList(ng4, 12) = [0,73,38,111,40,41,30,79,32,81,70,71]);
Assert(0, Set(PseudoFrobeniusOfNumericalSemigroup(ng4)) = Set([99]));
Assert(0, TypeOfNumericalSemigroup(ng4) = 1);

# ── Semigroup 5: <12, 42, 44, 50, 52, 53, 82, 83, 85, 91, 93> ──
ng5 := NumericalSemigroup(12,42,44,50,52,53,82,83,85,91,93);
Assert(0, Multiplicity(ng5) = 12);
Assert(0, FrobeniusNumber(ng5) = 123);
Assert(0, EmbeddingDimension(ng5) = 11);
Assert(0, GenusOfNumericalSemigroup(ng5) = 62);
Assert(0, 1 + FrobeniusNumber(ng5) - GenusOfNumericalSemigroup(ng5) = 62);
Assert(0, IsSymmetric(ng5) = true);
Assert(0, AperyList(ng5, 12) = [0,85,50,135,52,53,42,91,44,93,82,83]);
Assert(0, Set(PseudoFrobeniusOfNumericalSemigroup(ng5)) = Set([123]));
Assert(0, TypeOfNumericalSemigroup(ng5) = 1);

# ── Semigroup 6: <12, 54, 56, 62, 64, 65, 94, 95, 97, 103, 105> ──
ng6 := NumericalSemigroup(12,54,56,62,64,65,94,95,97,103,105);
Assert(0, Multiplicity(ng6) = 12);
Assert(0, FrobeniusNumber(ng6) = 147);
Assert(0, EmbeddingDimension(ng6) = 11);
Assert(0, GenusOfNumericalSemigroup(ng6) = 74);
Assert(0, 1 + FrobeniusNumber(ng6) - GenusOfNumericalSemigroup(ng6) = 74);
Assert(0, IsSymmetric(ng6) = true);
Assert(0, AperyList(ng6, 12) = [0,97,62,159,64,65,54,103,56,105,94,95]);
Assert(0, Set(PseudoFrobeniusOfNumericalSemigroup(ng6)) = Set([147]));
Assert(0, TypeOfNumericalSemigroup(ng6) = 1);

# ── Semigroup 7: <12, 66, 68, 74, 76, 77, 106, 107, 109, 115, 117> ──
ng7 := NumericalSemigroup(12,66,68,74,76,77,106,107,109,115,117);
Assert(0, Multiplicity(ng7) = 12);
Assert(0, FrobeniusNumber(ng7) = 171);
Assert(0, EmbeddingDimension(ng7) = 11);
Assert(0, GenusOfNumericalSemigroup(ng7) = 86);
Assert(0, 1 + FrobeniusNumber(ng7) - GenusOfNumericalSemigroup(ng7) = 86);
Assert(0, IsSymmetric(ng7) = true);
Assert(0, AperyList(ng7, 12) = [0,109,74,183,76,77,66,115,68,117,106,107]);
Assert(0, Set(PseudoFrobeniusOfNumericalSemigroup(ng7)) = Set([171]));
Assert(0, TypeOfNumericalSemigroup(ng7) = 1);

# ── Semigroup 8: <12, 78, 80, 86, 88, 89, 118, 119, 121, 127, 129> ──
ng8 := NumericalSemigroup(12,78,80,86,88,89,118,119,121,127,129);
Assert(0, Multiplicity(ng8) = 12);
Assert(0, FrobeniusNumber(ng8) = 195);
Assert(0, EmbeddingDimension(ng8) = 11);
Assert(0, GenusOfNumericalSemigroup(ng8) = 98);
Assert(0, 1 + FrobeniusNumber(ng8) - GenusOfNumericalSemigroup(ng8) = 98);
Assert(0, IsSymmetric(ng8) = true);
Assert(0, AperyList(ng8, 12) = [0,121,86,207,88,89,78,127,80,129,118,119]);
Assert(0, Set(PseudoFrobeniusOfNumericalSemigroup(ng8)) = Set([195]));
Assert(0, TypeOfNumericalSemigroup(ng8) = 1);

# ── Semigroup 9: <12, 90, 92, 98, 100, 101, 130, 131, 133, 139, 141> ──
ng9 := NumericalSemigroup(12,90,92,98,100,101,130,131,133,139,141);
Assert(0, Multiplicity(ng9) = 12);
Assert(0, FrobeniusNumber(ng9) = 219);
Assert(0, EmbeddingDimension(ng9) = 11);
Assert(0, GenusOfNumericalSemigroup(ng9) = 110);
Assert(0, 1 + FrobeniusNumber(ng9) - GenusOfNumericalSemigroup(ng9) = 110);
Assert(0, IsSymmetric(ng9) = true);
Assert(0, AperyList(ng9, 12) = [0,133,98,231,100,101,90,139,92,141,130,131]);
Assert(0, Set(PseudoFrobeniusOfNumericalSemigroup(ng9)) = Set([219]));
Assert(0, TypeOfNumericalSemigroup(ng9) = 1);

# ── Semigroup 10: <12, 102, 104, 110, 112, 113, 142, 143, 145, 151, 153> ──
ng10 := NumericalSemigroup(12,102,104,110,112,113,142,143,145,151,153);
Assert(0, Multiplicity(ng10) = 12);
Assert(0, FrobeniusNumber(ng10) = 243);
Assert(0, EmbeddingDimension(ng10) = 11);
Assert(0, GenusOfNumericalSemigroup(ng10) = 122);
Assert(0, 1 + FrobeniusNumber(ng10) - GenusOfNumericalSemigroup(ng10) = 122);
Assert(0, IsSymmetric(ng10) = true);
Assert(0, AperyList(ng10, 12) = [0,145,110,255,112,113,102,151,104,153,142,143]);
Assert(0, Set(PseudoFrobeniusOfNumericalSemigroup(ng10)) = Set([243]));
Assert(0, TypeOfNumericalSemigroup(ng10) = 1);

# ── Semigroup 11: <12, 102, 104, 110, 112, 113, 142, 143, 145, 151, 153, 243> ──
ng11 := NumericalSemigroup(12,102,104,110,112,113,142,143,145,151,153,243);
Assert(0, Multiplicity(ng11) = 12);
Assert(0, FrobeniusNumber(ng11) = 231);
Assert(0, EmbeddingDimension(ng11) = 12);
Assert(0, GenusOfNumericalSemigroup(ng11) = 121);
Assert(0, 1 + FrobeniusNumber(ng11) - GenusOfNumericalSemigroup(ng11) = 111);
Assert(0, IsSymmetric(ng11) = false);
Assert(0, AperyList(ng11, 12) = [0,145,110,243,112,113,102,151,104,153,142,143]);
Assert(0, Set(PseudoFrobeniusOfNumericalSemigroup(ng11)) = Set([90,92,98,100,101,130,131,133,139,141,231]));
Assert(0, TypeOfNumericalSemigroup(ng11) = 11);

# ── Semigroup 12: <12, 102, 104, 110, 112, 113, 142, 143, 145, 151, 153, 231> ──
ng12 := NumericalSemigroup(12,102,104,110,112,113,142,143,145,151,153,231);
Assert(0, Multiplicity(ng12) = 12);
Assert(0, FrobeniusNumber(ng12) = 219);
Assert(0, EmbeddingDimension(ng12) = 12);
Assert(0, GenusOfNumericalSemigroup(ng12) = 120);
Assert(0, 1 + FrobeniusNumber(ng12) - GenusOfNumericalSemigroup(ng12) = 100);
Assert(0, IsSymmetric(ng12) = false);
Assert(0, AperyList(ng12, 12) = [0,145,110,231,112,113,102,151,104,153,142,143]);
Assert(0, Set(PseudoFrobeniusOfNumericalSemigroup(ng12)) = Set([90,92,98,100,101,130,131,133,139,141,219]));
Assert(0, TypeOfNumericalSemigroup(ng12) = 11);

# ── Semigroup 13: <12, 102, 104, 110, 112, 113, 142, 143, 145, 151, 153, 219> ──
ng13 := NumericalSemigroup(12,102,104,110,112,113,142,143,145,151,153,219);
Assert(0, Multiplicity(ng13) = 12);
Assert(0, FrobeniusNumber(ng13) = 207);
Assert(0, EmbeddingDimension(ng13) = 12);
Assert(0, GenusOfNumericalSemigroup(ng13) = 119);
Assert(0, 1 + FrobeniusNumber(ng13) - GenusOfNumericalSemigroup(ng13) = 89);
Assert(0, IsSymmetric(ng13) = false);
Assert(0, AperyList(ng13, 12) = [0,145,110,219,112,113,102,151,104,153,142,143]);
Assert(0, Set(PseudoFrobeniusOfNumericalSemigroup(ng13)) = Set([90,92,98,100,101,130,131,133,139,141,207]));
Assert(0, TypeOfNumericalSemigroup(ng13) = 11);

# ── Semigroup 14: <12, 102, 104, 110, 112, 113, 142, 143, 145, 151, 153, 207> ──
ng14 := NumericalSemigroup(12,102,104,110,112,113,142,143,145,151,153,207);
Assert(0, Multiplicity(ng14) = 12);
Assert(0, FrobeniusNumber(ng14) = 195);
Assert(0, EmbeddingDimension(ng14) = 12);
Assert(0, GenusOfNumericalSemigroup(ng14) = 118);
Assert(0, 1 + FrobeniusNumber(ng14) - GenusOfNumericalSemigroup(ng14) = 78);
Assert(0, IsSymmetric(ng14) = false);
Assert(0, AperyList(ng14, 12) = [0,145,110,207,112,113,102,151,104,153,142,143]);
Assert(0, Set(PseudoFrobeniusOfNumericalSemigroup(ng14)) = Set([90,92,98,100,101,130,131,133,139,141,195]));
Assert(0, TypeOfNumericalSemigroup(ng14) = 11);

# ── Semigroup 15: <12, 102, 104, 110, 112, 113, 142, 143, 145, 151, 153, 195> ──
ng15 := NumericalSemigroup(12,102,104,110,112,113,142,143,145,151,153,195);
Assert(0, Multiplicity(ng15) = 12);
Assert(0, FrobeniusNumber(ng15) = 183);
Assert(0, EmbeddingDimension(ng15) = 12);
Assert(0, GenusOfNumericalSemigroup(ng15) = 117);
Assert(0, 1 + FrobeniusNumber(ng15) - GenusOfNumericalSemigroup(ng15) = 67);
Assert(0, IsSymmetric(ng15) = false);
Assert(0, AperyList(ng15, 12) = [0,145,110,195,112,113,102,151,104,153,142,143]);
Assert(0, Set(PseudoFrobeniusOfNumericalSemigroup(ng15)) = Set([90,92,98,100,101,130,131,133,139,141,183]));
Assert(0, TypeOfNumericalSemigroup(ng15) = 11);

# ── Semigroup 16: <12, 102, 104, 110, 112, 113, 142, 143, 145, 151, 153, 183> ──
ng16 := NumericalSemigroup(12,102,104,110,112,113,142,143,145,151,153,183);
Assert(0, Multiplicity(ng16) = 13);
Assert(0, FrobeniusNumber(ng16) = 171);
Assert(0, EmbeddingDimension(ng16) = 12);
Assert(0, GenusOfNumericalSemigroup(ng16) = 116);
Assert(0, 1 + FrobeniusNumber(ng16) - GenusOfNumericalSemigroup(ng16) = 56);
Assert(0, IsSymmetric(ng16) = false);
Assert(0, AperyList(ng16, 12) = [0,145,110,183,112,113,102,151,104,153,142,143]);
Assert(0, Set(PseudoFrobeniusOfNumericalSemigroup(ng16)) = Set([90,92,98,100,101,130,131,133,139,141,171]));
Assert(0, TypeOfNumericalSemigroup(ng16) = 11);

# ── Semigroup 17: <12, 102, 104, 110, 112, 113, 142, 143, 145, 151, 153, 171> ──
ng17 := NumericalSemigroup(12,102,104,110,112,113,142,143,145,151,153,171);
Assert(1, Multiplicity(ng17) = 12);
Assert(0, FrobeniusNumber(ng17) = 159);
Assert(0, EmbeddingDimension(ng17) = 12);
Assert(0, GenusOfNumericalSemigroup(ng17) = 115);
Assert(0, 1 + FrobeniusNumber(ng17) - GenusOfNumericalSemigroup(ng17) = 45);
Assert(0, IsSymmetric(ng17) = false);
Assert(0, AperyList(ng17, 12) = [0,145,110,171,112,113,102,151,104,153,142,143]);
Assert(0, Set(PseudoFrobeniusOfNumericalSemigroup(ng17)) = Set([90,92,98,100,101,130,131,133,139,141,159]));
Assert(0, TypeOfNumericalSemigroup(ng17) = 11);

# ── Semigroup 18: <12, 102, 104, 110, 112, 113, 142, 143, 145, 151, 153, 159> ──
ng18 := NumericalSemigroup(12,102,104,110,112,113,142,143,145,151,153,159);
Assert(0, Multiplicity(ng18) = 12);
Assert(0, FrobeniusNumber(ng18) = 147);
Assert(0, EmbeddingDimension(ng18) = 12);
Assert(0, GenusOfNumericalSemigroup(ng18) = 114);
Assert(0, 1 + FrobeniusNumber(ng18) - GenusOfNumericalSemigroup(ng18) = 34);
Assert(0, IsSymmetric(ng18) = false);
Assert(0, AperyList(ng18, 12) = [0,145,110,159,112,113,102,151,104,153,142,143]);
Assert(0, Set(PseudoFrobeniusOfNumericalSemigroup(ng18)) = Set([90,92,98,100,101,130,131,133,139,141,147]));
Assert(0, TypeOfNumericalSemigroup(ng18) = 11);

Print("All assertions passed.\n");
